### ISSUE TITLE
Utilizing S3 Accelerate

### ISSUE THREAD

**Issue by deadjdona** [awslabs/aws-sdk-android-samples#101]
Good day.

Is it possible to use s3-accelerate as upload endpoint?

**Comment by mlshon** [comment]
Yes, you can use the Java example found [here](http://docs.aws.amazon.com/AmazonS3/latest/dev/transfer-acceleration-examples.html#transfer-acceleration-examples-java) to help you get started. Feel free to open again if you have any more questions.
