### ISSUE TITLE
S3 upload ssl exception

### ISSUE THREAD

**Issue by gokhanaliccii** [awslabs/aws-sdk-android-samples#103]
I tried d3 upload sample but always got "Unable to execute HTTP request: Write error: ssl=0x55a55d6250: I/O error during system call, Connection reset by peer" error   i share my problem on [link](http://stackoverflow.com/questions/42147282/android-file-upload-to-amazon-s3) 
I need help for solve exception

**Comment by minbi** [comment]
Are you using the sample in the repo or following the tutorial that you linked?

**Comment by gokhanaliccii** [comment]
I tried both of them. If you look upload method you will see they are same.

**Comment by gokhanaliccii** [comment]
I found my exception reason after 3 days. Reason is cognito credential region and s3 region at different region. I hope this answer help others
