### ISSUE TITLE
Android video uploading going to waiting state

### ISSUE THREAD

**Issue by cubatertech** [awslabs/aws-sdk-android-samples#104]
Hi, every body.

I face an issue but not on all devices. Android Note-3 with 5.0 version having some problem. If I upload a image or video to S3 bucket using Congnito credentails then app goes to waiting state not throw any exception. Please give tips why not upload file to S3. Thanks

**Comment by mlshon** [comment]
Could you provide more details for us?
What is the SDK version? Can you provide a code snippet?
What is the size of the video you're uploading?

**Comment by xiaoxiaohua333** [comment]
Hi,

This is my libs:
  compile files('libs/aws-android-sdk-cognito-2.4.5.jar')
    compile files('libs/aws-android-sdk-core-2.4.5.jar')
    compile files('libs/aws-android-sdk-s3-2.4.5.jar')

and I use the same  UploadActivity,Util from  S3TransferUtilitySample.But when I upload an img,the file goes to waiting state not throw any exception. I click the resume button,not work.The img is 113.60 KB. I have change my COGNITO_POOL_ID,BUCKET_NAME. The COGNITO_POOL_REGION 
is "ap-northeast-1".

How to show the log? Not throw any exception...

**Comment by kvasukib** [comment]
Thank you for reporting to us. Can you share the logs that are produced in the Android Studio console since the transfer started to the WAITING state? This would help us diagnose the issue. Does this happen with all files or occasionally?

**Comment by kvasukib** [comment]
Closing this issue as we don't have the adequate information.
