### ISSUE TITLE
About S3transferutility

### ISSUE THREAD

**Issue by tkdals1119** [awslabs/aws-sdk-android-samples#108]
I wrote my **pool Id** and **my bucket** name in Constants.java.

But it doesn't work.

Should I wrote

observer = transferUtility.upload(
        "bucketname",
        "entityname",
        file

this?

please tell me what should I do..

**Comment by karthiksaligrama** [comment]
Did you follow the [ReadMe](https://github.com/awslabs/aws-sdk-android-samples/blob/master/S3TransferUtilitySample/README.md)?

**Comment by tkdals1119** [comment]
@karthiksaligrama 
Thank you for your response!

Yes. I already read Readme and followed all steps.
(wrote my Pool ID and my bucket name..)
And when I running the app, that text is IN_PROGRESS become FAILED.
But the percentage is become 100%.
Also the image is not uploaded......
I don't know why it is not working..
![wrong](https://cloud.githubusercontent.com/assets/25217368/23693587/7b21c66a-0418-11e7-83b8-dedbe62e51bd.jpg)

**Comment by rohandubal** [comment]
Hi, could you please paste your logs so that we could help you debug the issue?

Thanks,
Rohan

**Comment by tkdals1119** [comment]
@rohandubal 
Thank you for your response!

When I click the 'Upload an Image' button,
there were no tag message.. but the other error was made.
![kakaotalk_20170311_010955901](https://cloud.githubusercontent.com/assets/25217368/23802969/5e8bdec8-05f8-11e7-82f5-6ce10ee7aa78.png)



and should I add some code here?
![kakaotalk_20170311_011713360](https://cloud.githubusercontent.com/assets/25217368/23803032/9349f708-05f8-11e7-92b8-d59cd261bbcb.png)

I really want to know why it is not working..

**Comment by rohandubal** [comment]
Hello, I am unable to find any error logs in the screen shots above. Do you have the correct permissions to read the file? Can you paste the error logs which you get the when the file upload is cancelled?

Thanks,
Rohan

**Comment by tkdals1119** [comment]
@rohandubal 
I really appreciate your response.

Here is the error screen.
![error](https://cloud.githubusercontent.com/assets/25217368/23820349/ac928c96-0659-11e7-935b-12215bf8bd84.png)

Can you give me some solution..?

**Comment by rohandubal** [comment]
Hello @tkdals1119 

We have identified the issue and you are right, its a bug related to the bucket region. As a fix, you need to add the following line:

`sS3Client.setRegion(Region.getRegion(Regions.AP_NORTHEAST_2));`

On line #73 in Util.java of the sample app. We will update once we have a fixed app in the repo.

Thanks,
Rohan

**Comment by karthiksaligrama** [comment]
fixed with 2.4.0
