### ISSUE TITLE
Pause and Cancel Works Like As Same In Upload

### ISSUE THREAD

**Issue by ananth10** [awslabs/aws-sdk-android-samples#109]
When i press pause while uploading video and resume it . it again start from beginning. not from the paused percentage. can anyone tell me why?

**Comment by karthiksaligrama** [comment]
Depending on the size of your file the TransferUtility will upload the file in multiple or single part (>5MB = multipart uploads). When the transfer is paused then the if the request is halfway through a part then the sdk will throw that part away and restart the part. 
SO if your file is small enough (< 5 MB) then its likely that when you pause and restart a transfer then it would restart the upload from 0%.

Hope this helps.

**Comment by ananth10** [comment]
@karthiksaligrama . Thank you.
