### ISSUE TITLE
Uploading is not completed if i exit from the app or killed from task manager. How to resolve this?

### ISSUE THREAD

**Issue by ananth10** [awslabs/aws-sdk-android-samples#110]

**Comment by karthiksaligrama** [comment]
can you give you more context?

**Comment by ananth10** [comment]
My file size  is 30 mb . when i start to upload the file. its uploading well. but i do not like to stay on the same page. so when i exit from the app . uploading continue , but when i remove app from taskmanager uploading gettting stopped.

**Comment by ananth10** [comment]
Will upload continue even after app killed?

**Comment by karthiksaligrama** [comment]
No the upload will not continue if you kill the process.

**Comment by ananth10** [comment]
oh. okay. is there a way to continue if app killed? . mean can i do any changes on aws sdk code?

**Comment by rohandubal** [comment]
Hello @ananth10 

If the app is killed, you can start the uploads/ downloads once the app is restarted and you can give the API call. There is no way to resume uploads/ downloads if the process is killed.

Thanks,
Rohan

**Comment by ananth10** [comment]
@rohandubal  .. Okay. Thank you.
