### ISSUE TITLE
E/MediaPlayer: Unable to create media player

### ISSUE THREAD

**Issue by anirudhbagri** [awslabs/aws-sdk-android-samples#111]
In the LEX sample..getting this error when pressing the MIC and waiting for response.
can any1 please help?

**Comment by karthiksaligrama** [comment]
can you paste your stacktrace here?

**Comment by anirudhbagri** [comment]
I figured it out...and it's working now.
although I have doubt now, Is there any way I can add list of items in the SLOT type in lex console instead of adding it manually for each item.
I have a huge list of item which comes under (lets say) "Product" category..So I want all item in the list to be added in custom slot category.

**Comment by rohandubal** [comment]
Hello @anirudhbagri 

Can you please take a look at the Lex console dev guide?  That should help.

Thanks,
Rohan
