### ISSUE TITLE
When is "dialogReadyForFulfillment" method called? 

### ISSUE THREAD

**Issue by anirudhbagri** [awslabs/aws-sdk-android-samples#112]
In Lex sample:-

When is the "dialofReadyForFulfillment()" function called?
In my lex console fulfillment is done by "return parameter to client".
I want to use these parameter in my app and do not expect any response.
How to use the parameters returned by lex bot in app? 

the response which I get from lex bot is like "{Solt:value}"

How and from which function can I get to access this result?

**Comment by karthiksaligrama** [comment]
there was a bug in the code that prevented ready for fullfilment to be called and has been fixed in 2.4.0. Please update the sdk to 2.4.0 and  give this a try
