### ISSUE TITLE
Uploading a directory from android device

### ISSUE THREAD

**Issue by shubhamgupta2901** [awslabs/aws-sdk-android-samples#114]
I have a usecase where I need to upload a complete directory to AWS bucket from the android devices.
I am using TransferUtility's  upload(String bucket, String key, File file) method. However I am getting following error.
Unable to calculate MD5 hash: /storage/emulated/0/S3TestFolder/Issues/ID_abcd1234 (Is a directory).

I am looking for something like deprecated TransferManager's uploadDirectory() and downloadDirectory(). Please help.

**Comment by mlshon** [comment]
uploadDirectory() isn't available with TransferUtility. We will take this as a feature request!

In the meanwhile, you could get the list of files in the directory and upload each file.

**Comment by muellerfr** [comment]
This feature request is being tracked using https://github.com/aws/aws-sdk-android/issues/505. Closing this issue.
