### ISSUE TITLE
org.json.JSONException: No value for appsig

### ISSUE THREAD

**Issue by vickey58** [awslabs/aws-sdk-android-samples#116]
Hi , 
I am trying to run the CognitoSyncDemo. 
I did the configuration for Login with Amazon, and created the API key and copied it to api_key.txt file.

While running the app I am geeting the below exception

org.json.JSONException: No value for **appsig**

When I debug I found the below  header and payload 

{"alg":"RSA-SHA256","ver":"1"}
{"ver":"3","endpoints":{"authz":"https:\/\/www.amazon.com\/ap\/oa","tokenExchange":"https:\/\/api.amazon.com\/auth\/o2\/token"},"clientId":"amzn1.application-oa2-client.051409f6247d44efae07c11f274c9437","appFamilyId":"amzn1.application.XXX","iss":"Amazon","type":"APIKey","pkg":"com.amazonaws.cognito.sync.demo","appVariantId":"amzn1.application-client.XXX","trustPool":null,"**appsigSha256**":"XXX","appId":"amzn1.application-client.XXX","id":"XXX","iat":"XXX"} 

looks like the payload is not having **appsig** key it instead it have **appsigSha256**.

Could anyone help me to resolve this?

Thanks
-Vickey

**Comment by karthiksaligrama** [comment]
this does not look like an aws sdk issue. I would recommend reaching out here http://login.amazon.com/support
