### ISSUE TITLE
Change layout

### ISSUE THREAD

**Issue by anirudhbagri** [awslabs/aws-sdk-android-samples#117]
In the Lex sample:

I converted the MIC background to transparent but when I send the audio and it is waiting for a response, the background automatically set back to white and after I get a response it again becomes transparent.
Is this because of a bug or do I have to change some parameters?

**Comment by karthiksaligrama** [comment]
in your layout you can use something like and change the background color

```
<com.amazonaws.mobileconnectors.lex.interactionkit.ui.InteractiveVoiceView
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="108dp"
    android:layout_height="108dp"
    android:layout_centerInParent="true"
    android:background="@android:color/white">
</com.amazonaws.mobileconnectors.lex.interactionkit.ui.InteractiveVoiceView>
```

**Comment by karthiksaligrama** [comment]
on second thought you should be able to do this directly from code as well. Will investigate

**Comment by anirudhbagri** [comment]
Well, that worked.
Now I can change the background and other things. But still there is another problem.
When It is waiting for response..the background again changes back to white.
How do I make the background change permanent?

**Comment by anirudhbagri** [comment]
How do I find my SDK version?

**Comment by karthiksaligrama** [comment]
verion is mentioned [here](https://github.com/awslabs/aws-sdk-android-samples/blob/master/LexSample/app/build.gradle#L32).

**Comment by minbi** [comment]
Re-open if there still problems
