### ISSUE TITLE
Linter warning in TransferUtility example for leak

### ISSUE THREAD

**Issue by snkashis** [awslabs/aws-sdk-android-samples#118]
Comes from https://github.com/awslabs/aws-sdk-android-samples/blob/master/S3TransferUtilitySample/src/com/amazonaws/demo/s3transferutility/Util.java#L43

"Do not place Android context classes in static fields (static reference to TransferUtility which has field appContext pointing to Context); this is a memory leak (and also breaks Instant Run)"

Android Studio 2.3, `buildToolsVersion '25.0.0'`, `com.android.tools.build:gradle:2.3`

**Comment by minbi** [comment]
Fixed with commit https://github.com/awslabs/aws-sdk-android-samples/commit/8e84504f364c9cee339f702fbea8ca314a567990
