### ISSUE TITLE
Regions Setting

### ISSUE THREAD

**Issue by wangshaolei** [awslabs/aws-sdk-android-samples#120]
```java
compile 'com.amazonaws:aws-android-sdk-s3:2.2.+'
private CognitoCachingCredentialsProvider getCredProvider(Context context) {
        if (sCredProvider == null) {
            sCredProvider = new CognitoCachingCredentialsProvider(context, COGNITO_POOL_ID, Regions.GovCloud);
        }
        return sCredProvider;
    }
```
Android sdk, why Regions Enum no "ca-central-1",And iOS S3TransferManager Region "ca-centeral-1"
bucket regions is Canada.

thanks~

**Comment by karthiksaligrama** [comment]
Please update your sdk to https://github.com/aws/aws-sdk-android/blob/master/CHANGELOG.md#release-236-12072016 CA central 1 was added in version 2.3.6
