### ISSUE TITLE
aws pubsub sample not working.

### ISSUE THREAD

**Issue by SungHyeon** [awslabs/aws-sdk-android-samples#121]
I created a keystore and placed it in "/data/user/0/com.amazonaws.demo.androidpubsub/files/demo.keystore".

However, PubSubActivity occurs when the file does not exist.

That's why it's still disconnected.

My app environment is marshmallow 6.x.

Ask for help.

![a](https://cloud.githubusercontent.com/assets/11917328/24602757/3af49dac-1899-11e7-9130-92ef7000fbee.png)
![b](https://cloud.githubusercontent.com/assets/11917328/24602761/3e0f3e2a-1899-11e7-8aa0-d54ad11ff0a8.png)

**Comment by bxpan** [comment]
The keystore name seems to be hardcoded in the sample. 
Could you try 
- renaming your keystore file to "iot_keystore" ? 
or
- replace the name in the pubsubactivity to "demo.keystore" 

Also, please change the password of your private key accordingly

**Comment by kvasukib** [comment]
Closing the issue. Please open a new issue if the issue persists.
