### ISSUE TITLE
What is customer specific end point described in android pubsub sample?

### ISSUE THREAD

**Issue by RnD-Qrio** [awslabs/aws-sdk-android-samples#122]
I want to publish a message to an AWS IoT thing from an android app as in the android pubsub example. I didn't understand  CUSTOMER_SPECIFIC_ENDPOINT parameter in PubSubActivity.java. Please explain what value should I use for this parameter?

**Comment by bxpan** [comment]
Hi RnD-Qrio,

The customer endpoint is in your AWS IoT console, You may find it in the "setting" tab, it is in the format of :  *****.iot.<region>.amazonaws.com

Thanks.

**Comment by shibinvadayatt** [comment]
It is different for each user. So we can't tell what is your's. Login to yours AWS IoT console click on Settings from left bottom. It will show your endpoint.
