### ISSUE TITLE
List of files available to download is not seen. Upload also fails.

### ISSUE THREAD

**Issue by sprajwala** [awslabs/aws-sdk-android-samples#123]
I tried to run the sample app by changing all the constants in the Constants.java file. The app builds and runs on the device but I do not see any listing when I select the "Manage Downloads" button. 
If someone could tell me what might be wrong that would be great as I am new to android programming.
Thanks.

**Comment by rohandubal** [comment]
Hello @sprajwala 

Could you upload files into your bucket first and then try downloading them?

Thanks,
Rohan

**Comment by sprajwala** [comment]
Hi @rohandubal
I have uploaded files already in my bucket. My requirement is to only download through android app.
