### ISSUE TITLE
D/CognitoCachingCredentialsProvider: No valid credentials found in SharedPreferences

### ISSUE THREAD

**Issue by sprajwala** [awslabs/aws-sdk-android-samples#124]
Hi,
I am getting the following message on the debugger while running the s3TransferUtilityApp:
D/CognitoCachingCredentialsProvider: No valid credentials found in SharedPreferences
and the "Manage Downloads" activity does not show any files to download.

Any idea what the message means? What am I doing wrong? Please help, this feature is very important for my project!
Note that i have created a bucket which contains files already (images and pdfs). I even changed the region from us-west-2 to us-east-1. I still get the same message.
Would really appreciate any help.

Thanks!

**Comment by rohandubal** [comment]
Which region is your bucket in? Are you using a Cognito Identity Pool for accessing the contents of bucket? You need to set Cognito Identity Pool ID and Pool region along with the correct bucket region. You also need a valid policy  to access contents of bucket.

**Comment by sprajwala** [comment]
Hi,
Yes I have all of that set up. Turns out I had some access permissions set up on my bucket and hence the application was not able to get the credentials. So I created a new bucket with no extra access permissions and it worked for me. Thanks for your help though, and thank you for the sample application code as well!
