### ISSUE TITLE
File upload doesn't resume on reconnection(WiFi on/off)

### ISSUE THREAD

**Issue by abhishektiwari120392** [awslabs/aws-sdk-android-samples#125]
Below is the stacktrace for 3 files uploading process. Whenever we turn off the wifi the status changes to WAITING_FOR_NETWORK and after that immediately changes to FAILED. After we turn on the wifi it doesn't resume FAILED uploads.

05-02 12:24:28.232 5589-5589/ D/TAG: OnStatusChanged:483,IN_PROGRESS
05-02 12:24:28.286 5589-5589/ D/TAG: OnStatusChanged:484,IN_PROGRESS
05-02 12:24:28.349 5589-5589/ D/TAG: OnStatusChanged:485,IN_PROGRESS
05-02 12:24:33.722 5589-5589/ D/TAG: OnStatusChanged:485,PAUSED
05-02 12:24:33.768 5589-5589/ D/TAG: OnStatusChanged:484,WAITING_FOR_NETWORK
05-02 12:24:33.920 5589-5589/ D/TAG: OnStatusChanged:484,FAILED
05-02 12:24:33.938 5589-5589/ D/TAG: OnStatusChanged:485,WAITING_FOR_NETWORK
05-02 12:24:33.970 5589-5589/ D/TAG: OnStatusChanged:483,PAUSED
05-02 12:24:33.991 5589-5589/ D/TAG: OnStatusChanged:483,WAITING_FOR_NETWORK
05-02 12:24:34.030 5589-5589/ D/TAG: OnStatusChanged:483,WAITING_FOR_NETWORK
05-02 12:24:34.082 5589-5589/ D/TAG: OnStatusChanged:485,FAILED
05-02 12:24:34.104 5589-5589/ D/TAG: OnStatusChanged:483,FAILED

**Comment by kvasukib** [comment]
Hi @abhishektiwari120392,

We have fixed this issue in the AWS Android SDK 2.4.3. Can you try upgrading and check if you are still facing this issue?
