### ISSUE TITLE
App crash after close it and start it again

### ISSUE THREAD

**Issue by rogercastaneda** [awslabs/aws-sdk-android-samples#126]
hi guys, the app doesn't work after restart the emulator or close the app.

I only configured my FB app settings and AWS Cognito IDENTITY_POOL_ID. 

Steps to reproduce it:
- I tap the facebook button, login with success, the button hides.
- I close the app or restart the emulator
- I start the app again or try to launch it from Android Studio
- I get the attached error messages:
   -  The first popup says: CognitoSyncDemo has stopped with a button saying "Open app again"
   - The second popup after says: "CognitoSyncDemo keeps stopping"

<img width="448" alt="1 cognitosyncdemo has stopped" src="https://cloud.githubusercontent.com/assets/622658/25730997/b804ad24-3107-11e7-9876-67e9124e734b.png">
<img width="442" alt="2 cognitosyncdemo keeps stopping" src="https://cloud.githubusercontent.com/assets/622658/25730998/b8052588-3107-11e7-92dc-65d4f76d7b74.png">

**Comment by JonathonTindale** [comment]
You can get around this issue by moving
`if (fbAccessToken != null) {
            setFacebookSession(fbAccessToken);
            btnLoginFacebook.setVisibility(View.GONE);
        }`
from MainActivity further back in OnCreate, the CognitoSyncClientManager needs to be initialised first.
