### ISSUE TITLE
Sample with mqtt service in android for running in background

### ISSUE THREAD

**Issue by SanyasiraoM** [awslabs/aws-sdk-android-samples#130]
https://eclipse.org/paho/clients/android/

Can you guys write a sample similar eclipse paho android service?

**Comment by bxpan** [comment]
Hi SanyasiraoM,

Could you elaborate on your use case ?

Thanks.

**Comment by SanyasiraoM** [comment]
Hi @bxpan ! We would like to use this sdk for real time chat purpose, for that we should be connected to mqtt server all the time to get messages though user closes the app. So service is useful in this scenario.

https://github.com/eclipse/paho.mqtt.android ,There paho team wrote a service in sample, but they have their own java models for MqttConnection, MqttClient . I'm unable to use them while using aws iot sdk. As in aws sample has it's own Connection and Client.

So can you guys write a service or edit the paho service and keep in your samples?

Thank you!

**Comment by bxpan** [comment]
Hi SanyasiraoM,

We will look into the option of using service in the future releases. However, making the client connected to the server all the time requires periodic pings being sent out to the server. This has significant impact on battery life so we need to assess this option carefully before implement it. 

Thanks.

**Comment by SanyasiraoM** [comment]
@bxpan Thank you

**Comment by drwjf** [comment]
@bxpan @SanyasiraoM  Thanks for your discuss about the case.

We would like to use this sdk for real time notification too. What is the newest state about this feature request?

**Comment by muellerfr** [comment]
This issue has been closed because of inactivity. Please open a new issue in https://github.com/aws/aws-sdk-android/issues if you are still encountering problems.
