### ISSUE TITLE
AWS IoT Android application over MQTT throws MqttException (0) - java.io.IOException: Already connected

### ISSUE THREAD

**Issue by shibinvadayatt** [awslabs/aws-sdk-android-samples#131]
I am trying to use 'Authenticate using Cognito-Identity with Cognito user pool' in my Android application. My Cognito user pool authentication works well when I run that seperately and I had seen a getJWTToken as well and When I run the the 'PubSub' sample application with Unauthenticated role as, it worked as expected When I integrate these two features to one application, the application threw following error.

    W/System.err: MqttException (0) - java.io.IOException: Already connected
    W/System.err:     at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:38)
    W/System.err:     at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:664)
    W/System.err:     at java.lang.Thread.run(Thread.java:761)
    W/System.err: Caused by: java.io.IOException: Already connected
    W/System.err:     at java.io.PipedOutputStream.connect(PipedOutputStream.java:100)
    W/System.err:     at java.io.PipedInputStream.connect(PipedInputStream.java:195)
    W/System.err:     at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketReceiver.<init (WebSocketReceiver.java:42)
    W/System.err:     at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketSecureNetworkModule.start(WebSocketSecureNetworkModule.java:78)
    W/System.err:     at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:650)
    W/System.err:   ... 1 more
I have been trying to resolve this issue since last Thursday and still stuck at the same place. Really No idea where should i check.!
I am adding my Authentication(Cognito user pool authentication) activity and Connect activity.

    `AmazonCognitoIdentityProviderClient identityProviderClient = new AmazonCognitoIdentityProviderClient(new AnonymousAWSCredentials(), new ClientConfiguration());
    identityProviderClient.setRegion(Region.getRegion(Regions.US_WEST_2));
    CognitoUserPool userPool = new CognitoUserPool(getApplicationContext(), "us-west-2_ghtcc6ho9", "4t0mk45hNso69dp2j4jvel5ghm", "1jmq0lhhq721oif9k6nug31c29i760vihua8hvrgu5umfr2a1vd7", identityProviderClient);
    cogUser = userPool.getUser();
    authenticationHandler = new AuthenticationHandler() {
        @Override
        public void onSuccess(CognitoUserSession userSession, CognitoDevice newDevice) {
            String ids = userSession.getIdToken().getJWTToken();
            Log.d("MyToken","session id___"+userSession.getIdToken().getExpiration()+"___"+userSession.getIdToken().getIssuedAt());
            Intent pubSub = new Intent(MainActivity.this, PubSubActivity.class);
            pubSub.putExtra("token",""+ids);
            startActivity(pubSub);
            //MainActivity.this.finish();
        }
        @Override
        public void getAuthenticationDetails(AuthenticationContinuation authenticationContinuation, String userId) {
            Log.d("MyToken","getAuthenticationDetails");
            AuthenticationDetails authenticationDetails = new AuthenticationDetails("shone", "172737", null);
            authenticationContinuation.setAuthenticationDetails(authenticationDetails);
            // Allow the sign-in to continue
            authenticationContinuation.continueTask();
        }
        @Override
        public void getMFACode(MultiFactorAuthenticationContinuation multiFactorAuthenticationContinuation) {
            Log.d("MyToken","getMFACode");
            multiFactorAuthenticationContinuation.continueTask();
        }
        @Override
        public void authenticationChallenge(ChallengeContinuation continuation) {
            Log.d("MyToken","authenticationChallenge"+continuation.getChallengeName());
            newPasswordContinuation.continueTask();
        }
        @Override
        public void onFailure(Exception exception) {
            exception.printStackTrace();
            Log.d("MyToken","onFailure");
        }
    };
     `cogUser.getSessionInBackground(authenticationHandler);`

When It reaches 'OnSuccess' I am launching my connect activity and passing my session token along with the Intent. Moving to the next activity

    private static final String COGNITO_POOL_ID = "us-west-2:a153a090-508c-44c0-a9dd-efd450298c4b";
    private static final Regions MY_REGION = Regions.US_WEST_2;
    AWSIotMqttManager mqttManager;
    String clientId;
    AWSCredentials awsCredentials;
    CognitoCachingCredentialsProvider credentialsProvider;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        Intent intent = getIntent();
        if(null == intent){
           Toast.makeText(getApplicationContext(), "Token is null", Toast.LENGTH_SHORT).show();
        }else {
           token = intent.getStringExtra("token");
        }
        clientId = UUID.randomUUID().toString();
    credentialsProvider = new CognitoCachingCredentialsProvider(
            getApplicationContext(), 
            COGNITO_POOL_ID, 
            MY_REGION 
    );
    mqttManager = new AWSIotMqttManager(clientId, CUSTOMER_SPECIFIC_ENDPOINT);
     Map loginsMap = new HashMap();
     loginsMap.put("cognito-idp.us-west-2.amazonaws.com/us-west-2_ghtcc6ho9", token);
    credentialsProvider.setLogins(loginsMap);
    Log.d("SESSION_ID", ""+token);
    new Thread(new Runnable() {
        @Override
        public void run() {
            credentialsProvider.refresh();
            awsCredentials = credentialsProvider.getCredentials();
            Log.d("SESSION_ID B: ", ""+awsCredentials.getAWSAccessKeyId());
            Log.d("SESSION_ID C: ", ""+awsCredentials.getAWSSecretKey());
        }
    }).start();
    }
    View.OnClickListener connectClick = new View.OnClickListener() {
    @Override
    public void onClick(View v) {

        Log.d(LOG_TAG, "clientId = " + clientId);

        try {
            mqttManager.connect(credentialsProvider, new AWSIotMqttClientStatusCallback() {
                @Override
                public void onStatusChanged(final AWSIotMqttClientStatus status,
                        final Throwable throwable) {
                    Log.d(LOG_TAG, "Status = " + String.valueOf(status)+"______"+((null !=throwable)?throwable.getMessage():""));

                    runOnUiThread(new Runnable() {
                        @Override
                        public void run() {
                            if (status == AWSIotMqttClientStatus.Connecting) {
                                tvStatus.setText("Connecting...");

                            } else if (status == AWSIotMqttClientStatus.Connected) {
                                tvStatus.setText("Connected");

                            } else if (status == AWSIotMqttClientStatus.Reconnecting) {
                                if (throwable != null) {
                                    Log.e(LOG_TAG, "Connection error.", throwable);
                                }
                                tvStatus.setText("Reconnecting");
                            } else if (status == AWSIotMqttClientStatus.ConnectionLost) {
                                if (throwable != null) {
                                    Log.e(LOG_TAG, "Connection error.", throwable);
                                    throwable.printStackTrace();
                                }
                                tvStatus.setText("Disconnected");
                            } else {
                                tvStatus.setText("Disconnected");

                            }
                        }
                    });
                }
            });
        } catch (final Exception e) {
            Log.e(LOG_TAG, "Connection error.", e);
        }
    }
    };
 Why it throws exception when the MQTT connect is being invoked? Any help would be appreciated.

https://stackoverflow.com/questions/44244375/aws-iot-android-application-over-mqtt-throws-mqttexception-0-java-io-ioexcep

**Comment by bxpan** [comment]
Hi shibinvadayatt,

Would you please clarify which 2 features are you trying to integrate ? Where in your code did the exception throw? 

Thanks.

**Comment by shibinvadayatt** [comment]
Hi brother,
I hope you have gone through the my issue. I am writing an application for my IoT application. The Amazon AWS IoT portal is being used in the application to support IoT part. I had two requirements. 1st is the user authentication which I did with the help of Amazon Cognito Identity provider SDK. After authentication the SDK gives a session token. Till session token reception is done in the first activity. You can check the first portion to know more about this. Once I receive a token, I will launch another activity and the token received will be send through the intent to the new activity. 
The second activity is designed to communicate with the AWS IoT portal. To connect MQTT client, I need to use the token received from the previous activity. I am trying to establish the connection with the help of Cognito. When try connecting it, throws the exception. Hope you are clear.

Thanks,
Francis Shibin

**Comment by shibinvadayatt** [comment]
Adding my cloud watch console. It connects twice and second one fails. I found EOFException somewhere also
2017-06-02 19:26:22.921 TRACEID:ce0e995f-7858-c6aa-e2ab-03d6a13317be PRINCIPALID:854510022280/AROAISSJBDLZWLKHMH4UA:CognitoIdentityCredentials/AROAISSJBDLZWLKHMH4UA:CognitoIdentityCredentials [INFO] EVENT:MQTT Client Connect MESSAGE:Connect Status: AUTHORIZATION_ERROR
2017-06-02 19:26:22.921 TRACEID:ce0e995f-7858-c6aa-e2ab-03d6a13317be PRINCIPALID:854510022280/AROAISSJBDLZWLKHMH4UA:CognitoIdentityCredentials/AROAISSJBDLZWLKHMH4UA:CognitoIdentityCredentials [INFO] EVENT:MQTT Client Connect MESSAGE: IpAddress: 106.201.105.61 SourcePort: 18900

**Comment by bxpan** [comment]
@shibinvadayatt Are you still seeing the same issue?

**Comment by kvasukib** [comment]
@NickLink Sorry to hear this. We will update our documentation to reflect the required information of retrieving the token and federating with the Cognito and using the credentials provider with IoT.

**Comment by gdingenen** [comment]
@kvasukib , where can I find the updated documentation on using IoT with Cognito?

**Comment by kvasukib** [comment]
Hi @gdingenen, Thank you for reporting to us. We are still working on it. Can you point out the specific questions you have using IoT with Cognito? Are you trying to add Cognito UserPools SignIn or Cognito Identities only?

**Comment by gdingenen** [comment]
I was trying to cobine AWS IoT MQTT with AWS Cognito. I got it working by attaching the policy.

**Comment by mpanicker** [comment]
I am getting same error but with java. Still cant solve it. I am running the PublishSubscribeSample.java from https://github.com/aws/aws-iot-device-sdk-java
This line gives me error awsIotClient.connect(); 

MqttException (0) - java.io.IOException: Already connected
	at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:38)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:664)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Already connected
	at java.io.PipedOutputStream.connect(PipedOutputStream.java:100)

**Comment by muellerfr** [comment]
We released updated documentation IoT that can be viewed here: 
https://aws-amplify.github.io/docs/android/pubsub

If you have any questions about how to use IoT please file an issue [here](https://github.com/aws-amplify/aws-sdk-android/issues).
