### ISSUE TITLE
Multiple parallel downloads using TransferUtility hanging UI thread

### ISSUE THREAD

**Issue by sriram-kakarala** [awslabs/aws-sdk-android-samples#136]
Hi We are using the latest version of Android SDK ie 2.4.4 and are downloading about 20 files.

We see that the max concurrent downloads can be 5 which internal can use max number of HTTP connections which we leave it to the default ie 10.
With this setup the UI thread hangs up completely. If I reduce the number of connections to 3 then it is a little better, but overall the app becomes unresponsive. I could not find a way to reduce overall thread count but I suspect it is the number of connections causing this.
Our block of code is quite simple as shown in Demo, that is use transfer utility to create a download and attach an observer.
We use Cognito Authentication and that part works as expected.

**Comment by sriram-kakarala** [comment]
I see the following warning in the Console,
W/art: Long monitor contention event with owner method=int com.amazonaws.mobileconnectors.s3.transferutility.TransferDBBase.update(android.net.Uri, android.content.ContentValues, java.lang.String, java.lang.String[]) from TransferDBBase.java:181 waiters=0 for 288ms

**Comment by Vieufoux** [comment]
Hi @kvasukib i also have the same problem.

My version is:     
compile 'com.amazonaws:aws-android-sdk-s3:2.6.+'

Here is my console:
12-04 14:07:04.515 28325 31431 W art     : Long monitor contention event with owner method=int com.amazonaws.mobileconnectors.s3.transferutility.TransferDBBase.update(android.net.Uri, android.content.ContentValues, java.lang.String, java.lang.String[]) from TransferDBBase.java:181 waiters=0 for 382ms

**Comment by kvasukib** [comment]
Hi @sriram-kakarala, Approximately how many transfers are present in the database? Are there any transfers that are long-running (probably more than 50 minutes?)

**Comment by kvasukib** [comment]
Hi @sriram-kakarala, Sorry for the delayed reply. We released 2.6.16 with enhancements for stability in TransferUtility. Now you have a flag to customize the size of the thread pool for the transfers. We have documented it here: https://docs.aws.amazon.com/aws-mobile/latest/developerguide/how-to-transfer-files-with-transfer-utility.html#native-transfer-utility-options Please let us know if this works for you.
