### ISSUE TITLE
cognitosyncdemo error

### ISSUE THREAD

**Issue by ubaidsayyed54** [awslabs/aws-sdk-android-samples#137]
Can anyone help me out to resolve this bug while building cognitio sync demo sample in Android Studio.I am a noob in Android studio

Gradle sync finished with 1 error 

Error:Execution failed for task ':processDebugManifest'.
> Manifest merger failed : Attribute activity#com.facebook.FacebookActivity@theme value=(@android:style/Theme.Translucent.NoTitleBar) from AndroidManifest.xml:43:13-72
	is also present at [com.facebook.android:facebook-android-sdk:4.24.0] AndroidManifest.xml:32:13-63 value=(@style/com_facebook_activity_theme).
	Suggestion: add 'tools:replace="android:theme"' to <activity> element at AndroidManifest.xml:40:9-44:48 to override.

**Comment by minbi** [comment]
Did you try the suggestion?

```
Suggestion: add 'tools:replace="android:theme"' to element at AndroidManifest.xml:40:9-44:48 to override.
```

**Comment by ubaidsayyed54** [comment]
Issue solved :+1:
