### ISSUE TITLE
AndroidPubSubWebSocket can't publish and subscribe topic

### ISSUE THREAD

**Issue by oceantear** [awslabs/aws-sdk-android-samples#138]
I am new for AWS IOT. I tried to build an Android  project (AndroidPubSubWebSocket) on my tablet.
Following doc (https://github.com/awslabs/aws-sdk-android-samples/blob/master/AndroidPubSubWebSocket/README.md) , it can connect to my thing(use unauthenticated identities). But, I can't get any message from MQTT client when I send message from my tablet. 
When I clicked **SUBSCRIBLE**, the status change to Connecting -> Connected -> Connecting -> Connected......(looping). And nothing something shown in Last message.
Below is my Policy

<pre>{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "iot:Connect"
            ],
            "Resource": [
                "*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "iot:Publish"
            ],
            "Resource": [
                "arn:aws:iot:us-east-1:471565932063:topic/mytopic/mysubtopic"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "iot:Subscribe",
                "iot:Receive"
            ],
            "Resource": [
                "arn:aws:iot:us-east-1:471565932063:topic/mytopic/mysubtopic"
            ]
        }
    ]
}
</pre>
Is any setting I miss?

**Comment by fengsongAWS** [comment]
You only allow to pub/sub/receive messages from mytopic/mysubtopic. Is that you want? 
You can try setting your resources to be "*" and this will allow your client to be able to perform on any resources without limit. Then, if you want, you can add more restrict on your policies.

Thanks,
Fengyi

**Comment by oceantear** [comment]
Thanks for your suggestion. After I follow the doc again , it works!!
I can use app to send message and received the message from MTQQ client.
