### ISSUE TITLE
please help to solve manifest error.

### ISSUE THREAD

**Issue by minaz-tank** [awslabs/aws-sdk-android-samples#141]
In CognitoSyncDemo,
Error occured in menifest file.

Error:Execution failed for task ':processDebugManifest'.
> Manifest merger failed : Attribute activity#com.facebook.FacebookActivity@theme value=(@android:style/Theme.Translucent.NoTitleBar) from AndroidManifest.xml:43:13-72
  	is also present at [com.facebook.android:facebook-android-sdk:4.24.0] AndroidManifest.xml:32:13-63 value=(@style/com_facebook_activity_theme).
  	Suggestion: add 'tools:replace="android:theme"' to <activity> element at AndroidManifest.xml:40:9-44:48 to override.

**Comment by minbi** [comment]
Hi @minaz-tank ,

I have updated the sample. Can you see if it works for you now? :)

**Comment by minaz-tank** [comment]
Thanks @minbi ,
It works.
