### ISSUE TITLE
Can anyone solve this gradle exception?

### ISSUE THREAD

**Issue by minaz-tank** [awslabs/aws-sdk-android-samples#142]
Hi,
M trying to run AmazonCognitoAuthDemo, but there is gradle which can not be build. 

code:
 compile(name:'aws-android-sdk-cognitoauth-2.4.4', ext:'aar')

Error:
Failed to resolve: :aws-android-sdk-cognitoauth-2.4.4:

**Comment by kredden** [comment]
Hi,

The gradle line for that is already in the samples build.gradle file (aws-sdk-android-samples-master/AmazonCognitoAuthDemo/app/build.gradle) although I just noticed a missing quote at the end that we will get fixed.

It should be:
compile 'com.amazonaws:aws-android-sdk-cognitoauth:2.4.4@aar'

In the gradle file the quote at the end is missing.

Kevin

**Comment by kredden** [comment]
Did this get you past your issue?

Kevin

**Comment by minbi** [comment]
Feel free to re-open this issue if this is not solved
