### ISSUE TITLE
AWS Cognito User Pools + SAML Integration in Android

### ISSUE THREAD

**Issue by Mactores** [awslabs/aws-sdk-android-samples#143]
# **We are getting below error after user signins in Android application.**

07-31 11:47:21.344 14566-14566/com.amazonaws.cognito.android.samples.authdemo W/System.err: **com.amazonaws.mobileconnectors.cognitoauth.exceptions.AuthNavigationException: user cancelled**
07-31 11:47:21.354 14566-14566/com.amazonaws.cognito.android.samples.authdemo W/System.err:     at com.amazonaws.mobileconnectors.cognitoauth.AuthClient$4.onNavigationEvent(AuthClient.java:555)
07-31 11:47:21.354 14566-14566/com.amazonaws.cognito.android.samples.authdemo W/System.err:     at android.support.customtabs.CustomTabsClient$2$1.run(CustomTabsClient.java:197)
07-31 11:47:21.354 14566-14566/com.amazonaws.cognito.android.samples.authdemo W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
07-31 11:47:21.354 14566-14566/com.amazonaws.cognito.android.samples.authdemo W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
07-31 11:47:21.354 14566-14566/com.amazonaws.cognito.android.samples.authdemo W/System.err:     at android.os.Looper.loop(Looper.java:135)
07-31 11:47:21.354 14566-14566/com.amazonaws.cognito.android.samples.authdemo W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5237)
07-31 11:47:21.354 14566-14566/com.amazonaws.cognito.android.samples.authdemo W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
07-31 11:47:21.354 14566-14566/com.amazonaws.cognito.android.samples.authdemo W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
07-31 11:47:21.354 14566-14566/com.amazonaws.cognito.android.samples.authdemo W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
07-31 11:47:21.354 14566-14566/com.amazonaws.cognito.android.samples.authdemo W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:707)
07-31 11:47:21.374 14566-14566/com.amazonaws.cognito.android.samples.authdemo D/UnauthUserFragment: UnauthUserFragment

**Comment by kyarosh** [comment]
I encountered the same issue and, after poking around a bit, it looks like the exception is being thrown by the Android SDK itself and not just the demo. I've opened aws/aws-sdk-android#328 and updated it with my findings for tracking.

**Comment by nzhou** [comment]
Same here! kyarosh's fix worked for me.

**Comment by nzhou** [comment]
Same here!

**Comment by kvasukib** [comment]
Tracking this issue under AWS Android SDK : https://github.com/aws/aws-sdk-android/issues/328. Closing this issue.
