### ISSUE TITLE
Subscribe Multiple Topic

### ISSUE THREAD

**Issue by ravirajjak** [awslabs/aws-sdk-android-samples#144]
How to subscribe Multiple Topic ?

**Comment by kvasukib** [comment]
Hi @ravirajjak,

Thanks for reporting to us and sorry for the delayed response.

Yes, it's possible to subscribe to more than one topic. You can use the subscribe API repeatedly with different topics.

https://github.com/aws/aws-sdk-ios/blob/master/AWSIoT/AWSIoTDataManager.h#L477

Thanks

**Comment by Hemant0601** [comment]
@ravirajjak  @kvasukib is correct here. Try iterating over the array of topics you have and fire subscribe API on those.
Update the comment if it helps and mark it close too.  #happycoding

**Comment by ravirajjak** [comment]
@Hemant0601 @kvasukib  I tried subscribing repeatedly but it didn't work. But anyways I found another way of subscribing.

**Comment by Hemant0601** [comment]
Ok. Cool. You can share the approach too, might be helpful for others if its better optimised.
