### ISSUE TITLE
Internal Error - verifyAttribute

### ISSUE THREAD

**Issue by darwin-android** [awslabs/aws-sdk-android-samples#147]
I am trying to verify the phone_number attribute, for that i have called
user.getAttributeVerificationCodeInBackground("phone_number", callback);

and i am able get the verification code in my mobile.
after that i invoked the 
user.verifyAttribute("phone_number", verificationCode, callback); service then i am getting "Internal Error".

i am using  compile 'com.amazonaws:aws-android-sdk-cognitoidentityprovider:2.4.6'

**Comment by minbi** [comment]
Tracking in aws/aws-sdk-android#331
