### ISSUE TITLE
java-lang-nosuchfielderror-com-amazonaws-services-dynamodbv2-amazondynamodbclient

### ISSUE THREAD

**Issue by praducg** [awslabs/aws-sdk-android-samples#150]
Hello I tried to create sample project with the code provided .But I am facing isuse with endpoint url.
I have submitted a stackoverflow question.
https://stackoverflow.com/questions/46042288/java-lang-nosuchfielderror-com-amazonaws-services-dynamodbv2-amazondynamodbclie

**Comment by kvasukib** [comment]
Answered on StackOverflow : https://stackoverflow.com/questions/46042288/java-lang-nosuchfielderror-com-amazonaws-services-dynamodbv2-amazondynamodbclie.
Hence closing the issue.
