### ISSUE TITLE
The AmazonCognitoAuthDemo is broken when using app secret

### ISSUE THREAD

**Issue by nzhou** [awslabs/aws-sdk-android-samples#152]
Without adding app secret, it returns the error invalid_client.

It return the following error message after adding the code to set the app secret:
Unexpected char 0x0a at 82 in header value: Basic NnI2NmcwMWhza2U0NXE1N2g1ajM3YTcwNm46MXRxOXMyNTg1NWF0NXNvNG9wbjl2bXA1ODVjM2kw
a25tNDRtajc3MWt2MzB2OTlxYXQwbw

Though it seems that was caused by a binding exception, and the real error is user_cancelled. I haven't found a fix for it yet.

**Comment by kvasukib** [comment]
Hi @nzhou, 

Thanks for reporting to us. Did you setup the app client secret in strings.xml? 
What version of SDK are you using?

**Comment by nzhou** [comment]
Yes, I added the client secret in strings.xml and set it in the auth builder too. I'm using aws-android-sdk-cognitoauth:2.4.7 and Android SDK 25.
