### ISSUE TITLE
Access Issue while accessing private files from S3 Bucket - S3TransferUtilitySample

### ISSUE THREAD

**Issue by Bhargav-VIT** [awslabs/aws-sdk-android-samples#153]
Hi, I am using the sample app for S3 integration. I am using the code as is and have just added all the keys and location name as applicable. I am able to view files from the bucket. However, I am able to download only public files and not private files. For private files I am getting the following exception.

Exception -- Failed to download: 2 due to Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 5AE60C1B744E3DA7).

If I use BasicAWSCredentials(accessKey,secretKey) I am able to access the files but if I use CognitoCachingCredentialsProvide I am not getting access to private files.

**Comment by kvasukib** [comment]
Hello Bhargav,

Thanks for using our samples and reporting to us.

Have you setup the right permissions as described in README: "Set up permissions" ?

**Comment by minbi** [comment]
updated response see above

**Comment by Bhargav-VIT** [comment]
Hi kvasukib,

We are not using a bucket generated by mobile hub. We have created a bucket individually from the AWS Console.

We are trying to access the bucket via Unauth role. We are not using any login.

**Comment by Bhargav-VIT** [comment]
Hi, any updates on this ?

**Comment by minbi** [comment]
Does your unauthenticated role have the correct IAM permissions attached to access the files?

Reference http://docs.aws.amazon.com/AmazonS3/latest/dev/using-with-s3-actions.html
