### ISSUE TITLE
Where is the sqs demo of the Android SDK?

### ISSUE THREAD

**Issue by lreaderl** [awslabs/aws-sdk-android-samples#154]
I wanna use the sqs service on Android platform. Could you plz tell me that?

**Comment by minbi** [comment]
There is currently no demo for SQS. We will take this as a feature request.
Here is the API reference http://docs.aws.amazon.com/AWSAndroidSDK/latest/javadoc/com/amazonaws/services/sqs/AmazonSQSClient.html

**Comment by newchenxf** [comment]
what's the status now? @minbi  I also wanna use sqs, but hardly find a demo. please tell me if amazon has this demo.

**Comment by minbi** [comment]
We currently do not have a demo. I will update the team of your request.

**Comment by AdityaS-Cybage** [comment]
Do we have any update? Even I couldn't find any such Demo/Sample code to implement SQS for android SDK.

If anyone having the link, please share. Thanks.

**Comment by desokroshan** [comment]
@AdityaS-Cybage 
We unfortunately still do not have an android sample app for sqs. This request has already been submitted to the team for prioritization. I do not have specific timeline that I can share at this point. We will let you know, either on this thread, or through a forum announcement when the sample app for sqs is ready. 
You can however use the following to get started with using sqs for your android app. 

Add the android sdk for sqs as a dependency in your build.gradle
```
dependencies {
    implementation ("com.amazonaws:aws-android-sdk-sqs:2.7.5")
}
```

Following snippet demonstrates how to use essential features of sqs service using andoird sdk: 

```
CognitoCachingCredentialsProvider credentialsProvider;
// Initialize the AWS Cognito credentials provider
credentialsProvider = new CognitoCachingCredentialsProvider(
        getApplicationContext(), // context
        COGNITO_POOL_ID, // Identity Pool ID
        MY_REGION // Region
);

// Construct a new client to invoke service methods on AmazonSQS
AmazonSQSClient sqs = new AmazonSQSClient(credentialsProvider);

// Create a new queue
CreateQueueRequest createQueueRequest = new CreateQueueRequest("MyQueue");
String myQueueUrl = sqs.createQueue(createQueueRequest).getQueueUrl();

// List all the queues
System.out.println("Listing all queues in your account.\n");
for (String queueUrl : sqs.listQueues().getQueueUrls()) {
    Log.d("sqs_sample","QueueUrl: " + queueUrl);
}

// Send a message to the queue
Log.d("sqs_sample","Sending a message to MyQueue.");
sqs.sendMessage(new SendMessageRequest(myQueueUrl, "This is my message text."));

// Receive messages
Log.d("sqs_sample","Receiving messages from MyQueue.");
ReceiveMessageRequest receiveMessageRequest = new ReceiveMessageRequest(myQueueUrl);
List<Message> messages = sqs.receiveMessage(receiveMessageRequest).getMessages();
for (Message message : messages) {
    System.out.println("  Message");
    System.out.println("    MessageId:     " + message.getMessageId());
    System.out.println("    ReceiptHandle: " + message.getReceiptHandle());
    System.out.println("    MD5OfBody:     " + message.getMD5OfBody());
    System.out.println("    Body:          " + message.getBody());
    for (Map.Entry<String, String> entry : message.getAttributes().entrySet()) {
        System.out.println("  Attribute");
        System.out.println("    Name:  " + entry.getKey());
        System.out.println("    Value: " + entry.getValue());
    }
}

// Delete a message
Log.d("sqs_sample","Deleting a message.");
String messageReceiptHandle = messages.get(0).getReceiptHandle();
sqs.deleteMessage(new DeleteMessageRequest(myQueueUrl, messageReceiptHandle));

// Delete a queue
Log.d("sqs_sample", "Deleting the test queue.");
sqs.deleteQueue(new DeleteQueueRequest(myQueueUrl));
```
Please ensure that methods calls involving network operations such as ```sendMessage``` and ```receiveMessage``` are done on a separate thread. Let us know if you have any questions.

Best, Roshan

**Comment by muellerfr** [comment]
This issue has been closed because of inactivity. Please open a new issue in https://github.com/aws/aws-sdk-android/issues if you are still encountering problems.
