### ISSUE TITLE
IllegalArgumentException Unexpected char

### ISSUE THREAD

**Issue by rtokun** [awslabs/aws-sdk-android-samples#157]
In the AmazonCognitoAuthDemo, once trying to call Auth.getTokens() endpoint, the java.lang.IllegalArgumentException is being thrown. Looks like the reason is in AuthClient.getHttpHeader().
When header is being created the Pkce.encodeBase64 called and it adds new lines inside header which is invalid. Probably you should use Base64.encodeToString(data, Base64.NO_WRAP) instead of Base64.encodeToString(data, Base64.DEFAULT) when creating the headers.
Thanks

**Comment by kvasukib** [comment]
Hi @rtokun, This has been fixed in 2.6.13 version of the SDK. Thanks!
