### ISSUE TITLE
Recommended architecture for IoT system

### ISSUE THREAD

**Issue by Ibrahimhassan1** [awslabs/aws-sdk-android-samples#159]
I noticed that in the Temperature Controller example, two thing shadows were used one to control and one to monitor, it this the recommended architecture that should be used in all apps?

Also is it possible to get updates of current status and the desired state when changes happen using the Android SDK, should I use the PubSub sample for that?

The system consists of a number of devices running Android OS and has a number of sensors and actuators, and an Android/iOS clients should monitor the device status and issue commands to alternate actuators.

**Comment by bxpan** [comment]
Hi lbrahimhassan1, 

It depends on each use case how many thing shadows to use, there's no such recommended architecture. 

You may refer to the documentation on thing shadows here to see when messages are published on each shadow topics: http://docs.aws.amazon.com/iot/latest/developerguide/using-thing-shadows.html

Thanks.
