### ISSUE TITLE
AWS-android-iot

### ISSUE THREAD

**Issue by akskulk** [awslabs/aws-sdk-android-samples#160]
Working on an Android application with AWS-SDK-android SDK, finding difficulty in getting the list of Things from AWSIoTClient though the required data is passed. It would be helpful if a Sample app is created for displaying the Things list also.

**Comment by bxpan** [comment]
Hi akskulk,

Would you please elaborate on how you were using AWSIotClient to get things list? 

Thanks.

**Comment by Hemant0601** [comment]
@akskulk Hi, see if this is any help [https://github.com/aws/aws-iot-device-sdk-java/blob/master/aws-iot-device-sdk-java-samples/src/main/java/com/amazonaws/services/iot/client/sample/shadow/ShadowSample.java](url)

**Comment by kvasukib** [comment]
Closing this. Please open if the issue persists.
