### ISSUE TITLE
FATAL 

### ISSUE THREAD

**Issue by Krist-m** [awslabs/aws-sdk-android-samples#161]
mobileconnectors.cognitoauth.exceptions.AuthInvalidParameterException: validation failed
10-30 17:52:59.421 20117 20117 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2928)
10-30 17:52:59.421 20117 20117 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3003)
10-30 17:52:59.421 20117 20117 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
10-30 17:52:59.421 20117 20117 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1678)
10-30 17:52:59.421 20117 20117 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
10-30 17:52:59.421 20117 20117 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
10-30 17:52:59.421 20117 20117 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6876)
10-30 17:52:59.421 20117 20117 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-30 17:52:59.421 20117 20117 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
10-30 17:52:59.421 20117 20117 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1368)
10-30 17:52:59.421 20117 20117 E AndroidRuntime: Caused by: com.amazonaws.mobileconnectors.cognitoauth.exceptions.AuthInvalidParameterException: validation failed
10-30 17:52:59.421 20117 20117 E AndroidRuntime: 	at com.amazonaws.mobileconnectors.cognitoauth.Auth$Builder.validateCognitoAuthParameters(Auth.java:341)
10-30 17:52:59.421 20117 20117 E AndroidRuntime: 	at com.amazonaws.mobileconnectors.cognitoauth.Auth$Builder.build(Auth.java:288)
10-30 17:52:59.421 20117 20117 E AndroidRuntime: 	at com.amazonaws.cognito.android.samples.authdemo.MainActivity.initCognito(MainActivity.java:121)
10-30 17:52:59.421 20117 20117 E AndroidRuntime: 	at com.amazonaws.cognito.android.samples.authdemo.MainActivity.onCreate(MainActivity.java:48)
10-30 17:52:59.421 20117 20117 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7159)
10-30 17:52:59.421 20117 20117 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
10-30 17:52:59.421 20117 20117 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2881)
10-30 17:52:59.421 20117 20117 E AndroidRuntime: 	... 9 more
10-30 17:52:59.421 20117 20117 E AndroidRuntime: Caused by: com.amazonaws.mobileconnectors.cognitoauth.exceptions.AuthInvalidParameterException: {"AppCognitoWebDomain":"invalid"}
10-30 17:52:59.421 20117 20117 E AndroidRuntime: 	at com.amazonaws.mobileconnectors.cognitoauth.Auth$Builder.validateCognitoAuthParameters(Auth.java:338)

**Comment by kvasukib** [comment]
Hi @Krist-m,

Have you setup the application as described in the [README](https://github.com/awslabs/aws-sdk-android-samples/tree/master/AmazonCognitoAuthDemo) ?

**Comment by desokroshan** [comment]
@Krist-m 

This exceptions is usually caused by incorrect format of the cognito_web_domain. The cognito_web_domain resource in the [strings.xml](https://github.com/awslabs/aws-sdk-android-samples/blob/master/AmazonCognitoAuthDemo/app/src/main/res/values/strings.xml) file must be of the form __foo.auth.us-east-1.amazoncognito.com__ devoid of preceding _http://_ or _https://_. The readme is updated, detailing instructions on getting the app up and running. Please update if the the issue persists.

Thanks, Roshan

**Comment by muellerfr** [comment]
This issue has been closed because of inactivity. Please open a new issue in https://github.com/aws/aws-sdk-android/issues if you are still encountering problems.
