### ISSUE TITLE
Aws android iot with RXjava

### ISSUE THREAD

**Issue by tvhieuit** [awslabs/aws-sdk-android-samples#164]
Where can i find android aws with rxjava.

**Comment by kvasukib** [comment]
Hi @tvhieuit,

Thanks for reporting to us. Can you provide us more details on what you are trying to accomplish?
Currently, AWS Android SDK doesn't support RxJava.

**Comment by tvhieuit** [comment]
@kvasukib thanks for your reply.
I have convert to RxJava like this 
<img width="702" alt="screen shot 2017-11-28 at 14 41 20" src="https://user-images.githubusercontent.com/12293328/33307770-598b90a0-d44a-11e7-90e3-0866d25b5434.png">

**Comment by kvasukib** [comment]
Hi @tvhieuit, We do not have a sample app for IoT that works with RxJava. We will take it as a feature request. If you encounter any issues while using the Android IoT SDK, please feel free to open an issue in https://github.com/aws/aws-sdk-android.

Thanks

**Comment by tvhieuit** [comment]
okay, I know

Thank you so much.
