### ISSUE TITLE
About CognitoCachingCredentialsProvider

### ISSUE THREAD

**Issue by jason8232590** [awslabs/aws-sdk-android-samples#166]
I can  download files by using aws-sdk and using  Amazon Cognito to authenticate with AWS from our mobile application .  But what can I do when  I want to  download files by using another download library . 
I guess it may be need a token when I download it but I dont know the exactly method . So could you give me some advices or examples? Thanks !

**Comment by kvasukib** [comment]
Hi @jason8232590,

1. Create a CredentialsProvider, for example:

CognitoCachingCredentialsProvider provider = new CognitoCachingCredentialsProvider(
                    getApplicationContext(),
                    "<COGNITO_IDENTITY_POOL_ID>",
                    Regions.fromName("<COGNITO_IDENTITY_POOL_REGION>"));

2. Create a AmazonS3 Client:

AmazonS3 s3Client = new AmazonS3Client(provider);
s3Client.setRegion(Region.getRegion("<S3_REGION>"));
       
3. Use TransferUtility:

TransferUtility transferUtility = new TransferUtility(s3Client, getApplicationContext());
transferUtility.

TransferObserver observer = transferUtility.upload(
  MY_BUCKET,     /* The bucket to upload to */
  OBJECT_KEY,    /* The key for the uploaded object */
  MY_FILE        /* The file where the data to upload exists */
);

You can try out our S3 sample app here: https://github.com/awslabs/aws-sdk-android-samples/tree/master/S3TransferUtilitySample

**Comment by jason8232590** [comment]
Thanks for your relay! But the way you wrote is to  use amazon sdk to download file. But I wonder whether there is a way to allow third party library to download the file come from amazon directly @kvasukib .
