### ISSUE TITLE
Start voice dialog with bot without pushing InteractiveVoiceView button

### ISSUE THREAD

**Issue by zepelinjam** [awslabs/aws-sdk-android-samples#167]
Hi there!

I've just started using this SDK and I have 2 questions:
1. How can I start a voice conversation without pushing InteractiveVoiceView button? For example, after pushing custom button or other action.
2. Can I start a voice conversation with Lex bot via special start word? Like a "OK Google" in google search.

**Comment by minbi** [comment]
1. The button works on the underlying SDK, so you can make the same SDK calls based on your own triggers.

2. That is not currently supported by the SDK directly.
