### ISSUE TITLE
Unclear example documentation

### ISSUE THREAD

**Issue by flycast** [awslabs/aws-sdk-android-samples#168]
I am trying to follow the [AndroidPubSub](https://github.com/awslabs/aws-sdk-android-samples/tree/master/AndroidPubSub) example to the letter but it seems to me that the docs are either unclear or out of date.

First hitch is when following the docs they say:

> EnsureEnable access to unauthenticated identities is checked. This allows the sample application to assume the unauthenticated role associated with this identity pool.
> 
> Important: see note below on unauthenticated user access.

The note says:

> Note: to keep this example simple it makes use of unauthenticated users in the identity pool. This can be used for getting started and prototypes but unauthenticated users should typically only be given read-only permissions if used in production applications. More information on Cognito identity pools including the Cognito developer guide can be found here.

I cannot find the "access to unauthenticated identities" anywhere in Cognito settings. Frustrating. This makes me think something is missing or out of date.

Next the docs say:

> As part of creating the identity pool Cognito will setup two roles in Identity and Access Management (IAM). These will be named something similar to:Cognito_PoolNameAuth_Role andCognito_PoolNameUnauth_Role.

This did not happen. No roles were set up in IAM. What to do? Do I set them up manually? Do I attach them to the Identity pool? 

When I run the example using Android Studio I get:

> 11-24 11:21:29.635 16268-16274/? E/art: Failed sending reply to debugger: Broken pipe
> 11-24 11:21:30.532 16268-16306/? E/com.amazonaws.demo.androidpubsub.PubSubActivity: Exception occurred when generating new private key and certificate.
>                                                                                     com.amazonaws.AmazonServiceException: 1 validation error detected: Value 'us-east-1_XXXXXXXXX' at 'identityPoolId' failed to satisfy constraint: Member must satisfy regular expression pattern: [\w-]+:[0-9a-f-]+ (Service: AmazonCognitoIdentity; Status Code: 400; Error Code: ValidationException; Request ID: e8d9e88f-d13b-11e7-bbc5-d993303a1539)
>                                                                                         at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:712)
>                                                                                         at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:388)
>                                                                                         at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:199)
>                                                                                         at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.invoke(AmazonCognitoIdentityClient.java:558)
>                                                                                         at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.getId(AmazonCognitoIdentityClient.java:444)
>                                                                                         at com.amazonaws.auth.AWSAbstractCognitoIdentityProvider.getIdentityId(AWSAbstractCognitoIdentityProvider.java:172)
>                                                                                         at com.amazonaws.auth.AWSEnhancedCognitoIdentityProvider.refresh(AWSEnhancedCognitoIdentityProvider.java:76)
>                                                                                         at com.amazonaws.auth.CognitoCredentialsProvider.retryRefresh(CognitoCredentialsProvider.java:597)
>                                                                                         at com.amazonaws.auth.CognitoCredentialsProvider.startSession(CognitoCredentialsProvider.java:569)
>                                                                                         at com.amazonaws.auth.CognitoCredentialsProvider.getCredentials(CognitoCredentialsProvider.java:371)
>                                                                                         at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(CognitoCachingCredentialsProvider.java:441)
>                                                                                         at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(CognitoCachingCredentialsProvider.java:76)
>                                                                                         at com.amazonaws.services.iot.AWSIotClient.invoke(AWSIotClient.java:3700)
>                                                                                         at com.amazonaws.services.iot.AWSIotClient.createKeysAndCertificate(AWSIotClient.java:754)
>                                                                                         at com.amazonaws.demo.androidpubsub.PubSubActivity$1.run(PubSubActivity.java:192)
>                                                                                         at java.lang.Thread.run(Thread.java:818)

I am positive that the pool ID is correct.

As a general note (or rant)...it seems many example docs here are out of date/incorrect or leave info out. In addition, help seems to be user to user and inconsistent. Personally, I LOVE AWS services - it's amazing what is available. It just seems a bit hard to get help either here or at the AWS forums. I kind of feel like I am on my own and just hacking around until I guess the solutions. The goal of examples is usually to get someone started with training wheels so that they have basic skills to move forward. More often than not it seems like they are incomplete, unclear or out of date with poor help from AWS staff. I have had similar experiences with other AWS github libraries as well.

I have tried two other examples:
AmazonCognitoAuthDemo - I ran into similar issues there.
AmazonCognitoYourUserPoolsDemo - this worked perfectly for me.

Any help would be appreciated.

**Comment by kvasukib** [comment]
Thank you for reporting to us. Sorry for the inconvenience caused. We will look into it.

**Comment by kredden** [comment]
Hi, we will look at getting the docs updated shortly.   To get you going:

Use the link in the readme to take you to the Amazon Cognito page, on that page press the "Manage Federated Identities" button.  On the resulting page press the "Create new Identity pool" button.  On the new page you should see a space to enter the name of the identity pool and then in the "Unauthenticated identities" section you should see the checkbox mentioned in the readme "Enable access to unauthenticated identities", which you need to check.

Next press the "Create Pool" button.  On the resulting page expand the "View Details" section.  This will show you the two roles that are being created.  Click the "Allow" button.

In the resulting page you should see some red text in the "Get AWS Credentials" section, this is your identity pool id.

Next go to the IAM console roles page: https://console.aws.amazon.com/iam/home?region=us-east-1#/roles and search for "pubsub".  Click on the link for the unauth role.

Now click on the "Add inline policy" button and add the policy in the readme, giving it whatever name you choose.

Next click on the IoT console as specified in the readme and click on "Get Started".  On the side panel click on "Secure" and then "Policies".

Click on "Create a Policy". Type in the name you want to call it.  Then click on "Advanced mode" and replace the default policy with the one in the readme and click the "Create" button.

Next set your constant values in PubSubActivity.java.  The endpoint can be found in the "Settings" page of the IoT console.  The Cognito pool id is the red text from the Cognito console that you previosly saved and the IoT policy name is the name of the policy you just created.

I just ran through these steps and got the app running in the simulator.

Hope this helps you out!

Kevin

**Comment by kredden** [comment]
Just checking in to see if this helped you out.

**Comment by flycast** [comment]
Yes, it did. Thank you.

**Comment by kredden** [comment]
Great! I'll close the ticket then.  If you have any additional issues let us know.
