### ISSUE TITLE
how to use cloud search sdk in android application

### ISSUE THREAD

**Issue by Pd51** [awslabs/aws-sdk-android-samples#169]

**Comment by kvasukib** [comment]
Hi @Pd51, Currently our SDK doesn't support CloudSearch. We will take it as a feature request.

**Comment by Pd51** [comment]
Can you suggest me how can i implement search feature in dynamo db for my android application

**Comment by minbi** [comment]
You may `query` the DynamoDB table based on your primary key and sort key.
If you wish to "search" on any arbitrary field, then you will need to `scan` the table (This is expensive and should only be used if absolutely necessary).
