### ISSUE TITLE
Unexpected char 0x0a at 82 in header

### ISSUE THREAD

**Issue by CristianCardosoA** [awslabs/aws-sdk-android-samples#173]
This is still happening on version: com.amazonaws:aws-android-sdk-cognitoauth:2.4.7@aar

java.lang.IllegalArgumentException: Unexpected char 0x0a at 82 in header value: Basic ****

https://github.com/aws/aws-sdk-android/pull/327

Any updates @kvasukib ?

**Comment by drxeno02** [comment]
That's because Amazon fools won't merge my fix into their updates. I asked them to, and resolved this issue 2 months ago. But in Amazon fashion they are dragging their feet. If they do not fix in 2 weeks, I am switching to Microsoft. And I suggest you do the same.

**Comment by drxeno02** [comment]
All they have to do is change line 72 in Pkce.java (aws-sdk-android/aws-android-sdk-cognitoauth/src/main/java/com/amazonaws/mobileconnectors/cognitoauth/util/Pkce.java)

Update to: Base64.encodeToString(digestBytes, Base64.URL_SAFE | Base64.NO_WRAP | Base64.NO_PADDING);

That will resolve everything. They won't even take the 1 second required to make that change. Which is the ONLY way SSO will work for their cognito services. So 1 second of work is being ignored that blocks the entire service.

**Comment by kvasukib** [comment]
Hi, @CristianCardosoA and @drxeno02, Sorry for the inconvenience caused. We will be doing the merge in the next few days. We will communicate here once we test and merge in the changes.

**Comment by kvasukib** [comment]
Hi @CristianCardosoA and @drxeno02, We have fixed the issue in 2.6.13 release. Please check and let us know if it fixes the issue. Sorry for the inconvenience caused in the meantime. Thanks for helping us out with submitting a Pull Request.
