### ISSUE TITLE
Is required Cognito Pool Id for mqtt connection

### ISSUE THREAD

**Issue by yusufonderd** [awslabs/aws-sdk-android-samples#174]
Hi all,
Is required Cognito Pool Id for mqtt connection ?

**Comment by kvasukib** [comment]
Hi @yusufonderd, Are you referring to IdentityPool or UserPool?

**Comment by yusufonderd** [comment]
Yes it is. For example iot java sdk don't need cognito. It this possible for android ?

**Comment by kvasukib** [comment]
All of the samples require Amazon Cognito Identity.
