### ISSUE TITLE
AccessDenied for S3TransferUtilitySample

### ISSUE THREAD

**Issue by milindshah077** [awslabs/aws-sdk-android-samples#177]
Hi, 
I have imported the S3TransferUtilitySample Project. I have created a bucket and a corresponding IAM rule with permissions to access it. I have been following this guide: http://docs.aws.amazon.com/mobile/sdkforandroid/developerguide/s3transferutility.html

However, while uploading it shows AccessDenied. When I changed the permission of the S3 bucket to public, I was able to upload but download is still failing with the same error. 

How can I upload and download without making the bucket public? Also, why is the access control for IAM not working in this case?

Please help. 

Regards,
Milind.

**Comment by milindshah077** [comment]
HI,
I was able to figure out the reason for this. 
In my IAM permission policy, I had 

"Resource": [
                "arn:aws:s3:::bucketName"
            ]
when I changed it to "arn:aws:s3:::bucketName/*", the upload worked fine. However, the download still did not work. For the download to work, we have to also give permissions on the bucket and not just the objects inside the bucket. Thus the following policy worked: 
"Resource": [
                "arn:aws:s3:::bucketName",
                "arn:aws:s3:::bucketName/*"
            ]

This should be updated in the aws documentation as well. Thanks.

**Comment by cbommas** [comment]
Hello milindshah077,

The link https://aws.amazon.com/blogs/security/writing-iam-policies-how-to-grant-access-to-an-amazon-s3-bucket/ in the developer guide describes the policy for programmatic access and details out what needs to be set for the bucket and for the objects in the bucket. 

Please feel free to reply back on this thread if you have further questions.
