### ISSUE TITLE
AWS IOT Reconnecting Issue 

### ISSUE THREAD

**Issue by yusufonderd** [awslabs/aws-sdk-android-samples#179]
I'm following AndroidPubSubWebSocket sample code. I tried app on Android version 7.1.1, 5.0.2,  4.4.4. Android 7.1.1 successfully connected. But I can't connect with Android 4.4.4 and 5.0.2. 

Library version : compile 'com.amazonaws:aws-android-sdk-iot:2.6.12'
 

Status is constantly reconnecting.  

```
mqttManager.connect(credentialsProvider, AWSIotMqttClientStatusCallback { status, throwable ->
                runOnUiThread {
                    if (status == AWSIotMqttClientStatus.Connecting) {
                        log("Connecting...")
                    } else if (status == AWSIotMqttClientStatus.Connected) {
                        log("Connected")
                    } else if (status == AWSIotMqttClientStatus.Reconnecting) {
                        if (throwable != null) {
                            log("Connection error.")
                        }
                        log("Reconnecting")
                    } else if (status == AWSIotMqttClientStatus.ConnectionLost) {
                        if (throwable != null) {
                            log("Connection error.")
                            throwable.printStackTrace()
                        }
                        log("Disconnected")
                    } else {
                        log("Disconnected")
                    }
                }
            })


```

Log: 
MainActivity : Connecting...
AWSIotMqttManager: onFailure: connection failed.
AWSIotMqttManager: schedule Reconnect attempt 0 of 10 in 4 seconds.
MainActivity : Reconnecting
AWSIotMqttManager: attempting to reconnect to mqtt broker
AWSIotMqttManager: Reconnect failed 
AWSIotMqttManager: schedule Reconnect attempt 1 of 10 in 8 seconds.
MainActivity : Reconnecting
AWSIotMqttManager: attempting to reconnect to mqtt broker
AWSIotMqttManager: Reconnect failed 
AWSIotMqttManager: schedule Reconnect attempt 2 of 10 in 16 seconds.
MainActivity : Reconnecting
...

**Comment by tonyteate** [comment]
Likewise. This issue is duplicated [here](https://github.com/aws/aws-sdk-android/issues/353) and [here](https://github.com/aws/aws-sdk-android/issues/394), the latter of which appears to have the most interest. 

Just noting in case anyone else is having the same problem and lands on this thread.

**Comment by Hemant0601** [comment]
Hi, I am not sure about the AWS MQTT but I was using my own MQTT server and the connection issue sometimes happen if I am using same CLIENT_ID. Please check if that's the case.

**Comment by aroravinay4** [comment]
Hello folks,

The client fails to connect initially, and remains stuck attempting to reconnect.we have attempted providing credentials using both Cognito and basic AWS.

We are using "UUID.randomUUID().toString() + System.currentTimeMillis();" for generating client id.

07-03 19:45:59.840 12813-12813/com.net.pubsubandroidfinal D/com.net.pubsubandroidfinal.MainActivity: topic = hi 07-03 19:46:03.301 12813-12813/com.net.pubsubandroidfinal D/com.net.pubsubandroidfinal.MainActivity: clientId = e9a03b89-2b39-4b31-a854-6013300f810a1530627337890 07-03 19:46:03.443 12813-12813/com.net.pubsubandroidfinal I/AWSIotMqttManager: metrics collection is enabled, username: ?SDK=Android&Version=2.6.23 07-03 19:46:03.444 12813-12813/com.net.pubsubandroidfinal I/AWSIotMqttManager: resetting reconnect attempt and retry time 07-03 19:46:03.444 12813-12813/com.net.pubsubandroidfinal D/com.net.pubsubandroidfinal.MainActivity: Status = Connecting 07-03 19:46:05.673 12813-13522/com.net.pubsubandroidfinal W/AWSIotMqttManager: onFailure: connection failed. 07-03 19:46:05.673 12813-13522/com.net.pubsubandroidfinal D/com.net.pubsubandroidfinal.MainActivity: Status = Reconnecting 07-03 19:46:05.673 12813-13522/com.net.pubsubandroidfinal I/AWSIotMqttManager: schedule Reconnect attempt 0 of 10 in 4 seconds. 07-03 19:46:09.680 12813-13526/com.net.pubsubandroidfinal I/AWSIotMqttManager: attempting to reconnect to mqtt broker 07-03 19:46:11.970 12813-13561/com.net.pubsubandroidfinal W/AWSIotMqttManager: Reconnect failed 07-03 19:46:11.971 12813-13561/com.net.pubsubandroidfinal I/AWSIotMqttManager: schedule Reconnect attempt 1 of 10 in 8 seconds. 07-03 19:46:11.973 12813-13561/com.net.pubsubandroidfinal D/com.net.pubsubandroidfinal.MainActivity: Status = Reconnecting 07-03 19:46:19.982 12813-13565/com.net.pubsubandroidfinal I/AWSIotMqttManager: attempting to reconnect to mqtt broker 07-03 19:46:23.487 12813-13647/com.net.pubsubandroidfinal W/AWSIotMqttManager: Reconnect failed 07-03 19:46:23.488 12813-13647/com.net.pubsubandroidfinal I/AWSIotMqttManager: schedule Reconnect attempt 2 of 10 in 16 seconds. 07-03 19:46:23.489 12813-13647/com.net.pubsubandroidfinal D/com.net.pubsubandroidfinal.MainActivity: Status = Reconnecting 07-03 19:46:39.506 12813-13665/com.net.pubsubandroidfinal I/AWSIotMqttManager: attempting to reconnect to mqtt broker 07-03 19:46:41.914 12813-13782/com.net.pubsubandroidfinal W/AWSIotMqttManager: Reconnect failed.

Please help Us.
Thanks in advance.

**Comment by Hemant0601** [comment]
@aroravinay4 

Check my above solution, it mostly happens because of same CLIENT ID used by other client.

Thanks

**Comment by shibinvadayatt** [comment]
This issue is from MQTT paho library. Use version 1.0.0. That will solve this issue.

**Comment by desokroshan** [comment]
We are tracking IoT reconnection issues in the AndroidPubSubWebSocket sample [here](https://github.com/aws/aws-sdk-android/issues/394). Please update that thread if you have any additional findings/issues. Closing this thread.
