### ISSUE TITLE
DynamoDBMapper_UserPreference_Cognito

### ISSUE THREAD

**Issue by taha7ussein007** [awslabs/aws-sdk-android-samples#180]
I/UserPreferenceDemoActivity: createTableBttn clicked.
D/CognitoCachingCredentialsProvider: Loading credentials from SharedPreferences
D/CognitoCachingCredentialsProvider: No valid credentials found in SharedPreferences
D/CognitoCachingCredentialsProvider: Loading credentials from SharedPreferences
D/CognitoCachingCredentialsProvider: No valid credentials found in SharedPreferences
E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
                  Process: com.amazonaws.demo.userpreferencesom, PID: 6718
Application terminated.

**Comment by kvasukib** [comment]
Hi @taha7ussein007,

Thanks for reporting to us. I download the sample and followed the instructions on README.

This is the excerpt from the log cat:

Just opening the app for the first time:

1-10 11:18:39.658 5083-5083/com.amazonaws.demo.userpreferencesom I/UserPreferenceDemoActivity: createTableBttn clicked.
01-10 11:18:40.037 5083-5105/com.amazonaws.demo.userpreferencesom D/CognitoCachingCredentialsProvider: Loading credentials from SharedPreferences
01-10 11:18:40.037 5083-5105/com.amazonaws.demo.userpreferencesom D/CognitoCachingCredentialsProvider: No valid credentials found in SharedPreferences
01-10 11:18:40.585 5083-5105/com.amazonaws.demo.userpreferencesom D/CognitoCachingCredentialsProvider: Loading credentials from SharedPreferences
01-10 11:18:40.585 5083-5105/com.amazonaws.demo.userpreferencesom D/CognitoCachingCredentialsProvider: No valid credentials found in SharedPreferences
01-10 11:18:40.604 5083-5105/com.amazonaws.demo.userpreferencesom D/NetworkSecurityConfig: No Network Security Config specified, using platform default
01-10 11:18:41.118 5083-5105/com.amazonaws.demo.userpreferencesom D/CognitoCachingCredentialsProvider: Identity id is changed
01-10 11:18:41.118 5083-5105/com.amazonaws.demo.userpreferencesom D/CognitoCachingCredentialsProvider: Saving identity id to SharedPreferences
01-10 11:18:41.120 5083-5105/com.amazonaws.demo.userpreferencesom D/CognitoCachingCredentialsProvider: Clearing credentials from SharedPreferences
01-10 11:18:41.381 5083-5105/com.amazonaws.demo.userpreferencesom D/CognitoCachingCredentialsProvider: Saving credentials to SharedPreferences

Re-opening the app from background.

01-10 11:17:29.949 3750-3750/com.amazonaws.demo.userpreferencesom I/UserPreferenceDemoActivity: createTableBttn clicked.
01-10 11:17:30.001 3750-4756/com.amazonaws.demo.userpreferencesom D/CognitoCachingCredentialsProvider: Loading credentials from SharedPreferences

Can you post any stacktrace if you got in the logcat/Android Monitor?
Can you verify if the Unauthenticated role of the Identity Pool has DynamoDB access?
Can you verify in [Constants.java](https://github.com/awslabs/aws-sdk-android-samples/blob/master/DynamoDBMapper_UserPreference_Cognito/src/com/amazonaws/demo/userpreferencesom/Constants.java) for the Identity pool and region values?

**Comment by taha7ussein007** [comment]
thanks a lot , @kvasukib 
I configured my credentials on the machine but it wasn't able to detect it every time so simply i opened the Internet connection to make it get credentials on-line .
