### ISSUE TITLE
DexArchiveMergerException: Unable to merge dex error with aws-android-sdk-cognitoidentityprovider and cognito jar files

### ISSUE THREAD

**Issue by KMiso** [awslabs/aws-sdk-android-samples#181]
Hi, I am trying to use AWS cognito on android studio .
I learned that I need to import aws-android-sdk-cognitoidentityprovider and cognito jar files.
But when I import those jar files, I keep getting the same error...
I looked it up, and tried every ways I found such as cleaning or setting multidexenabled true.
But couldn't solve the problem.
Please let me know if you have any ideas how to fix this.
Thank you

Error:
---------------------------------------------------------------------------------------------------
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex
----------------------------------------------------------------------------------------------------

**Comment by kvasukib** [comment]
Refer [Issue](https://github.com/aws/aws-sdk-android/issues/396)

**Comment by kvasukib** [comment]
Closing this as the original [issue](https://github.com/aws/aws-sdk-android/issues/396) is closed now.
