### ISSUE TITLE
TemperatureControl/README.md is not self-contained (and possibly in-complete).

### ISSUE THREAD

**Issue by Kumfert** [awslabs/aws-sdk-android-samples#182]
I successfully worked through the AndroidPubSub example. But my experience with theTemperature Control Sample is fraught with complications.  Unfortunately, the README.md relies too much on external projects to be self contained.  Even then, I suspect there are important set-up steps that are missing from both.

In particular, neither this readme or the associated example (from a Javascript SDK, why JS?) really describe how to create the Thing instances or types in the AWS IoT console. Without that, I don't see how there could be shadow things to connect to. 

Please reconsider their design of the samples to make them completely self-contained --- in code as well as instructions.

Also, some screen shots to explain what the sample actually demonstrates and how it should look would be helpful.

Finally, there's a typo in the TemperatureControl/Readme.md file.  s/applicaiton/application/;

**Comment by kvasukib** [comment]
Thanks, @Kumfert for using our sample and for the suggestion. We have fixed the typo in the README. We are looking into improving the sample.

**Comment by muellerfr** [comment]
Hi @Kumfert,

Thank you for your feedback. After some review, we have decided to deprecate the TemperatureControl sample. It will be fully delete from the repo in two weeks. 

If you have any questions about using IoT please open an issue [here](https://github.com/aws-amplify/aws-sdk-android/issues).
