### ISSUE TITLE
Getting issue when resume the uploaded file by use of TransferUtility , resume start from 0% 

### ISSUE THREAD

**Issue by nrup-parikh-indianic** [awslabs/aws-sdk-android-samples#184]
When we start uploading any file and after some time pause it , it will pause properly but when resume it will not resumed from last byte transfered. 

bellow is the method we are calling for resume

TransferObserver resumed = transferUtility.resume(observers.get(checkedIndex)                            .getId());

we are getting 0% ( start from begining ) when click on resume button.

**Comment by kvasukib** [comment]
Hi @nrup-parikh-indianic, 

Thanks for reporting to us. 

How large is the file that you are trying to upload? 
Does this happen for every file and every upload?

**Comment by nrup-parikh-indianic** [comment]
Hi
Thank you for quick reply.
The file size is 30 mb .
Try to upload 5mb and 10mb also.
But issue comes when start uploading and pause when about more then 10mb or
15 mb uploaded and resume the uploading.
Try with multiple file and individual file but getting same issue.
We are passing observer Id of current file upload in resume and log that,
the Id was same at time of start uploading but file resume from first byte
in most of the case.

Some time it start from 5mb but actually more then 5 mb already uploaded.
So getting weired behavior.

Thank you
