### ISSUE TITLE
Documentation quality

### ISSUE THREAD

**Issue by Pantkowsky** [awslabs/aws-sdk-android-samples#186]
Hi,

Can somebody here shed some light on how to successfully enable custom Sign-Up functionality with AWS Cognito for an android app? Your documentation is scattered all around the web and explains so little that I feel like reading an incomplete instruction for something I've never built before, in a language I do not speak. 

You guys have documentation that seems out of date (I've stumbled on instructions such as "top-right corner of the page there is a button" where in reality there is nothing there), with additional lack of any information on where to start and what to do in order to successfully enable sign-up flows. Tried to hook up google sign up method before, none of your documentation helped at all, not to mention that the classes you offer with AWS Android SDK have pretty much the same naming, but are located in different packages (like SignInManager in com.amazonaws.mobile.user and SignInManager in com.amazonaws.mobile.auth) which makes it even harder to comprehend what is happening. This is so far the worst documentation I've stumbled upon and I'm completely clueless how to move forward with implementing sign-up flows using AWS cognito. 

Can you please explain where to start and how to do it, comprehensively ?! I would really appreciate any help here.

**Comment by swaminator** [comment]
Hi @Pantkowsky: Really sorry that you're facing these issues. Have you checked out our updated docs? We make it really easy to add a sign-in UI to your Android app: https://docs.aws.amazon.com/aws-mobile/latest/developerguide/add-aws-mobile-user-sign-in.html

If you could email me at the address listed on my GitHub profile, would be happy to get on a call with you to alleviate your concerns.

**Comment by Pantkowsky** [comment]
Hey @swaminator ! Thanks so much for prompt reply. Yes, I have checked the link you had passed me. Unfortunately, without any luck. Thing is, the documentation provided on the given link does not account for any issues that one might have with it - it simply assumes itself being 'plug'n'play' and that everything will work. 

On top of the discussed approach, I have also found other suggestions on how to supposedly hook up custom sign up with AWS:
- https://aws.amazon.com/cognito/
- https://docs.aws.amazon.com/cognito/latest/developerguide/developer-authenticated-identities.html
- https://github.com/awslabs/aws-sdk-android-samples/tree/master/AmazonCognitoYourUserPoolsDemo

Neither one resulted in success so far. It would be great to get some help and guidance here.

**Comment by swaminator** [comment]
@Pantkowsky: Can you email me at nikhil@live.ca? I'd love to jump on a call with you to better understand your situation and how we can help you out.

**Comment by Pantkowsky** [comment]
@swaminator I already did, on 25th of january.

**Comment by swaminator** [comment]
@Pantkowsky: Were you able to get it to work?

**Comment by Pantkowsky** [comment]
To who may be reading this issue in the future:

Thanks to the amazing help and effort of @swaminator (and few other Amazon developers which names I unfortunately do not remember) I was able to finally make sense of the provided Amazon documentation and solve my issue. Suggested steps provided in Amazon documentation in regards to User Sign Up (https://docs.aws.amazon.com/aws-mobile/latest/developerguide/add-aws-mobile-user-sign-in.html) do in fact work. It is however important to include several dependencies:

`   compile "com.amazonaws:aws-android-sdk-auth-core:2.6.14"
    compile "com.amazonaws:aws-android-sdk-auth-userpools:2.6.14"
    compile ('com.amazonaws:aws-android-sdk-mobile-client:2.6.+@aar') {transitive = true}
    compile ('com.amazonaws:aws-android-sdk-auth-ui:2.6.+@aar') { transitive = true }
    compile ('com.amazonaws:aws-android-sdk-auth-facebook:2.6.+@aar') { transitive = true }
    compile ('com.amazonaws:aws-android-sdk-auth-google:2.6.0') { transitive = true }`

Provided link suggest to include different dependencies for a different `SignInProvider`, however it is necessary to include them all, as otherwise one will stumble upon compilation errors. Then 
`AWSMobileClient.getInstance().initialize(this, new AWSStartupHandler() {
            @Override
            public void onComplete(AWSStartupResult awsStartupResult) {
                SignInUI signin = (SignInUI) AWSMobileClient.getInstance().getClient(AuthenticatorActivity.this, SignInUI.class);
                signin.login(AuthenticatorActivity.this, NextActivity.class).execute();
            }
        }).execute();`

will work. I was also able to solve my problem with Login flow by manually extending `CognitoUserPoolsSignInProvider`. `CognitoUserPoolsSignInProvider` is a good place to start if one needs to fine-tune their sign-up flow, however be informed that it might also be required to extend additional classes ( `SignUpActivity` and `SignUpConfirmActivity` ) at the end. 

For those that had implemented their sign-up flow before the 3rd quarter of 2017, and are possibly having issues in regards to user sign-up with AWS, it is important to mention that there has been a change of SDK packages:

Change from
`com.amazonaws.mobile.user`
to
`com.amazonaws.mobile.auth`
and hopefully have your problems resolved.

Again, many thanks to the Amazon Tech Team for being kind and understanding, and providing me with exhaustive help in solving the issues I have had with AWS Android SDK.
