### ISSUE TITLE
Proguard obfuscation

### ISSUE THREAD

**Issue by trauzti** [awslabs/aws-sdk-android-samples#19]
I had to add these two lines to proguard-project.txt in the S3_TransferManager sample to make it usable:

-dontwarn com.amazonaws.org.joda.time.**
-keep class com.amazonaws.org.apache.commons.logging.** { *; }

**Comment by fosterzhang** [comment]
Thanks for the heads up. Joda isn't required anymore. It makes sense to keep apache common logging which is been jarjar-ed under com.amazonaws.
