### ISSUE TITLE
TransferUtility errors out without completion for large files (~1GB)

### ISSUE THREAD

**Issue by Festak** [awslabs/aws-sdk-android-samples#190]
On android 7+ if i started uploading a large video file like 1GB in background mode (start uploading and turned off the screen), then sometimes after 400-700 uploaded megabytes amazon gave me the failure state with the message: Error: Unable to execute HTTP request: connection timed out.

Does somebody know what is wrong? Now i am using amazon SDK version 2.2.22, but on 2.6.14 absolutely the same issue.

That is how i am configuring transfer utility:
` 
    private static AmazonConfigManager manager;
 
   private static final int SOCKET_TIMEOUT = 300000;
    private static final int MAX_AMAZON_ERRORS_ENTRY = 10;
    private static final int CONNECTION_TIMEOUT = 30000;

    private AmazonConfigs configs;
    private TransferUtility transferUtility;
    private TransferUtility acceleratedTransferUtility;

    private AmazonConfigManager() {
        // do nothing
    }

    public static AmazonConfigManager getManager(){
        if(manager == null){
            manager = new AmazonConfigManager();
        }
        return manager;
    }

    public AmazonConfigs getConfigs() {
        if (configs == null) {
            return new AmazonConfigs();
        }
        return configs;

    }

    public void setConfigs(AmazonConfigs configs) {
        this.configs = configs;
    }

    public TransferUtility getTransferUtility(Context context) {
        if (transferUtility == null) {
            transferUtility = new TransferUtility(getS3Client(context.getApplicationContext(), false),
                    context.getApplicationContext());
        }

        return transferUtility;
    }

    public TransferUtility getAcceleratedTransferUtility(Context context) {
        if (acceleratedTransferUtility == null) {
            boolean isAccelerated = getConfigs() != null && getConfigs().is_accelerated();
            acceleratedTransferUtility = new TransferUtility(getS3Client(context.getApplicationContext(), isAccelerated),
                    context.getApplicationContext());
        }
        return acceleratedTransferUtility;
    }

    public void clearAmazonVariables(){
        acceleratedTransferUtility = null;
        transferUtility = null;
    }

    private CognitoCachingCredentialsProvider getCredProvider(Context context) {
        return new CognitoCachingCredentialsProvider(
                context.getApplicationContext(),
                context.getResources().getString(R.string.s3_pool_id),
                Regions.US_EAST_1);
    }

    private AmazonS3Client getS3Client(Context context, boolean isAccelerated) {
        ClientConfiguration cc = new ClientConfiguration();
        cc.setSocketTimeout(SOCKET_TIMEOUT);
        cc.setProtocol(Protocol.HTTP);
        cc.setMaxErrorRetry(MAX_AMAZON_ERRORS_ENTRY);
        cc.setConnectionTimeout(CONNECTION_TIMEOUT);
        AmazonS3Client s3Client = new AmazonS3Client(getCredProvider(context.getApplicationContext()), cc);
     //   s3Client.setRegion(Region.getRegion(Regions.US_EAST_1));

        if (isAccelerated) {
            s3Client.setS3ClientOptions(S3ClientOptions.builder().setAccelerateModeEnabled(true).build());
        }

        return s3Client;
    }`

**Comment by kvasukib** [comment]
Hi @Festak,

Thank you for reporting to us. Sorry for the inconvenience caused. How much time did it take to get the first failure "Unable to execute HTTP request" after the transfer was started?

**Comment by Festak** [comment]
I can't reproduce it, but my client can ;) I guess every time when she starts uploading video and then turned off application to background - it's reproducing (On my android 6 everything is ok). Here is the tracking results:
additionalMessage : Unable to execute HTTP request: Connection timed out
SDK Version : 7602
App Version : 16
fileName : d8606-29494.MOV
videoDuration : 104601 (ms)
fileSize : 981798809 (981 megabyte)
Platform : ANDROID

**Comment by Festak** [comment]
Also, I  have an interesting try. I set socket timeout in configuration to 0 - which means infinity. And after 500 uploaded megabyte upload stopped. State was in IN_PROGRESS, but uploading stopped. And what I did, I just turned off and then turned on my internet connection and uploading resumed.

**Comment by Festak** [comment]
Also the way to reproduce:
Go to Settings > Developer options. Under the app section change the Background process limit to No background processes.
Then start upload file and turn off the application and then block your device.
After 400 uploaded megabytes I got an error a few minutes ago:
`02-05 12:27:14.536 9862-10143/com.euclid.uptiiq E/UploadPartTask: Encountered error uploading part Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed. (Service: Amazon S3; Status Code: 400; Error Code: RequestTimeout; Request ID: 3C1A541F0FA81C8A)
02-05 12:27:14.540 9862-9862/com.euclid.uptiiq W/System.err: com.amazonaws.services.s3.model.AmazonS3Exception: Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed. (Service: Amazon S3; Status Code: 400; Error Code: RequestTimeout; Request ID: 3C1A541F0FA81C8A), S3 Extended Request ID: /td1N9fQlZxblAq9mtG8RSnOm1/FAtJ4nEYcWKbiRWprt9sReZPzQvj0GHF3LzklBFgZUfIFZDekSvgaNWPE2WS5Ae2EiZzH
02-05 12:27:14.546 9862-9862/com.euclid.uptiiq W/System.err:     at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:712)
02-05 12:27:14.546 9862-9862/com.euclid.uptiiq W/System.err:     at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:388)
02-05 12:27:14.546 9862-9862/com.euclid.uptiiq W/System.err:     at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:199)
02-05 12:27:14.546 9862-9862/com.euclid.uptiiq W/System.err:     at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4375)
02-05 12:27:14.546 9862-9862/com.euclid.uptiiq W/System.err:     at com.amazonaws.services.s3.AmazonS3Client.uploadPart(AmazonS3Client.java:3454)
02-05 12:27:14.546 9862-9862/com.euclid.uptiiq W/System.err:     at com.amazonaws.mobileconnectors.s3.transferutility.UploadPartTask.call(UploadPartTask.java:47)
02-05 12:27:14.546 9862-9862/com.euclid.uptiiq W/System.err:     at com.amazonaws.mobileconnectors.s3.transferutility.UploadPartTask.call(UploadPartTask.java:27)
02-05 12:27:14.547 9862-9862/com.euclid.uptiiq W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
02-05 12:27:14.547 9862-9862/com.euclid.uptiiq W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
02-05 12:27:14.547 9862-9862/com.euclid.uptiiq W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
02-05 12:27:14.547 9862-9862/com.euclid.uptiiq W/System.err:     at java.lang.Thread.run(Thread.java:761)`

**Comment by kvasukib** [comment]
Hi @Festak 

Thank you for the detailed analysis. I am able to see the behavior that you observed. Android 8.1 (API 27); 2.6.14 version SDK; Upload a file of 1.07 GB text file. When the app goes to background after 10MB of transfer, the upload continues in background until 50-60% progress (500-600MB) and after that the app crashes.

The app crash is related to monitor lock contention and the OS stops the app from executing. If I open the app again and just call resume on the transfer, the transfer resumes and finishes eventually.

This might be a stress test for the multi-part upload of large files. I haven't noticed this behavior for download as download is single threaded. Debugging into the crash noticed in the app.

**Comment by Festak** [comment]
Hi @kvasukib 

My app is not crashed, just gave the error as I previously said. Do you have any advice, what to do? My client absolutely dislike this behaviour :(

**Comment by Festak** [comment]
And if uploading failure, I am trying to restart the upload, but it's just stuck on 0 megabyte and doesn't want to start the upload at all.

**Comment by Festak** [comment]
Actually, maybe you should use in your service wake lock?
Like this example https://developer.android.com/training/scheduling/wakelock.html#wakeful
It keeps CPU still working in background mode, as i understood.

**Comment by Festak** [comment]
Hi @kvasukib 
Do you have any suggestions what I can do?

**Comment by kvasukib** [comment]
This problem stems from the fact that we use a thread pool whose size is the number of processors + 1. We use ```final int processors = Runtime.getRuntime().availableProcessors();``` to find the number of processors. We have two executor service. One for the main upload/download task whose size is processors + 1. The other one is for the upload part tasks whose size is again processors + 1.

So in total, there are 2 ( N + 1 ). We are working on providing a flag to customize this. That should help control the number of threads that are contending for the resource.

**Comment by Festak** [comment]
@kvasukib Ok, great. Will you notify me when the update will be ready?

**Comment by kvasukib** [comment]
Yes, we would notify you on this thread when we make the update! Thank you for the patience.

**Comment by kvasukib** [comment]
Hi @Festak, Sorry for the delayed reply. We released 2.6.16 with enhancements for stability in TransferUtility. Now you have a flag to customize the size of the thread pool for the transfers. We have documented it here: https://docs.aws.amazon.com/aws-mobile/latest/developerguide/how-to-transfer-files-with-transfer-utility.html#native-transfer-utility-options Please let us know if this works for you.

**Comment by Festak** [comment]
Hi @kvasukib. Will test it in the near days.
