### ISSUE TITLE
No address associated with hostname

### ISSUE THREAD

**Issue by dgaurav-163** [awslabs/aws-sdk-android-samples#192]
Hi 
I am trying to use lex sample on android device but i am getting this error, While I have added all required items.
Using These Required Value :  
 "app_name"- "Lex Sample"
   name="bot_name"
  "bot_alias"- "$LATEST"
   "identity_id_test" - ap-south - "1:7b23e6d5-fac1-4c8c-93ef-7ac0fd332951"
    "cognito_region - "ap-south-1"
    name="lex_region" - "ap-south-1"
    "screen_options_main_message"- "Amazon Lex"

Error Message
Error: Unable to execute HTTP request: Unable to resolve host "runtime.lex.ap-south-1.amazonaws.com": No address associated with hostname

Kindly review and confirm. Let me know What is missing from my end.

Thanks in Advance
Gaurav

**Comment by kvasukib** [comment]
Thank you @dgaurav-163 for reporting to us. Amazon Lex is not yet supported in "ap-south-1" region. You can see a list of the supported AWS Regions for Lex here: [Amazon Lex Regions and Endpoints](https://docs.aws.amazon.com/general/latest/gr/rande.html#lex_region)

**Comment by dgaurav-163** [comment]
Thanks @kvasukib for your update! Let me check for different available region.
