### ISSUE TITLE
AWSKinesisVideoDemoApp - No Fragments Found

### ISSUE THREAD

**Issue by vince-nyanga** [awslabs/aws-sdk-android-samples#193]
I'm trying to run the AWSKinesisVideoDemoApp and the demo-stream is created but the video preview keeps on saying `No fragments found`.
Device: Samsung Galaxy S7 Edge
OS Version: 7.0

**Comment by minbi** [comment]
Hi @vince-nyanga ,

Can you check the logs in verbose mode and see if there are any issues? You may paste them here as well.

**Comment by minbi** [comment]
We have seen a similar issue when the region was not set properly in the app. The region setting is now exposed at this line in the current sample app.

**Comment by minbi** [comment]
Please re-open or create another issue is problem persists.
