### ISSUE TITLE
AmazonKinesisVideoDemoApp can't send to ap-northeast-1

### ISSUE THREAD

**Issue by hryktrd** [awslabs/aws-sdk-android-samples#195]
I use this sample application to send video stream to ap-northeast-1,
but it send to us-west-2 despite I set Region ap-northeast-1 to awsconfiguration.json.

I put my settings below.

```json
{
  "Version": "1.0",
  "CredentialsProvider": {
    "CognitoIdentity": {
      "Default": {
        "PoolId": "ap-northeast-1:xxxxx",
        "Region": "ap-northeast-1"
      }
    }
  },
  "IdentityManager": {
    "Default": {}
  },
  "CognitoUserPool": {
    "Default": {
      "AppClientSecret": "xxxxxx",
      "AppClientId": "xxxxxx",
      "PoolId": "ap-northeast-1_xxxxxxx",
      "Region": "ap-northeast-1"
    }
  }
}
```

Did I something wrong ?

Thank you.

**Comment by hryktrd** [comment]
Thank you for your reply.
I solved it by make class like KinesisVideoAndroidClientFactory and rewite DERAULT to AP-NORTHEAST-1.

Do you have a plan to fix it to read awsconfiguration.json to set region?

**Comment by cbommas** [comment]
@hryktrd 

Yes, we are looking at ways to improve our configuration mechanisms and to make it easier for customers to use the SDK.  Please feel free to post back on this thread if you have any further questions.
