### ISSUE TITLE
aws ses example for android 

### ISSUE THREAD

**Issue by Pd51** [awslabs/aws-sdk-android-samples#198]

**Comment by Hemant0601** [comment]
Can you provide more details to understand??

**Comment by Pd51** [comment]
how to use ses for sending mail to users using aws  android sdk any examples will be helpful

**Comment by Hemant0601** [comment]
Have a look at below link

1. https://docs.aws.amazon.com/ses/latest/DeveloperGuide/send-an-email-using-sdk.html

2. https://docs.aws.amazon.com/ses/latest/DeveloperGuide/send-an-email-using-sdk-programmatically.html

Start with 2nd if all prerequisites are done mentioned in step 1.

**Comment by minbi** [comment]
To be clear, the Java and Android SDKs are different, so if you use documentation for the Java SDKs, then there will be differences in API names.

Thank you for asking for a SES sample app, we will take this as a feature request.
