### ISSUE TITLE
Amazon mobile push app pops up frequently to foreground while running in background.

### ISSUE THREAD

**Issue by dmsherazi** [awslabs/aws-sdk-android-samples#20]
Although it is not a part of the samples here in this repository still I guess it is somewhat related as it is based on the AWS sdk fro android. The app would frequently pop up and minimize the active app. Here is the link  [ snsmobilepush.zip!](http://docs.aws.amazon.com/sns/latest/dg/samples/snsmobilepush.zip)

**Comment by fosterzhang** [comment]
The sample isn't owned by the SDK. We will consider add a SNS sample in the future.
