### ISSUE TITLE
Regarding aws Dynamodb performance in loading data android sdk

### ISSUE THREAD

**Issue by Pd51** [awslabs/aws-sdk-android-samples#201]
I use asynctask for loading items from dynamodb using aws android sdk DynamodbMapper class 
the problem is it is taking more time to get the results even with high speed internet so is there any way to access dynamodb using endpoint url and fetch data using volley or retrofit which is fast when compared to traditional async task i've searched the documentation for low level api but it is not clear and dax is also a better approach but there is no clear example of how to use dax in  android sdk
provide can you help me to solve this issue .

**Comment by kvasukib** [comment]
Hi @Pd51, Thank you for reporting to us. You can refer to the Amazon DynamoDB low-level API in the following resources:

https://docs.aws.amazon.com/AWSAndroidSDK/latest/javadoc/ (Search for "AmazonDynamoDBClient")

Source code: https://github.com/aws/aws-sdk-android/tree/master/aws-android-sdk-ddb

https://github.com/aws/aws-sdk-android/blob/master/aws-android-sdk-ddb/src/main/java/com/amazonaws/services/dynamodbv2/AmazonDynamoDBClient.java
