### ISSUE TITLE
Restrict Bucket Access

### ISSUE THREAD

**Issue by Hemant0601** [awslabs/aws-sdk-android-samples#202]
I have a bucket having public access to upload objects and then download.
What I need is having some sort of key or anything by which only my application will be able to upload and download the content.
If I change access of bucket then I was not able to upload in it and was getting error of authorisation.

**Comment by kvasukib** [comment]
Thank you @Hemant0601 for reporting to us. You can refer these links for information on configuring the required access policies on the bucket: 

https://docs.aws.amazon.com/AmazonS3/latest/dev/s3-access-control.html
IAM: https://aws.amazon.com/blogs/security/how-to-restrict-amazon-s3-bucket-access-to-a-specific-iam-role/
Cognito: https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_examples_s3_cognito-bucket.html

**Comment by Hemant0601** [comment]
@kvasukib I guess I have done this previously but thats giving public access where anyone can upload, I need it restricted to only my Android App. Is that kind of restriction is allowed?

**Comment by rohandubal** [comment]
Hello @Hemant0601 

There is no direct way to restrict uploads/ downloads from a specific Android App. You could create access key and secret key and bundle it with the app(which is risky) or create a identity pool with un-auth access to achieve this. The bucket won't be public but would be under controlled access by IAM.

Thanks,
Rohan
