### ISSUE TITLE
java.security.UnrecoverableKeyException: no match

### ISSUE THREAD

**Issue by isha31** [awslabs/aws-sdk-android-samples#204]
I am facing one issue while integrating AWS Iot SDK in my Xamarin.android app.
I am creating basic app just to connect to mqtt through AWS Iot to subscribe to topics and and publish messages to that topic.
I am getting "java.security.UnrecoverableKeyException:no match" in getTempKeystore method in AWSIotKeystoreHelper class. I have followed the steps exactly as mentioned.
Please help me!

**Comment by cbommas** [comment]
hello @isha31 

Sorry to hear that you are encountering issues. Can you post your code sample and a link to the doc that outlines the steps you are following?

**Comment by isha31** [comment]
@cbommas Thanks for your reply!
I followed the steps exactly as mentioned here : 
[https://github.com/awslabs/aws-sdk-android-samples/tree/master/AndroidPubSub](url)
I am using bouncy caslte : bcprov-jdk15on-159.jar
My code snippet is : 
`   private static String CUSTOMER_SPECIFIC_ENDPOINT = "";
    private static String COGNITO_POOL_ID = "";
    private static String AWS_IOT_POLICY_NAME = "";
    private static Regions MY_REGION = Regions.UsEast2;
    private static String KEYSTORE_NAME = "";
    private static String KEYSTORE_PASSWORD = "";
    private static String CERTIFICATE_ID = "";
    clientId = UUID.RandomUUID().ToString();
        credentialsProvider = new CognitoCachingCredentialsProvider(
        Android.App.Application.Context, // context
        COGNITO_POOL_ID, // Identity Pool ID
        MY_REGION // Region
    );

        Region region = Region.GetRegion(MY_REGION);
        mqttManager = new AWSIotMqttManager(clientId, CUSTOMER_SPECIFIC_ENDPOINT);           
        mqttManager.KeepAlive = 10;
        AWSIotMqttLastWillAndTestament lwt = new AWSIotMqttLastWillAndTestament("my/lwt/topic", "Android client lost connection", AWSIotMqttQos.Qos0);
        mqttManager.MqttLastWillAndTestament = lwt;

        mIotAndroidClient = new AWSIotClient(credentialsProvider);
        mIotAndroidClient.SetRegion(region);
        keystorePath = FilesDir.AbsolutePath;
        keystoreName = KEYSTORE_NAME;
        keystorePassword = KEYSTORE_PASSWORD;
        certificateId = CERTIFICATE_ID;
            if ((bool)AWSIotKeystoreHelper.IsKeystorePresent(keystorePath, keystoreName))
            {
               if ((bool)AWSIotKeystoreHelper.KeystoreContainsAlias(certificateId, keystorePath, keystoreName, keystorePassword))
                  {               
                    clientKeyStore = AWSIotKeystoreHelper.GetIotKeystore(certificateId, keystorePath, keystoreName, keystorePassword);
                  }`
               else
                  {
                    Log.Info(LOG_TAG, "Key/cert " + certificateId + " not found in keystore.");
                  }
            }
            else
            {
               Log.Info(LOG_TAG, "Keystore " + keystorePath + "/" + keystoreName + " not found.");
            }``

**Comment by cbommas** [comment]
Hello @isha31 

I tried the sample on my side and I did not encounter the exception. I did some digging to understand why the issue may be happening.  A couple of things to rule out are 1) was the cert/keystore created a while ago with another version of the software 2) has the password of the keystore changed.

Can you change the name of the keystore, by changing the value in KEYSTORE_NAME,  to trigger the creation of a new keystore and run the sample again. The idea here is that the code will create a new keystore, generate a certficate and add it to the new keystore, retrieve the certificate and use it for mutual auth and connect to the MQTT server.

Can you try and let me know how it goes?

**Comment by isha31** [comment]
@cbommas I made the changes and ran the sample. Its working great. Also I tried giving the same password for 'source' and 'destination' while keystore creation using bouncy castle and even that solved the problem.

**Comment by cbommas** [comment]
thanks @isha31 for confirming.
