### ISSUE TITLE
AndroidPubSub API 24 issur

### ISSUE THREAD

**Issue by matszal** [awslabs/aws-sdk-android-samples#207]
Hi,
I just needed to update API to 24 for further testing and noticed following issue with the sample app. Any ideas what might be causing this?

It works fine with API 23!

```    --------- beginning of crash
03-26 23:04:27.841 4921-4921/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.mateusz.homesecurity, PID: 4921
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.mateusz.homesecurity/com.example.mateusz.homesecurity.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
        at com.amazonaws.mobileconnectors.iot.AwsIotEndpointUtility.stripPort(AwsIotEndpointUtility.java:39)
        at com.amazonaws.mobileconnectors.iot.AwsIotEndpointUtility.getAccountPrefixFromEndpont(AwsIotEndpointUtility.java:90)
        at com.amazonaws.mobileconnectors.iot.AWSIotMqttManager.<init>(AWSIotMqttManager.java:545)
        at com.example.mateusz.homesecurity.MainActivity.onCreate(MainActivity.java:151)
        at android.app.Activity.performCreate(Activity.java:6662)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6077) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756) ```

**Comment by kvasukib** [comment]
Thank you @matszal for reporting to us. Sorry for the inconvenience caused. This exception after strip the port off of the endpoint if present. Can you check what's the endpoint you have configured in your app? Is it a valid endpoint?

**Comment by matszal** [comment]
I'm reading all the details from emulator storage let me work on this to make sure this is fully working. Will update you ASAP

**Comment by kvasukib** [comment]
Hi @matszal, Thank you for the reply. Can you point me to the IoT Sample app that you are using? If not, can you post the sample code where you use `AWSIotMqttManager`?

**Comment by matszal** [comment]
Hi @kvasukib, think my problem is when im reading details from internal storage. Here's code:

`package com.example.mateusz.homesecurity;

import android.Manifest;
import android.content.DialogInterface;
import android.content.Intent;
import android.os.AsyncTask;
import android.os.Bundle;
import android.os.Environment;
import android.os.StrictMode;
import android.support.annotation.NonNull;
import android.support.v7.app.AlertDialog;
import android.support.v7.app.AppCompatActivity;
import android.util.Log;
import android.view.View;
import android.widget.Button;
import android.widget.TextView;
import android.widget.Toast;
import android.content.Context;
import android.net.ConnectivityManager;
import android.net.NetworkInfo;
import com.amazonaws.auth.CognitoCachingCredentialsProvider;
import com.amazonaws.mobileconnectors.iot.AWSIotKeystoreHelper;
import com.amazonaws.mobileconnectors.iot.AWSIotMqttClientStatusCallback;
import com.amazonaws.mobileconnectors.iot.AWSIotMqttLastWillAndTestament;
import com.amazonaws.mobileconnectors.iot.AWSIotMqttManager;
import com.amazonaws.mobileconnectors.iot.AWSIotMqttQos;
import com.amazonaws.regions.Region;
import com.amazonaws.regions.Regions;
import com.amazonaws.services.iot.AWSIotClient;
import com.amazonaws.services.iot.model.AttachPrincipalPolicyRequest;
import com.amazonaws.services.iot.model.CreateKeysAndCertificateRequest;
import com.amazonaws.services.iot.model.CreateKeysAndCertificateResult;
import com.google.gson.Gson;

import org.json.JSONException;
import org.json.JSONObject;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.Serializable;
import java.nio.MappedByteBuffer;
import java.nio.channels.FileChannel;
import java.nio.charset.Charset;
import java.security.KeyStore;
import java.util.UUID;

import permissions.dispatcher.NeedsPermission;
import permissions.dispatcher.OnNeverAskAgain;
import permissions.dispatcher.OnShowRationale;
import permissions.dispatcher.PermissionRequest;
import permissions.dispatcher.RuntimePermissions;

@RuntimePermissions
public class MainActivity extends AppCompatActivity{
    static final String LOG_TAG = MainActivity.class.getCanonicalName();

    //Toast.makeText(this, String.valueOf(sdcard), Toast.LENGTH_SHORT).show();

    private static String CUSTOMER_SPECIFIC_ENDPOINT;       //cse
    private static String COGNITO_POOL_ID;                  //cp_id
    private static String AWS_IOT_POLICY_NAME;              //policy
    private static Regions MY_REGION = Regions.EU_WEST_1;
    private static String KEYSTORE_NAME;                    //key_name
    private static String KEYSTORE_PASSWORD;                //key_pass;
    private static String CERTIFICATE_ID;                   //cert_id

    String clientId;
    String keystorePath;
    String keystoreName;
    String keystorePassword;

    KeyStore clientKeyStore = null;
    String certificateId;

    private String fileName = "/credentials_app.json";

    //TextView keysWindow;
    Button btnConnect;
    Button btnDisconnect;
    TextView tvClientId;
    TextView tvStatus;

    File sdcard = new File(Environment.getExternalStorageDirectory() + fileName);

    static AWSIotClient mIotAndroidClient;
    static AWSIotMqttManager mqttManager;

    CognitoCachingCredentialsProvider credentialsProvider;


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        //Allowing Strict mode policy for Nougat support
        StrictMode.VmPolicy.Builder builder = new StrictMode.VmPolicy.Builder();
        StrictMode.setVmPolicy(builder.build());

       // Toast.makeText(this, "App started succesfully!",
         //       Toast.LENGTH_SHORT).show();

        Log.i("info", "Done creating the app");


        //Check if app has an access to internet
        if (!AppStatus.getInstance(this).isOnline()) {

           // Toast.makeText(this,"Please check your internet connection",Toast.LENGTH_LONG).show();
            Log.v("Home", "############################You are not online!!!!");
            //btnConnect.setEnabled(false);

        }

        //Read all credentials on separate thread
        AsyncTask.execute(new Runnable() {
            @Override
            public void run() {
                readStorage();
            }
        });


        tvClientId = (TextView) findViewById(R.id.tvClientId);
        tvStatus = (TextView) findViewById(R.id.tvStatus);

        btnConnect = (Button)findViewById(R.id.btnConnect);
        btnConnect.setOnClickListener(connect);
        btnConnect.setEnabled(false);

        btnDisconnect = (Button)findViewById(R.id.btnDisconnect);
        btnDisconnect.setOnClickListener(disconnect);



        // MQTT client IDs are required to be unique per AWS IoT account.
        // This UUID is "practically unique" but does not _guarantee_
        // uniqueness.
        clientId = UUID.randomUUID().toString();
        tvClientId.setText(clientId);

        // Initialize the AWS Cognito credentials provider
        credentialsProvider = new CognitoCachingCredentialsProvider(
                getApplicationContext(), // context
                COGNITO_POOL_ID, // Identity Pool ID
                MY_REGION // Region
        );

        Region region = Region.getRegion(MY_REGION);

        // MQTT Client
        mqttManager = new AWSIotMqttManager(clientId, CUSTOMER_SPECIFIC_ENDPOINT);

        // Set keepalive to 10 seconds.  Will recognize disconnects more quickly but will also send
        // MQTT pings every 10 seconds.
        mqttManager.setKeepAlive(10);

        // Set Last Will and Testament for MQTT.  On an unclean disconnect (loss of connection)
        // AWS IoT will publish this message to alert other clients.
        AWSIotMqttLastWillAndTestament lwt = new AWSIotMqttLastWillAndTestament("my/lwt/topic",
                "Android client lost connection", AWSIotMqttQos.QOS0);
        mqttManager.setMqttLastWillAndTestament(lwt);

        // IoT Client (for creation of certificate if needed)
        mIotAndroidClient = new AWSIotClient(credentialsProvider);
        mIotAndroidClient.setRegion(region);

        keystorePath = getFilesDir().getPath();
        keystoreName = KEYSTORE_NAME;
        keystorePassword = KEYSTORE_PASSWORD;
        certificateId = CERTIFICATE_ID;

        // To load cert/key from keystore on filesystem
        try {
            if (AWSIotKeystoreHelper.isKeystorePresent(keystorePath, keystoreName)) {
                if (AWSIotKeystoreHelper.keystoreContainsAlias(certificateId, keystorePath,
                        keystoreName, keystorePassword)) {
                    Log.i(LOG_TAG, "Certificate " + certificateId
                            + " found in keystore - using for MQTT.");
                    // load keystore from file into memory to pass on connection
                    clientKeyStore = AWSIotKeystoreHelper.getIotKeystore(certificateId,
                            keystorePath, keystoreName, keystorePassword);
                    btnConnect.setEnabled(true);
                } else {
                    Log.i(LOG_TAG, "Key/cert " + certificateId + " not found in keystore.");
                }
            } else {
                Log.i(LOG_TAG, "Keystore " + keystorePath + "/" + keystoreName + " not found.");
            }
        } catch (Exception e) {
            Log.e(LOG_TAG, "An error occurred retrieving cert/key from keystore.", e);
        }

        if (clientKeyStore == null) {
            Log.i(LOG_TAG, "Cert/key was not found in keystore - creating new key and certificate.");

            new Thread(new Runnable() {
                @Override
                public void run() {
                    try {
                        // Create a new private key and certificate. This call
                        // creates both on the server and returns them to the
                        // device.
                        CreateKeysAndCertificateRequest createKeysAndCertificateRequest =
                                new CreateKeysAndCertificateRequest();
                        createKeysAndCertificateRequest.setSetAsActive(true);
                        final CreateKeysAndCertificateResult createKeysAndCertificateResult;
                        createKeysAndCertificateResult =
                                mIotAndroidClient.createKeysAndCertificate(createKeysAndCertificateRequest);
                        Log.i(LOG_TAG,
                                "Cert ID: " +
                                        createKeysAndCertificateResult.getCertificateId() +
                                        " created.");

                        // store in keystore for use in MQTT client
                        // saved as alias "default" so a new certificate isn't
                        // generated each run of this application
                        AWSIotKeystoreHelper.saveCertificateAndPrivateKey(certificateId,
                                createKeysAndCertificateResult.getCertificatePem(),
                                createKeysAndCertificateResult.getKeyPair().getPrivateKey(),
                                keystorePath, keystoreName, keystorePassword);

                        // load keystore from file into memory to pass on
                        // connection
                        clientKeyStore = AWSIotKeystoreHelper.getIotKeystore(certificateId,
                                keystorePath, keystoreName, keystorePassword);

                        // Attach a policy to the newly created certificate.
                        // This flow assumes the policy was already created in
                        // AWS IoT and we are now just attaching it to the
                        // certificate.
                        AttachPrincipalPolicyRequest policyAttachRequest =
                                new AttachPrincipalPolicyRequest();
                        policyAttachRequest.setPolicyName(AWS_IOT_POLICY_NAME);
                        policyAttachRequest.setPrincipal(createKeysAndCertificateResult
                                .getCertificateArn());
                        mIotAndroidClient.attachPrincipalPolicy(policyAttachRequest);

                        runOnUiThread(new Runnable() {
                            @Override
                            public void run() {
                                btnConnect.setEnabled(true);
                            }
                        });
                    } catch (Exception e) {
                        Log.e(LOG_TAG,
                                "Exception occurred when generating new private key and certificate.",
                                e);
                    }
                }
            }).start();
        }
    }

    @NeedsPermission(Manifest.permission.READ_EXTERNAL_STORAGE)
    void readStorage() {

        try {
            FileInputStream fis = new FileInputStream((sdcard));
            String jsonStr = null;

            try{
                FileChannel fc = fis.getChannel();
                MappedByteBuffer bb = fc.map(FileChannel.MapMode.READ_ONLY, 0, fc.size());
                jsonStr = Charset.defaultCharset().decode(bb).toString();
            }catch(Exception e){
               // Toast.makeText(this, "exception after reading json object!", Toast.LENGTH_SHORT).show();
            }
            finally {
                fis.close();
            }

            JSONObject jsonObj = new JSONObject(jsonStr);
            JSONObject data = jsonObj.getJSONObject("credentials");

            CUSTOMER_SPECIFIC_ENDPOINT = data.getString("cse");
            COGNITO_POOL_ID = data.getString("cp_id");
            AWS_IOT_POLICY_NAME = data.getString("policy");
            KEYSTORE_NAME = data.getString("key_name");
            KEYSTORE_PASSWORD = data.getString("key_pass");
            CERTIFICATE_ID = data.getString("cert_id");

        } catch (IOException e) {
           // Toast.makeText(getApplicationContext(), "Error While reading file", Toast.LENGTH_SHORT).show();
        } catch (JSONException e){
            //Toast.makeText(getApplicationContext(), "JSON exception", Toast.LENGTH_SHORT).show();
        }

    }

    @Override
    public void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions, @NonNull int[] grantResults) {
        super.onRequestPermissionsResult(requestCode, permissions, grantResults);
        MainActivityPermissionsDispatcher.onRequestPermissionsResult(this, requestCode, grantResults);
    }

    @OnShowRationale(Manifest.permission.READ_EXTERNAL_STORAGE)
    void readStorageRationale(final PermissionRequest request) {
        new AlertDialog.Builder(this)
                .setMessage("To read internal storage, enable Read Storage")
                .setPositiveButton("OK", new DialogInterface.OnClickListener() {
                    @Override
                    public void onClick(DialogInterface dialogInterface, int i) {
                        request.proceed();
                    }
                })
                .setNegativeButton("Deny", new DialogInterface.OnClickListener() {
                    @Override
                    public void onClick(DialogInterface dialogInterface, int i) {
                        request.cancel();
                    }
                })
                .show();
    }

    @OnNeverAskAgain(Manifest.permission.READ_EXTERNAL_STORAGE)
    void sendMessageNever() {
      //  Toast.makeText(this, "You have denied permission", Toast.LENGTH_SHORT).show();
    }



    public static class AppStatus {

        private static AppStatus instance = new AppStatus();
        static Context context;
        ConnectivityManager connectivityManager;
        NetworkInfo wifiInfo, mobileInfo;
        boolean connected = false;

        public static AppStatus getInstance(Context ctx) {
            context = ctx.getApplicationContext();
            return instance;
        }

        public boolean isOnline() {
            try {
                connectivityManager = (ConnectivityManager) context
                        .getSystemService(Context.CONNECTIVITY_SERVICE);

                NetworkInfo networkInfo = connectivityManager.getActiveNetworkInfo();
                connected = networkInfo != null && networkInfo.isAvailable() &&
                        networkInfo.isConnected();
                return connected;


            } catch (Exception e) {
                System.out.println("CheckConnectivity Exception: " + e.getMessage());
                Log.v("connectivity", e.toString());
            }
            return connected;
        }
    }




    View.OnClickListener connect = new View.OnClickListener() {
        @Override
        public void onClick(final View v) {
            Log.d(LOG_TAG, "clientId = " + clientId);

            try {
                mqttManager.connect(clientKeyStore, new AWSIotMqttClientStatusCallback() {
                    @Override
                    public void onStatusChanged(final AWSIotMqttClientStatus status,
                                                final Throwable throwable) {
                    Log.d(LOG_TAG, "Status = " + String.valueOf(status));

                    runOnUiThread(new Runnable() {
                        @Override
                        public void run() {
                            if (status == AWSIotMqttClientStatus.Connecting) {
                                tvStatus.setText("Connecting...");

                            } else if (status == AWSIotMqttClientStatus.Connected) {
                                tvStatus.setText("Connected");
                                btnConnect.setEnabled(false);


                                //Gson gson = new Gson();
                                //String mqttAsString = gson.toJson(mqttManager);

                                Intent intent = new Intent(v.getContext(), TabbedActivity.class);
                                //intent.putExtra("object", mqttAsString);
                                v.getContext().startActivity(intent);

                            } else if (status == AWSIotMqttClientStatus.Reconnecting) {
                                if (throwable != null) {
                                    Log.e(LOG_TAG, "Connection error.", throwable);
                                }
                                tvStatus.setText("Reconnecting");
                            } else if (status == AWSIotMqttClientStatus.ConnectionLost) {
                                if (throwable != null) {
                                    Log.e(LOG_TAG, "Connection error.", throwable);
                                }
                                tvStatus.setText("Disconnected");
                                btnConnect.setEnabled(true);
                            } else {
                                tvStatus.setText("Disconnected");
                                btnConnect.setEnabled(true);

                            }
                        }
                    });
                    }
                });
            } catch (final Exception e) {
                Log.e(LOG_TAG, "Connection error.", e);
                tvStatus.setText("Error! " + e.getMessage());
            }

        }

    };

    View.OnClickListener disconnect = new View.OnClickListener() {
        @Override
        public void onClick(View v) {

            try {
                mqttManager.disconnect();
            } catch (Exception e) {
                Log.e(LOG_TAG, "Disconnect error.", e);
            }

        }
    };



}`

And theres a tab fragment:

`package com.example.mateusz.homesecurity;

import android.content.Intent;
import android.os.Bundle;
import android.support.annotation.Nullable;
import android.support.v4.app.Fragment;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;

import com.amazonaws.mobileconnectors.iot.AWSIotMqttLastWillAndTestament;
import com.amazonaws.mobileconnectors.iot.AWSIotMqttManager;
import com.amazonaws.mobileconnectors.iot.AWSIotMqttNewMessageCallback;
import com.amazonaws.mobileconnectors.iot.AWSIotMqttQos;
import com.google.gson.Gson;


import android.widget.EditText;
import android.widget.TextView;
import android.widget.Toast;

import java.io.UnsupportedEncodingException;
import java.util.zip.Inflater;

import static com.example.mateusz.homesecurity.MainActivity.LOG_TAG;
import static com.example.mateusz.homesecurity.MainActivity.mqttManager;

/**
 * Created by Mateusz on 25/03/2018.
 */

public class Tab1Fragment extends Fragment {
    private static final String TAG = "Tab1Fragment";

    //AWSIotMqttManager mqttManager;



    //private Button btnTest1;
    private Button btnPublish;
    private Button btnClearAll;
    private TextView incomingText;
    private EditText outgoingtext;

    private String id;
    private String endPoint;


    @Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {

        View view = inflater.inflate(R.layout.tab1_fragment, container, false);


        subscribe();
        btnPublish = (Button)view.findViewById(R.id.btnPublish);
        btnPublish.setOnClickListener(publishClick);

        btnClearAll = (Button)view.findViewById(R.id.btnClear);

        incomingText = (TextView)view.findViewById(R.id.incomingTxt);

        outgoingtext = (EditText)view.findViewById(R.id.outgoingTxt);


        return view;
    }



    public void subscribe() {

        final String topic = "mytopic/iot/led";

        Log.d(LOG_TAG, "topic = " + topic);

        try {
            mqttManager.subscribeToTopic(topic, AWSIotMqttQos.QOS0, new AWSIotMqttNewMessageCallback() {
                    @Override
                    public void onMessageArrived(final String topic, final byte[] data) {
                        try {
                            String message = new String(data, "UTF-8");
                            Log.d(LOG_TAG, "Message arrived:");
                            Log.d(LOG_TAG, "   Topic: " + topic);
                            Log.d(LOG_TAG, " Message: " + message);

                            incomingText.setText(message);

                        } catch (UnsupportedEncodingException e) {
                            Log.e(LOG_TAG, "Message encoding error.", e);
                        }
                    }
                });



            } catch (Exception e) {
                Log.e(LOG_TAG, "Subscription error.", e);
            }
        }

    View.OnClickListener publishClick = new View.OnClickListener() {
        @Override
        public void onClick(View v) {

            final String topic = "mytopic/iot";
            final String msg = outgoingtext.getText().toString();

            try {
                mqttManager.publishString(msg, topic, AWSIotMqttQos.QOS0);
            } catch (Exception e) {
                Log.e(LOG_TAG, "Publish error.", e);
            }

        }
    };


}
`

**Comment by kvasukib** [comment]
Thanks @matszal for sharing the code snippet. We just updated the `README` instructions of the `AndroidPubSub` sample app with precise information on the policies setup. 

Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
        at com.amazonaws.mobileconnectors.iot.AwsIotEndpointUtility.stripPort(AwsIotEndpointUtility.java:39)
        at com.amazonaws.mobileconnectors.iot.AwsIotEndpointUtility.getAccountPrefixFromEndpont(AwsIotEndpointUtility.java:90)
        at com.amazonaws.mobileconnectors.iot.AWSIotMqttManager.<init>(AWSIotMqttManager.java:545)

It's clear that the CUSTOMER_SPECIFIC_ENDPOINT is null as the getAccountPrefixFromEndpont is trying to operate on it and found the endpoint to be null. Can you follow the README to retrieve the endpoint from the Settings section in your AWS IoT Console and paste that in the CUSTOMER_SPECIFIC_ENDPOINT variable?

**Comment by matszal** [comment]
Thanks @kvasukib for an update and genuine help and interst in solving my issue. My problem is: I can not hard code CUSTOMER_SPECIFIC_ENDPOINT and other aws details, because this is a college project and im required to upload all to VCS. Thats the reason why I need to read this from a file. My phone sgs7e has no root access and thats the reson im getting this exception I think. It works fine from android emulator.

**Comment by kvasukib** [comment]
Thank you @matszal for the reply. You need to check if the CUSTOMER_SPECIFIC_ENDPOINT is not null before being passed into the `AWSIotMqttManager` constructor. You can add a log statement before constructing the AWSIotMqttManager object to ensure you have the right endpoint.

You can subscribe to multiple topics in a loop or in parallel. The subscribe method allows you to subscribe to one topic in a call. However you can loop subscribe over the different topics you have or have multiple threads, where each thread subscribes to a topic. We will take a feature request to provide a method to subscribe to multiple topics in one method.

**Comment by matszal** [comment]
Thank you @kvasukib for all the help provided. I am going to close this issue as my problem has been solved. Thanks again!
