### ISSUE TITLE
S3TransferUtilitySample- how to upload multiple files (bulk) at once.

### ISSUE THREAD

**Issue by sarvale** [awslabs/aws-sdk-android-samples#208]
able to upload single file to S3 bucket  using TransferUtility.how to upload multiple files (bulk) at once.

**Comment by cbommas** [comment]
hello @sarvale 

You can use the TransferUtility to upload files in parallel. You don't have wait for a previous transfer to complete before initiating the next one.

**Comment by sarvale** [comment]
Hi @cbommas, Thank you for the reply.Currently i am using TransferUtility  to upload single file at a time but i want to give multiple files selection option so user can upload multiple file once instead of one by one. I tried to change widget and TransferUtility  class but its not working.If you have example please share.
Thanks,
sarvale

**Comment by kvasukib** [comment]
@sarvale Thank you for the reply. Currently, the TransferUtility.upload just takes one file at a time. As @cbommas said you can loop over all the files you have and call upload for each file. From the widget once you know the list of files selected, grab their file path information, construct File objects for each and invoke upload for each of the File objects in a loop or in parallel.

**Comment by sarvale** [comment]
Thanks a ton kvasukib.I will try this approach.
