### ISSUE TITLE
facebook login notworking

### ISSUE THREAD

**Issue by lakshmisvtech** [awslabs/aws-sdk-android-samples#21]
I have implemented facebook as per the instructions, i am getting following error, when trying sync the dataset,

 E/ListDatasetsActivity(8541): Caused by: com.amazonaws.AmazonServiceException: 1 validation error detected: Value '{graph.facebook.com=}' at 'logins' failed to satisfy constraint: Map value must satisfy constraint: [Member must have length less than or equal to 2048, Member must have length greater than or equal to 1, Member must satisfy regular expression pattern: [\S]+] (Service: AmazonCognitoIdentity; Status Code: 400; Error Code: ValidationException; Request ID: e1df945a-98a1-11e4-b934-6d5e6adaec7e)

Note: The code is exactly as per the example cognitodemosync, Has key was verified using
try {
        	PackageInfo info = getPackageManager().getPackageInfo(
        	      "com.amazonaws.cognito.sync.demo", PackageManager.GET_SIGNATURES);
        	for (Signature signature : info.signatures){
        	       MessageDigest md = MessageDigest.getInstance("SHA");
        	       md.update(signature.toByteArray());
        	       Log.d("KeyHash:", Base64.encodeToString(md.digest(), Base64.DEFAULT));
        	}
        	} catch (NameNotFoundException e) {
        		e.getMessage();
        	} catch (NoSuchAlgorithmException e) {
        	}

**Comment by behrooziAWS** [comment]
You need to set the value of graph.facebook.com to the facebook authentication token you get when you login to facebook.  It doesn't appear you have set it here, please double check.

**Comment by muneeb091** [comment]
Do inform if you have solved the issue. According to your log, David's
answer is the solution.

**Comment by lakshmisvtech** [comment]
hi thanks, 
the problem is with facebookid, once it is solved token came up.
thanks a lot

**Comment by muneeb091** [comment]
Anytime.
