### ISSUE TITLE
About AWS IoT connection as a service + integration of other demo apps

### ISSUE THREAD

**Issue by matszal** [awslabs/aws-sdk-android-samples#210]
Hi, I have a question regarding AWS demo AndroidPubSub and others to integrate couple of AWS services into one app. My college project has few services running on raspberry pi like IoT mqtt, dynamoDB, S3 and maybe kinesis. I am wondering if it's possible to integrate all of above services and communicate with all from android phone just by using one app?

At the moment I've created a basic app, based on AndroidPubSub demo. Connection with AWS is been dealt with in MainActivity. After connecting to AWS, I’m starting new activity with few tabs MQTT, S3, and kinesis. What I am worried about is: app is sometimes freezing on mqtt tab! I am new to Android and wondering if AWS connection should be running as a background service?

below is a link to my github project https://github.com/matszal/Android_App_4_FYP.git

It would be really appreciated if I could get some help with this issue please

**Comment by kvasukib** [comment]
Thank you @matszal for reporting to us. You can create a Cognito Identity Pool and edit the Unauth role of the Cognito identity pool to attach policies to access S3, DynamoDB, IoT and Kinesis. When you followed AndroidPubSub sample, you have done this only for IoT. But you can edit the inline-policy of the Unauth role to access S3, DynamODB and Kinesis resources. After this your policy might look like this:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "iot:*",
                "s3:*",
                "dynamodb:*",
                "kinesis:*"
            ],
            "Resource": [
                "*"
            ]
        }
    ]
}
```

The above policy means your Cognito Identity Pool has full access in {S3, Kinesis, DynamoDB, IoT} to all resources in your account. This is good for a prototype app, however for production apps, we suggest you to specify exactly the resources you want to provide access.

After this backend setup, create a CredentialsProvider, for example, CognitoCachingCredentialsProvider which is created based on the Cognito IdentityPool Id and region and you can pass this credentials provider to other SDK clients such as TransferUtility (S3), KinesisRecorder (Kinesis), DynamoDBObjectMapper (DynamoDB) and AWSIotMqttManager (IoT).

You can take a look at our documentation here: https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-native-how-tos.html

This repository also has sample apps for S3, DynamoDB and IoT, from which you can pull out the activities and use it in your app.

**Comment by matszal** [comment]
Thank you @kvasukib for good explanation and provided samples I will study documentation once more. In terms of maintaining connection between androidPubSub and other activities (tabs in thid case) what would be the best approach do you think? 

Run all the code below as a service?

`// Initialize the AWS Cognito credentials provider
        credentialsProvider = new CognitoCachingCredentialsProvider(
                getApplicationContext(), // context
                COGNITO_POOL_ID, // Identity Pool ID
                MY_REGION // Region
        );

        Region region = Region.getRegion(MY_REGION);

        // MQTT Client
        mqttManager = new AWSIotMqttManager(clientId, CUSTOMER_SPECIFIC_ENDPOINT);

        // Set keepalive to 10 seconds.  Will recognize disconnects more quickly but will also send
        // MQTT pings every 10 seconds.
        mqttManager.setKeepAlive(10);

        // Set Last Will and Testament for MQTT.  On an unclean disconnect (loss of connection)
        // AWS IoT will publish this message to alert other clients.
        AWSIotMqttLastWillAndTestament lwt = new AWSIotMqttLastWillAndTestament("my/lwt/topic",
                "Android client lost connection", AWSIotMqttQos.QOS0);
        mqttManager.setMqttLastWillAndTestament(lwt);

        // IoT Client (for creation of certificate if needed)
        mIotAndroidClient = new AWSIotClient(credentialsProvider);
        mIotAndroidClient.setRegion(region);`

**Comment by kvasukib** [comment]
To share the credentialsProvider between different activities/fragments, you can have a utility class which is a singleton and that creates and maintains the credentialsProvider object. This way you can use the same credentialsProvider object in all the four fragments.

An alternative way would be to have each activity/fragment create their own credentialsProvider object.
