### ISSUE TITLE
how to use Dax with dynamo db in android 

### ISSUE THREAD

**Issue by Pd51** [awslabs/aws-sdk-android-samples#211]
how can I utilize Dax performance with dynamodb in android any sample code in android is helpful

**Comment by kvasukib** [comment]
THank you @Pd51 for reporting to us. Can you elaborate on the question with more details?

**Comment by Pd51** [comment]
i want to use dax for my application for micro seconds latency but i didn't find any samples on how to use dax in android like gradle library or any sample code any sample code in android on how to use dax with dynamodb in android is helpful thanks your for reply.

**Comment by behrooziAWS** [comment]
No, you cannot use DAX from android.  Your DAX cluster is only accessible to EC2 instances running in a VPC.  Realistically the only way you can get microsecond latency on android is if you are working with a local datastore, anything over the network you are looking at milliseconds.
