### ISSUE TITLE
I am trying to connect to DynamoDb through Cognito using the code that Amazon provides. All I change are the app specific parameters. When I execute the code I get the following exception:

### ISSUE THREAD

**Issue by Pd51** [awslabs/aws-sdk-android-samples#212]
com.amazonaws.AmazonClientException: Unable to execute HTTP request: Unable to resolve host "cognito-identity.us-east-1.amazonaws.com": No address associated with hostname.

i even added <uses-permission android:name="android.permission.INTERNET" />

**Comment by kvasukib** [comment]
Thank you @Pd51 for reporting to us. 

Can you check if the network access is not blocked and you have network connectivity. Also have you added NETWORK_STATE permission in the `AndroidManifest.xml`?
Can you post a code snippet and the stacktrace for further debugging?
