### ISSUE TITLE
How to use X.509 or keystore to get iot shadow information?

### ISSUE THREAD

**Issue by pwa16000** [awslabs/aws-sdk-android-samples#216]
Hi,

I have x.509 certificate on the device and want to use AWS IoT android SDK to retrieve Shadow information or do some operation on Shadow. 

Is there any way to do that? Looks AWSCredentials was needed to create an instance of AWSIotDataClient. Can we create AWSIotDataClient instance by X.509 certificate?

Thanks

Best regards
Philip

**Comment by cbommas** [comment]
Hello @pwa16000 

The AWSIotDataClient cannot be instantiated by X.509 certificate. You have to instantiate it using AWSCredentials.

Here is some sample code on how to instantiate the client using a CognitoIdentityPool to obtain the AWSCredentials

``
CognitoCachingCredentialsProvider credentialsProvider = new CognitoCachingCredentialsProvider(
                getApplicationContext(),
                COGNITO_POOL_ID, // Identity Pool ID
                MY_REGION // Region
        );

AWSIotDataClient iotDataClient = new AWSIotDataClient(credentialsProvider);
``
Please feel free to reopen this topic if you have further questions.
