### ISSUE TITLE
443 timed out Error

### ISSUE THREAD

**Issue by achinverma** [awslabs/aws-sdk-android-samples#22]
hi , i am uploading image on my s3 server and i am running it on 4.4.2 and using WIFI in deviec,
![device-2015-01-19-155509](https://cloud.githubusercontent.com/assets/2811593/5800535/b76850c2-a005-11e4-9e30-f0f773247f99.png)
 and my images are placed in sd card and after uploading i am getting below error, please guide me?

**Comment by muneeb091** [comment]
Hi,
 Please properly check if your wifi is working properly and also you can browse internet. This problem mostly arises due to poor network issues.

**Comment by Aman91Goyal** [comment]
I am also facing same problem ,  i have checked network strength and concerned with my network team  and one more thing at the same time i was trying to upload from more then one device at the same time and same network .
4.4.2
5.0.1(Nexus 4 .In this device same code was working fine).
