### ISSUE TITLE
How to add sessionAttributes in InteractiveVoiceActivity

### ISSUE THREAD

**Issue by mnimkar** [awslabs/aws-sdk-android-samples#222]
I am using aws-sdk-android-sample for lex andoid app.
I want to add some sessionAttributes. while passing voice to InteractiveVoiceActivity How we can add?

Thanks In Advance.

**Comment by kvasukib** [comment]
SessionAttributes: https://docs.aws.amazon.com/lex/latest/dg/context-mgmt.html#context-mgmt-session-attribs

`SessionAttributes` map can be passed in as part of `InteractionConfig`. See 

https://github.com/aws/aws-sdk-android/blob/be47f215e2c2fb9d0a3a2daf9dc62acd8f607b7b/aws-android-sdk-lex/src/main/java/com/amazonaws/mobileconnectors/lex/interactionkit/config/InteractionConfig.java#L121

You can use the above constructor to pass in the session attributes to the InteractionConfig.

https://github.com/awslabs/aws-sdk-android-samples/blob/master/LexSample/app/src/main/java/com/amazonaws/sample/lex/InteractiveVoiceActivity.java#L66

Please let me know if this helps!

**Comment by kvasukib** [comment]
Please feel free to reopen if you have any more questions!

**Comment by mnimkar** [comment]
@kvasukib Thanks It helped for me. 
Sorry for late reply
