### ISSUE TITLE
Error "Not supported in this sample"

### ISSUE THREAD

**Issue by naser-shaikh** [awslabs/aws-sdk-android-samples#225]
I have downloaded latest sample code for KinesisVideoStream and done all the configuration mentioned here, i am getting crash after i log in.

`java.lang.UnsupportedOperationException: Not supported in this sample.
        at com.amazonaws.mobile.auth.userpools.CognitoUserPoolsSignInProvider$6.authenticationChallenge(CognitoUserPoolsSignInProvider.java:331)
        at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser$33.run(CognitoUser.java:2505)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)`

**Comment by minbi** [comment]
Hi @naser-shaikh ,

The KinesisVideoStream sample uses the aws-android-sdk-auth-userpool library to jump start development. The authentication challenge is not supported by that library at this time.

**Comment by minbi** [comment]
If you are creating, the user in the Cognito console, you can disable force password change or remove the requirement to be able to try out the sample. Another way is to use access key and secret key directly

**Comment by naser-shaikh** [comment]
Will try that, thanks for reply.

**Comment by naser-shaikh** [comment]
@minbi  I have tried to remove force password change from configuration side but i am not able to find any solution for that, can you explain me how to use direct access key and secret key. 
thanks in advance.

**Comment by minbi** [comment]
You'll need to move the intent filter [here](https://github.com/awslabs/aws-sdk-android-samples/blob/master/AmazonKinesisVideoDemoApp/src/main/AndroidManifest.xml#L23) to the `SimpleNavActivity` [here](https://github.com/awslabs/aws-sdk-android-samples/blob/master/AmazonKinesisVideoDemoApp/src/main/AndroidManifest.xml#L33). This will bypass the sign-in screen.

Replace [this line](https://github.com/awslabs/aws-sdk-android-samples/blob/master/AmazonKinesisVideoDemoApp/src/main/java/com/amazonaws/kinesisvideo/demoapp/KinesisVideoDemoApp.java#L42) with

```
return new StaticCredentialsProvider(new BasicAWSCredentials("accessKey", "secretKey"))
```

**Comment by naser-shaikh** [comment]
Thanks for replay @minbi , Can you please explain which access key and secrete key i need here, i am trying to use Cognito User Pool's client Id and client secrete, is it right?

**Comment by kvasukib** [comment]
@naser-shaikh  The Access Key and Secret Access Key can be retrieved from the Amazon IAM Console.

**Comment by naser-shaikh** [comment]
@kvasukib @minbi I am able to to login into app now, my question is how to add loading indicators for network operations or for background tasks. The app is look like freezing every time i try to log in or do any operation.

**Comment by muellerfr** [comment]
Hello @naser-shaikh,

Looking at thread, it looks like you sample app and SDK related questions were solved. We do not plan to extend the sample app with loading indicators at the moment. If you still need help using the AWS SDK for Android, please open an issue in aws/aws-sdk-android.
