### ISSUE TITLE
com.amazonaws.AmazonClientException: Unable to execute HTTP request: Unable to resolve host "cognito-identity.us-east-1.amazonaws.com":

### ISSUE THREAD

**Issue by Pd51** [awslabs/aws-sdk-android-samples#226]
sometime i get this error even i have a valid internet connection i've searched google and found some replies like add internet permission in android manifest even though i'am getting this error can some one help me to solve this issue

**Comment by kvasukib** [comment]
Thank you @Pd51 for reporting to us. Can you post the complete stack trace and the logs and a code snippet if possible?

**Comment by kvasukib** [comment]
Usually this error occurs when you switch networks and your emulator/device is not able to connect to the new network.
