### ISSUE TITLE
No Fragment found screen.

### ISSUE THREAD

**Issue by naser-shaikh** [awslabs/aws-sdk-android-samples#227]
I have done all the steps mentioned in this [link](https://github.com/awslabs/aws-sdk-android-samples/tree/master/AmazonKinesisVideoDemoApp), Now i am able to login in to app, and after clicking on stream button it is starting video capturing mode on Android phone. But at AWS Video preview page i am always getting "No Fragment Found" message. I am able to get analytics for same in cognito identity page. Please let me know if i missed something here.

![screen shot 2018-06-18 at 12 50 22 pm](https://user-images.githubusercontent.com/1841299/41522992-ff4f61e8-72f5-11e8-8c93-d5c4031c5f61.png)

![screen shot 2018-06-18 at 12 50 43 pm](https://user-images.githubusercontent.com/1841299/41522997-05b00b64-72f6-11e8-9fb2-d97abd490db0.png)

**Comment by vijaygj** [comment]
Hello,

Can you please send the accountId and logs to the  kinesis-video-support@amazon.com ? We want to check if we are receiving the data and this is playback error; or we are not receiving the data at all.

Thanks,
Vijay.

**Comment by muellerfr** [comment]
Hello @naser-shaikh,

Do you still require help?

**Comment by muellerfr** [comment]
@MixMasterMitch and @naser-shaikh debugged this issue via email. Closing this issue. If you still require help, please open a new issue in the aws/aws-sdk-android repo.
