### ISSUE TITLE
How to use SpeechMark and json output in android 

### ISSUE THREAD

**Issue by Feroz-Istar** [awslabs/aws-sdk-android-samples#228]
Hello Team, 

I am trying to use below configuration of polly in android  

![pollyimage](https://user-images.githubusercontent.com/17778549/41601238-8945fdee-73f5-11e8-9a9a-971014d420cf.png)

So far i have written the below code in my activity async task as follow:

```java
 ArrayList < String > liist = new ArrayList < > ();
 liist.add("viseme");
 liist.add("word");
 SynthesizeSpeechPresignRequest synthesizeSpeechPresignRequest =
  new SynthesizeSpeechPresignRequest()
  // Set text to synthesize.
  .withText(text)
  // Set voice selected by the user.
  .withVoiceId("Raveena")
  .withOutputFormat(OutputFormat.Mp3)
  .withSpeechMarkTypes(liist);
 // Set format to MP3.
 //.withOutputFormat(OutputFormat.Mp3);
 URL presignedSynthesizeSpeechUrl =
  client.getPresignedSynthesizeSpeechUrl(synthesizeSpeechPresignRequest);
 Log.i("sssss", "Playing speech from presigned URL: " + presignedSynthesizeSpeechUrl);

 // Create a media player to play the synthesized audio stream.
 if (mediaPlayer.isPlaying()) {
  setupNewMediaPlayer();
 }
 mediaPlayer.setAudioStreamType(AudioManager.STREAM_MUSIC);

 try {
  // Set media player's data source to previously obtained URL.
  mediaPlayer.setDataSource(presignedSynthesizeSpeechUrl.toString());
 } catch (IOException e) {
  Log.e("ss", "Unable to set data source for the media player! " + e.getMessage());
 }

 // Start the playback asynchronously (since the data source is a network stream).
 mediaPlayer.prepareAsync();
```

How can I implement the config required in the attached image at the Android end?

**Comment by kvasukib** [comment]
Thank you @Feroz-Istar for reporting to us. You can pass in the sample rate, output format and speech mark types in the request.

Sample Rate: https://github.com/aws/aws-sdk-android/blob/a21280396e36fc144e7911032f23d9a508abe4b9/aws-android-sdk-polly/src/main/java/com/amazonaws/services/polly/model/SynthesizeSpeechPresignRequest.java#L517

Doc: https://aws.github.io/aws-sdk-android/docs/reference//index.html?com/amazonaws/services/polly/model/SynthesizeSpeechPresignRequest.html -> Look for withSampleRate

OutputFormat: Json https://github.com/aws/aws-sdk-android/blob/a21280396e36fc144e7911032f23d9a508abe4b9/aws-android-sdk-polly/src/main/java/com/amazonaws/services/polly/model/OutputFormat.java#L26

```java
SynthesizeSpeechPresignRequest synthesizeSpeechPresignRequest = new SynthesizeSpeechPresignRequest()
.withText(text)
.withVoiceId("Raveena")
.withSampleRate("16000")
.withSpeechMarkTypes(liist);
.withOutputFormat(OutputFormat.Json);
```

Let us know if this works.

**Comment by Feroz-Istar** [comment]
@kvasukib thanks for reply. 
Whenever I pass list of string as read and vibeme in SynthesizeSpeechPresignRequest  object i m getting SpeechMarkType are not supported in this format  in the response i couldn't find any sample code of sending it properly. Can you please provide me a simple sample code for specifically for the android . Please

**Comment by kvasukib** [comment]
@Feroz-Istar Sorry for the delayed reply. Speech Mark Types are only supported with JSON output format. See [doc](https://docs.aws.amazon.com/polly/latest/dg/API_SynthesizeSpeech.html#API_SynthesizeSpeech_RequestSyntax) for more details on Output Format.

**Comment by Feroz-Istar** [comment]
@kvasukib thanks for reply.
So you mean to say if i make a second request to fetch the audio in mp3 format how will i get same  speech mark types required in first request?  If possible can you pass some sample code for the same.
PS : I m so sorry about this kind of question I am using polly for first time. I didn't understand how to use speech mark type in android side.

**Comment by kvasukib** [comment]
Thank you @Feroz-Istar for the reply.

Request-1:

SynthesizeSpeechPresignRequest synthesizeSpeechPresignRequest = new SynthesizeSpeechPresignRequest()
    .withText(text)
    .withVoiceId("Raveena")
    .withSampleRate("16000")
    .withSpeechMarkTypes(list);
    .withOutputFormat(OutputFormat.Json);

With this request, you get the json file and you know the speech marks. 

Request-2:

SynthesizeSpeechPresignRequest synthesizeSpeechPresignRequest = new SynthesizeSpeechPresignRequest()
    .withText(text)
    .withVoiceId("Raveena")
    .withSampleRate("16000")
    .withOutputFormat(OutputFormat.MP3);

With this request, you get the mp3 audio file of the text.

Now you can use the metadata from the JSON file received from request-1 along with the mp3 audio file from request-2 and play a certain portion of the audio file in the player.

I believe this is the use-case you are trying to solve: 

The text is "I love Amazon", and you only want to play the word "Amazon" in your audio player.

If this is a use-case you are trying to solve, you can do what I mentioned here by fetching the starting point of the word "Amazon" through request-1 and the audio from request-2 and use both the information to play the word "Amazon". Please correct me if this is not your use-case. Thanks.

**Comment by Feroz-Istar** [comment]
@kvasukib thanks for reply. 

How can i play the response getting from the first request in android ?

**Comment by kvasukib** [comment]
You cannot play the response from the first request. The first request is mainly used to identify the speech mark which can be used as metadata for your audio.
