### ISSUE TITLE
Resumable downloads 

### ISSUE THREAD

**Issue by Sahana312** [awslabs/aws-sdk-android-samples#229]
I am using TransferUtility to download zip files from the s3 bucket. I have a scenario, where I need to pause a download and resume it when ever the user clicks on resume. How do I do this? Is the id coming from the observer listener unique for each download from a device? If the user pauses the download on Day 1 and wants to resume on Day 2, how do I achieve this using TransferUtility?

**Comment by kvasukib** [comment]
Thank you @Sahana312 for reporting to us. Yes, you can pause and resume downloads. We persist the transfer record in SQLite database and as long as the file where the partial content downloaded is present, the download can be resumed from the point where it was left.

Pause a transfer: [Documentation](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/how-to-transfer-files-with-transfer-utility.html#native-pause-a-transfer)

Resume a transfer: [Documentation](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/how-to-transfer-files-with-transfer-utility.html#native-resume-a-transfer)

```java
        TransferObserver downloadObserver =
              transferUtility.download(
                    "s3Folder/s3Key.txt",
                    new File("/path/to/file/localFile.txt"));

        transferUtility.pause(downloadObserver.getId()) // Pause
 
        transferUtility.resume(downloadObserver.getId()) // Resume
```

The transfer Id is a unique identifier across all the transfers in the device.
