### ISSUE TITLE
Android upload file to AWS S3 error Status Code: 400

### ISSUE THREAD

**Issue by achinverma** [awslabs/aws-sdk-android-samples#23]
I am uploading a file to Amazon S3 server into my BUCKET i am getting error, i am using the code from github https://github.com/jgilfelt/android-simpl3r i will post my code: i have found some information here about my error but i don not know to solve this error https://github.com/jgilfelt/android-simpl3r/issues/4

Status Code: 400, AWS Service: Amazon S3, AWS Request ID: D49EFFBB39B49EEA, AWS Error Code: MalformedXML, AWS Error Message: The XML you provided was not well-formed or did not validate against our published schema, S3 Extended Request ID: fpAsdF+sxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=

**Comment by wdane** [comment]
Hi achinverma,

We do not support third party repositories or implementations.  If you can give a specific code example, using the AWS SDK that does not work, or produces this error then please let us know!  This area is specifically for issues with the AWS samples.  The SDK itself is hosted on https://github.com/aws/aws-sdk-android, where you can also post issues.  You can also contact us on our forum https://forums.aws.amazon.com/forum.jspa?forumID=88.

Thanks,
Weston

**Comment by achinverma** [comment]
ok thanks for your reply @wdane
