### ISSUE TITLE
Http Live Streaming Sample not Available

### ISSUE THREAD

**Issue by gerahimanshu** [awslabs/aws-sdk-android-samples#235]
Is there any documentation available regarding how to implement Http Live Streaming in an android app.
There are a lot of docs available which states that aws has feature for http live streaming but i am unable to find any implementation guide or code sample.
Do address if any android app sample available regarding the same.

**Comment by minbi** [comment]
Hi @gerahimanshu ,

We will look into adding this functionality into the KinesisVideo sample.

Code:
```
GetDataEndpointResult dataEndpoint = kinesisVideoClient.getDataEndpoint(new GetDataEndpointRequest()
        .withStreamName(streamName)
        .withAPIName(APIName.GET_HLS_STREAMING_SESSION_URL));

 final AWSKinesisVideoArchivedMediaClient kvamClient =
        new AWSKinesisVideoArchivedMediaClient(new CognitoCachingCredentialsProvider(*******));
 kvamClient.setEndpoint(dataEndpoint.getDataEndpoint());

try {
    final GetHLSStreamingSessionURLResult streamURL = kvamClient.getHLSStreamingSessionURL(
        new GetHLSStreamingSessionURLRequest()
            .withStreamName(streamName)
            .withPlaybackMode(PlaybackMode.LIVE)
    );
    // Use streamURL.getHLSStreamingSessionURL()
} catch (AmazonClientException e) {
    e.printStackTrace();
}
```

**Comment by gerahimanshu** [comment]
Thanks for this help! One more thing i want to do in my application is that i want to create multiple streams programatically along with keeping the video contents saved so that i can display and play the previous video contents anytime i want. What should be the best approach to do this?

**Comment by minbi** [comment]
If you wish to stream the contents at anytime, just increase the retention time in the console and then use `PlaybackMode.ON_DEMAND`. You may set the `HLSFragmentSelector` for timestamp selection.

**Comment by gerahimanshu** [comment]
Actually i have like multiple users to be created at runtime who will record the live video to be streamed to multiple devices. In my opinion i think i would require multiple streams to be created at run time for multiple users to make streams differentiable. How can this be possible? Please suggest me.

**Comment by minbi** [comment]
You may create multiple streams from each device or have a central location that assigns pre-created streams to each device.

**Comment by gerahimanshu** [comment]
How can creating multiple streams from each device be possible programatically for android? I also want the streamed videos to be stored somewhere for future viewing.

**Comment by dgaurav-163** [comment]
Hi AWS Team

One My Project Scope is fully dependent on Live Video Streaming. I have to create multiple channel where user can upload live video streaming and another end different user can view live streaming. I am talking about Live Streaming not On demand Video.

Now we got Sample code(AmazonKinesisVideoDemoApp). Via this code base I can start Live Video Streaming and able to see Live Streaming on AWS Console. Now we have to view this live video streaming at mobile device end.

Another point, I have to create multiple channel for this process.

Please provide consolidate solution so fullfill project requirement.

Thanks In Advance
Gaurav

**Comment by minbi** [comment]
@dgaurav-163 Please see my response for the code sample to stream

**Comment by gerahimanshu** [comment]
Hi @minbi , can you please let me know the dependency or code reference link for the above code that you have mentioned for android app. Actually i am unable to get some of the classes due to lack of dependency.
Thanks

**Comment by minbi** [comment]
Hi @gerahimanshu ,

You may add the following as a dependency:
```
implementation 'com.amazonaws:aws-android-sdk-kinesisvideo-archivedmedia:2.6.25'
```
To stay up to date with the SDK release see [CHANGELOG](https://github.com/aws/aws-sdk-android/blob/master/CHANGELOG.md)

**Comment by gerahimanshu** [comment]
@minbi Thank you so much for the help! This solved my problem for dependency. One more thing that is bothering me is:

GetDataEndpointResult dataEndpoint = kinesisVideoClient.getDataEndpoint(new GetDataEndpointRequest()
        .withStreamName(streamName)
        .withAPIName(APIName.GET_HLS_STREAMING_SESSION_URL));

In this line of code, where is this "kinesisVideoClient" coming from? I am unable to getDataEndPoint.
I have initialized the KinesisVideoClient class and used its instance for getting getDataEndPoint method, but there is no such method available in KinesisVideoClient class.
Thanks.

**Comment by gerahimanshu** [comment]
Any update on this? I have an urgent requirement of this and need to implement this as soon as possible.

**Comment by minbi** [comment]
That variable refers to `com.amazonaws.services.kinesisvideo.AWSKinesisVideoClient` class.
It is constructed in that same way as the `AWSKinesisVideoArchivedMediaClient` client.
```
final AWSKinesisVideoClient kinesisVideoClient =
        new AWSKinesisVideoClient(new CognitoCachingCredentialsProvider(*******));
```

**Comment by gerahimanshu** [comment]
Thank you for the help! It worked like a charm but i am getting an exception named ResourceNotForException:
"No fragments found in the stream for the HLS streaming request. (Service: AWSKinesisVideoArchivedMedia; Status Code: 404; Error Code: ResourceNotFoundException; Request ID: db3c8590-7a92-4fdd-88db-e7af561e6805)"
I am able to get the endpoint: https://b-647daf39.kinesisvideo.us-west-2.amazonaws.com
poolId: us-east-1:40a339fe-b0c9-4d6b-9529-64ab1b4189f9
region: us-east-1
and the stream name i am using is 100% correct, i am sure about it.
Please let me know where am i going wrong.
Thanks

**Comment by gerahimanshu** [comment]
Thanks a ton! It worked like a charm. I got the streamUrl. Can u please suggest me which player to be used to play it in? I am trying to play the url video into VLC player on my system but it isnt playing.

**Comment by gerahimanshu** [comment]
Can play the url.

**Comment by gerahimanshu** [comment]
Hi, i am using exo player to play the url and getting the following error while loading the url:
com.google.android.exoplayer.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalArgumentException: null
Please Help!

**Comment by MixMasterMitch** [comment]
@gerahimanshu I looks like you got ExoPlayer working for you based on https://github.com/awslabs/aws-sdk-android-samples/issues/240 Is that true? If so, what did you do to resolve your issue?

**Comment by muellerfr** [comment]
This issue has been closed because of inactivity. Please open a new issue in https://github.com/aws/aws-sdk-android/issues if you are still encountering problems.
