### ISSUE TITLE
S3 403 Permission Denied 

### ISSUE THREAD

**Issue by flexpeace** [awslabs/aws-sdk-android-samples#236]
I followed the steps found on this link https://github.com/awslabs/aws-sdk-android samples/tree/master/S3TransferUtilitySample. However, l keep getting 403 error.

Unless l go to s3 console, and then use the below before l am able to upload 
```
{
    "Version": "2012-10-17",
    "Id": "Policy1532856887763",
    "Statement": [
        {
            "Sid": "Access-to-specific-bucket-only",
            "Effect": "Allow",
            "Principal": "*",
            "Action": [
                "s3:GetObject",
                "s3:PutObject"
            ],
            "Resource": [
                "arn:aws:s3:::bucket",
                "arn:aws:s3:::bucket/*"
            ]
        }
    ]
}

```
However, l get a message that the bucket is public and is not advisable to do so? Is there a security risk for making the bucket public?

**Comment by desokroshan** [comment]
@flexpeace Can you please post the policy JSON which gives you 403 error

**Comment by cbommas** [comment]
@flexpeace 

I see that you are using a cognitoIdentity pool in your setup. In your scenario are you using "auth" or "unauth" role and do you have permissions setup to access the S3 bucket on those roles? In case you are not familiar with "auth" and "unauth" roles, here is a brief summary 

When you setup a Cognito Identity pool, it automatically creates 2 roles i.e., the "auth" and the "unauth" role. This is a convenience mechanism as many mobile apps have the notion of a signed-in user and anonymous user ( someone who hasn't yet signed in). At typical example would an ecommerce app that you can use to search and browse and only have to sign in to add to cart or make a purchase.

You can setup either the "auth" or the "unauth" or both roles (depending on your scenario) to have permissions on the bucket and that will enable you to access the buckets via the app. See https://docs.aws.amazon.com/aws-mobile/latest/developerguide/how-to-integrate-an-existing-bucket.html for more information.

**Comment by flexpeace** [comment]
Thanks a lot
