### ISSUE TITLE
Getting Could not find class errors after running the S3 sample app

### ISSUE THREAD

**Issue by flexpeace** [awslabs/aws-sdk-android-samples#237]
07-29 18:42:58.895 21678-21678 E/dalvikvm: Could not find class 'android.support.v4.app.JobIntentService$JobServiceEngineImpl', referenced from method android.support.v4.app.JobIntentService.onCreate

07-29 18:42:58.912 21678-21678/ E/dalvikvm: Could not find class 'com.amazonaws.mobile.auth.userpools.CognitoUserPoolsSignInProvider', referenced from method com.amazonaws.mobile.client.AWSMobileClient.registerConfigSignInProviders

07-29 18:42:58.912 21678-21678/ E/dalvikvm: Could not find class 'com.amazonaws.mobile.auth.facebook.FacebookSignInProvider', referenced from method com.amazonaws.mobile.client.AWSMobileClient.registerConfigSignInProviders

07-29 18:42:58.912 21678-21678/ E/dalvikvm: Could not find class 'com.amazonaws.mobile.auth.google.GoogleSignInProvider', referenced from method com.amazonaws.mobile.client.AWSMobileClient.registerConfigSignInProviders

07-29 18:42:58.913 21678-21678/ E/dalvikvm: Could not find class 'com.amazonaws.mobile.auth.facebook.FacebookSignInProvider', referenced from method com.amazonaws.mobile.client.AWSMobileClient.registerUserSignInProvidersWithPermissions

07-29 18:42:59.045 21678-21678/ E/dalvikvm: Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method android.support.v7.widget.AppCompatImageHelper.hasOverlappingRendering

**Comment by kvasukib** [comment]
Thank you @flexpeace for reporting to us. Sorry for the inconvenience caused. This error is due to the fact that your `awsconfiguration.json` file has an entry for `CognitoUserPools` but you don't have the required dependency for using Cognito UserPools. If you add the following dependency, you can recover from the exception:

```
// Cognito UserPools for SignIn
 implementation 'com.android.support:support-v4:24.+'
 implementation ('com.amazonaws:aws-android-sdk-auth-userpools:2.6.+@aar') { transitive = true }
```

Can you describe your use-case? If you are trying to add user signin to your app, you can follow the [documentation for Cognito UserPools in Android](https://docs.aws.amazon.com/cognito/latest/developerguide/tutorial-integrating-user-pools-android.html) to enable authentication to your app.

**Comment by flexpeace** [comment]
Thanks for your response. I only want to use S3 and CloudFront for uploading and downloading of files. I created a group in Iam, assigned s3 full access permission and created a user, added the user to the group. Also, granted list, put, delete Access policy in management console. However, I don’t know if it is safe for putting the Access Key and the secret key in the code to upload to S3? Or the cognito is the right and preferred way to access S3 resources? Because l have my own backend authentication and do not want to rely on Amazon authentication using cognito 
Also, which library should l use in build.gradle. I am currently using Android-sdk-s3:2.6.+ and Android-sdk-cognito:2.6.+

**Comment by kvasukib** [comment]
Thank you @flexpeace for the quick reply. Cognito is the preferred way for granting authorization to AWS resources. You can still use your own Identity Provider and federate it with Cognito to get short-lived AWSCredentials to access AWS resources like your S3 bucket.

You can create an Amazon Cognito Identity Pool and federate your user authenticated via your identity provider (https://docs.aws.amazon.com/cognito/latest/developerguide/developer-authenticated-identities.html and https://aws.amazon.com/blogs/mobile/understanding-amazon-cognito-authentication-part-2-developer-authenticated-identities/). 

Once you retrieve a JWT token from your Identity Provider, you can do the following:

```java
CognitoCachingCredentialsProvider credentialsProvider = new CognitoCachingCredentialsProvider(getApplicationContext(), "poolId", "aws-region");
Map<String, String> logins = new HashMap<String, String>();
// Set the facebook token in the logins map
logins.put("proivder-name-key", "JWT-Token"); 
// Add the new map we created to the Credentials Provider
credentialsProvider.withLogins(logins);

// Create AmazonS3Client based on the credentials provider
AmazonS3Client s3 = new AmazonS3Client(getApplicationContext(), credentialsProvider);
```

**Comment by flexpeace** [comment]
Great Response. Does that mean after following the steps above, l will not need to make my bucket public? and also l do not need to create a policy for the bucket as S3 console?

**Comment by kvasukib** [comment]
@flexpeace Sorry for the delayed response. You do not need to make the bucket public, however, you need to attach a policy that grants access to your S3 bucket, to the Authenticated/Unauthenticated role of the Cognito Identity pool. You can look at the sample app here: https://github.com/awslabs/aws-sdk-android-samples/tree/master/S3TransferUtilitySample which demonstrates the solution I described.

**Comment by kvasukib** [comment]
Thank you @flexpeace for the confirmation. Please let us know if you have any questions.
