### ISSUE TITLE
Need Multiple Live Stream From Mobile and View Live Stream In Mobile Device 

### ISSUE THREAD

**Issue by dgaurav-163** [awslabs/aws-sdk-android-samples#238]
Hi AWS Team

One My Project Scope is fully dependent on Live Video Streaming. I have to create multiple channel where user can upload live video streaming and another end different user can view live streaming. I am talking about Live Streaming not On demand Video.

Now we got Sample code(AmazonKinesisVideoDemoApp). Via this code base I can start Live Video Streaming and able to see Live Streaming on AWS Console. **Now we have to view this live video streaming at mobile device end**. 

Another point, I have to create multiple channel for this process.

Please provide consolidate solution so fullfill project requirement.

Thanks In Advance
Gaurav

**Comment by minbi** [comment]
Please see #235
