### ISSUE TITLE
not being able to resume an upload. Starts uploading from the beginning.

### ISSUE THREAD

**Issue by bpr10** [awslabs/aws-sdk-android-samples#24]
I'm trying to upload a 55Mb video file. every time i pause the video the next time i try to resume it it starts from the beginning. I am not getting any pause exception while pausing the video and some data is being stored in the persistableupload . But still the upload stars from the beginning. In your sample app also the file upload doesn't resume .It starts from the beginning .Any suggestions regarding this .

**Comment by bpr10** [comment]
I was using this constructor to get the s3Cliient reference 

new CognitoCachingCredentialsProvider(context, unique pool id , region)
	 
and the upload was not resuming 
then i used the constructor  specified in the developer guide and was able to pause and resume upload. Kind of weird as both the constructor should behave cohesively.

**Comment by dipen-solulab** [comment]
@bpr10 I facing the same issue. How you managed to solve this? Can you provide me the code snippet which works for you?
