### ISSUE TITLE
Unable to play Kinesis Video Stream Url in an android app

### ISSUE THREAD

**Issue by kumarketan75** [awslabs/aws-sdk-android-samples#240]
Hi,
I have a requirement of project which needs live streaming to be done at android device end.
I have reached till streaming the video on amazon console end and getting the video stream url at android end. But i am unable to play the url in any player. Please help me play the url.
Thanks.

**Comment by gerahimanshu** [comment]
You can use Exo Player for playing the url in an android device. It works fine!

**Comment by MixMasterMitch** [comment]
@kumarketan75 Did you try using ExoPlayer? When you say that you are unable to play the url in any player, what player(s) did you try? Where there any specific errors?

**Comment by muellerfr** [comment]
This issue has been closed because of inactivity. Please open a new issue in https://github.com/aws/aws-sdk-android/issues if you are still encountering problems.
