### ISSUE TITLE
Storing the kinesis video stream recordings

### ISSUE THREAD

**Issue by gerahimanshu** [awslabs/aws-sdk-android-samples#244]
Hi,
As per my requirement, I want to save all the recordings being streamed into a video stream.
Also I want to show them in my android application and play them whenever i want. What should be the best approach to achieve this.
Please Help!
Thanks!

**Comment by cbommas** [comment]
@gerahimanshu 

I believe this is what you are looking for. The `getHLSStreamingSessionURL` method
retrieves an HTTP Live Streaming (HLS) URL for the stream that you previously uploaded to Kinesis. The URL can be opened in a browser or media player to view the stream contents.  
See  https://aws.github.io/aws-sdk-android/docs/reference/com/amazonaws/services/kinesisvideoarchivedmedia/AWSKinesisVideoArchivedMediaClient.html for more details.

**Comment by gerahimanshu** [comment]
I think getHLSStreamingSessionURL is giving me the present video stream url which is being streamed. I want all the videos which has been streamed to a particular stream till now.

**Comment by cbommas** [comment]
@gerahimanshu 
AWS Kinesis stores the videos you stream on S3 and this feature is available for both live playback as well as replaying archived videos. Please see the Live and On-Demand playback section on this page for further details - https://aws.amazon.com/kinesis/video-streams/features/

**Comment by gerahimanshu** [comment]
How can this be achieved programatically in android side? I want to display all the previous recordings and play on click.

**Comment by MixMasterMitch** [comment]
@gerahimanshu 
You can use the ListFragments API to determine what content is in a KVS stream. It will not tell you the exact clips in the stream or provide a thumbnail or anything like that, but it is the mechanism for determining what content is in a stream.

The GetHLSStreamingSessionURL API does provide the ability to specify a PlaybackMode of on-demand playback and a FragmentSelector for choosing a specific time range.
