### ISSUE TITLE
Facebook login: CognitoSyncClientManager not initialized yet

### ISSUE THREAD

**Issue by JustonJ99** [awslabs/aws-sdk-android-samples#247]
Hi, I have installed the sample code and follow the instruction to run the application. My issue is after I logged into the Facebook account and relaunch the application, it will be crashed. Thank you.

 Caused by: java.lang.IllegalStateException: CognitoSyncClientManager not initialized yet
        at com.amazonaws.demo.CognitoSyncClientManager.addLogins(CognitoSyncClientManager.java:88)
        at com.amazonaws.demo.MainActivity.setFacebookSession(MainActivity.java:318)
        at com.amazonaws.demo.MainActivity.onCreate(MainActivity.java:108)

**Comment by undefobj** [comment]
@JustonJ99 are you looking for state synchronization across devices? The latest guidance from the Cognito team is to use AWS AppSync instead. From the [Cognito Sync Documentation](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-sync.html):

> If you're new to Amazon Cognito Sync, use AWS AppSync. Like Amazon Cognito Sync, AWS AppSync is a service for synchronizing application data across devices.
> 
> It enables user data like app preferences or game state to be synchronized. It also extends these capabilities by allowing multiple users to synchronize and collaborate in real time on shared data.

AWS AppSync [documentation is here](https://docs.aws.amazon.com/appsync/latest/devguide/building-a-client-app.html).

You can find specific blogs on this use case [for iOS](https://aws.amazon.com/blogs/mobile/user-settings-sync-for-ios-with-aws-appsync/) and [for Android](https://aws.amazon.com/blogs/mobile/user-settings-sync-for-android-with-aws-appsync/).

**Comment by muellerfr** [comment]
This issue has been closed because of inactivity. Please open a new issue in https://github.com/aws/aws-sdk-android/issues if you are still encountering problems.
