### ISSUE TITLE
TransferUtility get URL

### ISSUE THREAD

**Issue by Glennmen** [awslabs/aws-sdk-android-samples#248]
I have been looking through the sample and available docs but I can't seem to find how you can get the URL of the file after uploading it to the S3 bucket.

Use case:
I want to upload a file/pdf to S3 (and make it public)
After that I want to get the public url of the file on S3 so I can share it

**Comment by kvasukib** [comment]
@Glennmen Thank you for reporting to us. The `TransferUtility#upload` method uses the `PutObjectRequest` to perform an upload. It doesn't return an URL. However, you can generate a pre-signed URL using our SDK which you can then share it until the URL is expired.

See https://github.com/aws/aws-sdk-android/blob/1d492dc7d8ad37a14596ddc337ba1a0733ec1182/aws-android-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3Client.java#L3192 for details.

**Comment by Glennmen** [comment]
@kvasukib Thanks for your reply, so if I understand correctly (I haven't found any clear docs about all the SDK functions), first use `TransferUtility#upload` to upload the file to S3 and then use the `generatePresignedUrl()` function to generate a pre-signed URL.

Will have to experiment with it once I start implementing it into the app, not sure if we are going to at this point. I saw it as a possible feature in our next meeting topic and decided to do some research first.

**Comment by rohandubal** [comment]
If you want to make the file public, you might want to consider 1 of the two options:

- Make the file accessible to everyone who has AWS Credentials

or

- Make the file accessible to everyone without any credentials (For this case, you will have to use some API to update ACL on the file)

Thanks,
Rohan
