### ISSUE TITLE
[Android]pack the KEYSTORE file as part of the APK

### ISSUE THREAD

**Issue by arunkk-git** [awslabs/aws-sdk-android-samples#249]
AWS androidIoT : Publish/Subscribe sample

Where to keep the "KEYSTORE_PATH" file while building the APK.

I have tried in asset/aws/iot_keystore_aws folder, but unable to the get the folder path from AssetManager.

Sample example has the path of : KEYSTORE_PATH = context?.getFilesDir()!!.getPath()

Here the gitHub :https://github.com/awslabs/aws-sdk-android-samples/tree/master/AndroidPubSub

I'm following the Using an off-device keystore

Steps 1:Import certificate and private key into PKCS12 keystore.
Steps 2:Convert PKCS12 keystore to a BKS (BouncyCastle) keystore.
Steps 3: List aliases in keystore to verify (optional).
Steps 4:Push to Android Emulator (optional).
 adb push <keystore name>.bks /data/user/0/your_app_dir_goes_here/files/<keystore name>
 
Note :  App is working perfectly , but how to pack the KEYSTRORE file as part of the APK

**Comment by desokroshan** [comment]
This issue is being tracked in aws-sdk-android repo [Issue#549](https://github.com/aws/aws-sdk-android/issues/549).
