### ISSUE TITLE
Error in signature salt generation

### ISSUE THREAD

**Issue by chuihinwai** [awslabs/aws-sdk-android-samples#25]
"this.endpoint" should use the host name instead.
```
String salt = this.username + this.appName + this.endpoint;
```
[LoginRequest.java (line 781)](https://github.com/awslabs/aws-sdk-android-samples/blob/master/CognitoSyncDemo/src/com/amazonaws/cognito/sync/devauth/client/LoginRequest.java#L81)

Reference to the correct signature generation on iOS: 
```
NSURL *URL = [NSURL URLWithString:self.endpoint];
NSString *hostname = URL.host;
NSString *salt = [NSString stringWithFormat:@"%@%@%@", username, self.appname, hostname];
```
[DeveloperAuthenticationClient.m (line 221)](https://github.com/awslabs/aws-sdk-ios-samples/blob/master/CognitoSync-Sample/Objective-C/CognitoSyncDemo/DeveloperAuthenticated/DeveloperAuthenticationClient.m#L221)

**Comment by fosterzhang** [comment]
Thanks for reporting. We will work on it ASAP.

**Comment by rachitdhall** [comment]
In the [AmazonCognitoSampleDeveloperAuthenticationClient](https://github.com/awslabs/aws-sdk-android-samples/blob/master/CognitoSyncDemo/src/com/amazonaws/cognito/sync/devauth/client/AmazonCognitoSampleDeveloperAuthenticationClient.java) class, the endpoint is stripped down to the domain name before being used by the LoginRequest class. I do agree that the variable naming can be changed here to make it more readable and understandable. Are you having any issues in running the sample?

**Comment by chuihinwai** [comment]
The salt generation would be wrong if the end point contains any additional paths, such as "http://github.com/v1". The stripped endpoint field becomes the erroneous "github.com/v1" rather than "github.com". Note that the endpoint field would still need to contain the paths for the request, but only the host name should be used for salt generation.

**Comment by rachitdhall** [comment]
We will update this shortly, thanks for pointing it out.

**Comment by albertvaka** [comment]
It should be fixed in the last commit, sorry for the delay.

Thanks for reporting this problem and please let us know if you still have some issue.

**Comment by angelromero** [comment]
Hi
I have a question, the Android client sends the timestamp to the login endpoint.
the login endpoint validates if the result of signing that timestamp with the user's salted password matches the signature sent by the android client.
Is that correct?
Is the validateSignature in login correct?
