### ISSUE TITLE
Wrong video orientation in Kinesis Stream

### ISSUE THREAD

**Issue by gerahimanshu** [awslabs/aws-sdk-android-samples#251]
Hi, 
I am using Kinesis Video for live as well as on demand video playback in an android application. One thing i am stuck on now is getting wrong orientation while playing the video url.
AndroidCameraMediaSourceConfiguration.builder()
                        .withCameraId(String.valueOf(cameraId))
                        .withEncodingMimeType("video/avc")
                        .withHorizontalResolution(320)
                        .withVerticalResolution(240)
                        .withCameraFacing(1)
                        .withIsEncoderHardwareAccelerated(true)
                        .withFrameRate(FRAMERATE_20)
                        .withRetentionPeriodInHours(RETENTION_PERIOD_48_HOURS)
                        .withEncodingBitRate(BITRATE_384_KBPS)
                        .withCameraOrientation(0)
                        .withNalAdaptationFlags(StreamInfo.NalAdaptationFlags.NAL_ADAPTATION_ANNEXB_CPD_AND_FRAME_NALS)
                        .withIsAbsoluteTimecode(false));

Above is the configuration for media. Please help!

**Comment by gerahimanshu** [comment]
If anyone know the solution for this, please help! I have been stuck on this since a long time now.

**Comment by desokroshan** [comment]
Hi @gerahimanshu,
We're tracking this request with issue [aws/aws-sdk-android#544](https://github.com/aws/aws-sdk-android/issues/544).
