### ISSUE TITLE
[Android] Key param URLEndcode

### ISSUE THREAD

**Issue by GianhTran** [awslabs/aws-sdk-android-samples#258]
Refer document: https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html
When I using `+` character in my key param, I should using URL encoded or referenced as HEX, but I face some issues:
+ When I using the first solution, that is using  URL encoded as below:
 `val key = URLEncoder.encode("+mykey", "UTF-8")`
I have a error:

> Error initiating multipart upload: 181 due to Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 51D42F809CB0D831)
>     com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 51D42F809CB0D831), S3 Extended Request ID: BvH+82tjDqFC02kRFJKxtsWMEEB3V12QTkCINYzDVQ3SxUhEEFFYKyfFAFYsgUPEwlAwimwtB/M=

+ When I using second solution, that is using referenced as HEX as below
`val key = "%2Bmykey"`
then I will get `%252Bmykey`

My expected: I can get `+mykey` after I upload my video to S3.

**Comment by kvasukib** [comment]
@GianhTran Thank you for reporting to us. What do you mean by 'first' and 'second' solution? What version of SDK are you using?

**Comment by GianhTran** [comment]
@kvasukib hi, the SDK version is  '2.7.4',
- the first solution: using URL encoded
- second solution: using referenced as HEX

**Comment by kvasukib** [comment]
@GianhTran Thank you for the response. The SDK handles the following characters: https://github.com/aws/aws-sdk-android/blob/master/aws-android-sdk-s3/src/main/java/com/amazonaws/services/s3/internal/S3HttpUtils.java#L76

For characters besides these, you have to do special handling before passing it to the SDK.

**Comment by muellerfr** [comment]
This issue has been closed because of inactivity. Please open a new issue in https://github.com/aws/aws-sdk-android/issues if you are still encountering problems.
