### ISSUE TITLE
Unable to verify integrity of data upload

### ISSUE THREAD

**Issue by rameshmkll** [awslabs/aws-sdk-android-samples#259]
Hi 
iam getting the below error while uploading image.
com.amazonaws.demo.s3transferutility E/UploadTask: Error encountered during multi-part upload: 8 due to Unable to verify integrity of data upload.  Client calculated content hash didn't match hash calculated by Amazon S3.  You may need to delete the data stored in Amazon S3. com.amazonaws.AmazonClientException: Unable to verify integrity of data upload.  Client calculated content hash didn't match hash calculated by Amazon S3.  You may need to delete the data stored in Amazon S3.

**Comment by kvasukib** [comment]
@rameshmkll Thank you for reporting to us. What version of SDK and Android are you using? What is the size and type of the file?

**Comment by muellerfr** [comment]
This issue has been closed because of inactivity. Please open a new issue in https://github.com/aws/aws-sdk-android/issues if you are still encountering problems.
