### ISSUE TITLE
Upload throwing Access Denied

### ISSUE THREAD

**Issue by bsrikanth88** [awslabs/aws-sdk-android-samples#261]
Hi I followed the S3TransferUtilitySample to upload the sample. But it is throwing com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID:------.

I integrated the same in IOS app also. their it is working fine. I am using the same POOL_ID, BUCKET_REGION and BUCKET_NAME for android also.

Could you guys help me on this.

**Comment by desokroshan** [comment]
This issue is being tracked in aws-sdk-android repo [Issue#548](https://github.com/aws/aws-sdk-android/issues/548). Please update that thread if you have any comments. Closing this issue.
