### ISSUE TITLE
Single Device login

### ISSUE THREAD

**Issue by ali-mehmood-10p** [awslabs/aws-sdk-android-samples#270]
Is it possible to restrict a single device login, if a user logs in from another device, can we invoke the previously granted access/refresh tokens? If yes, please advise.

**Comment by kvasukib** [comment]
@ali-mehmood-10p Thank you for reporting to us. Can you open an issue with the `Usage Question` template in https://github.com/aws-amplify/aws-sdk-android repository and provide the required details? We can discuss in the issue that you will be creating in the https://github.com/aws-amplify/aws-sdk-android repository. Thanks!

**Comment by muellerfr** [comment]
Let's track the issue here: https://github.com/aws-amplify/aws-sdk-android/issues/585
