### ISSUE TITLE
Facebook SDK 4.XX

### ISSUE THREAD

**Issue by Aggiemaster** [awslabs/aws-sdk-android-samples#29]
There were changes in the facebook sdk since the version used in the CognitoSyncDemo (3.20).  Will the samples be update for the latest facebook SDK (4.5.1)?  

ex.  com.facebook.Request is now com.facebook.GraphRequest (src file:  com.amazonaws.cognito.sync.demo.MainActivity.java)

**Comment by wdane** [comment]
Thanks for reporting this.  We will definitely update our samples soon!  Will leave this issue open until we have pushed changes.

**Comment by wdane** [comment]
Late in closing, but we upgraded to the latest FB SDK ages ago (see the Gradle file in the sync demo)
