### ISSUE TITLE
TransferUtility class does not have permission setting option for uploaded file.

### ISSUE THREAD

**Issue by aks0020** [awslabs/aws-sdk-android-samples#30]
new `TransferUtility` class does not have `upload()` constructor which support `PutObjectRequest` so that I can set public read permission to the uploaded file.

There is only one upload method `upload(bucket, path, file)` which don't have any file permission setting.

**Comment by wdane** [comment]
Hi aks,

What exactly do you mean about file permissions?  Do you mean access permissions for the object on S3?  If so have you considered looking at bucket permissions or the IAM role associated with the Cognito Identity Pool if you are using one?

Thanks,
Weston

**Comment by aks0020** [comment]
I am not talking about bucket permissions, I am taking about individual upload file permission using `CannedAccessControlList` using new `TransferUtility` class.
It was possible using old `TransferManager` class but it is now deprecated. @wdane

**Comment by wdane** [comment]
@aks0020 You can probably use IAM policies to accomplish the same task.  If you look at http://blogs.aws.amazon.com/security/post/TxPOJBY6FE360K/IAM-policies-and-Bucket-Policies-and-ACLs-Oh-My-Controlling-Access-to-S3-Resource you can see how you could get up an IAM policy to either set a specific bucket as global read (or whatever you'd like to do) or use a specific bucket key pre-fix to do the same.  For example myBucket/global/read/YOUR_OBJECTS

Let me know if this doesn't work for you or is giving you trouble.

Weston

**Comment by wdane** [comment]
Closing for now, feel free to re-open if needed.
