### ISSUE TITLE
Amazon S3 provide Unable to resolve host "s3-ap-southeast-1.amazonaws.com"  while pause and resume

### ISSUE THREAD

**Issue by jitendraramoliya** [awslabs/aws-sdk-android-samples#32]
I am trying to resume and  pause download and getting this error.

Unable to execute HTTP request: Unable to resolve host "s3-ap-southeast-1.amazonaws.com": No address associated with hostname
Exception is:
Caused by: libcore.io.GaiException: getaddrinfo failed: EAI_NODATA (No address associated with hostname)
            at libcore.io.Posix.getaddrinfo(Native Method)

I have checked all internet permission and connection in device. thats all are working.
Could any one provide me solution on this? Why I am getting this error.

**Comment by fosterzhang** [comment]
This is usually caused by network connection of the device. I saw a similar issue on StackOverflow http://stackoverflow.com/questions/9475024/httpresponse-using-android-issue-execute-always-causes-exception. Would you please double check the network?

**Comment by fosterzhang** [comment]
This is usually a network issue. Closing it as it's unrelated to the AWS Android SDK or the sample.
