### ISSUE TITLE
CognitoSyncDemo - Register user

### ISSUE THREAD

**Issue by Jespervj** [awslabs/aws-sdk-android-samples#37]
I've followed the tutorial on how to autheunticate users with beanstalk, but when i try to log in with a user i get recieve the "Username or password do not match!!" which i obvious because i have registered no users og devices. My question is how do i register the users with a simple username and password?

**Comment by chetanme** [comment]
You can follow the README guide to setup [sample server side](https://github.com/awslabs/amazon-cognito-developer-authentication-sample) application. Go to the register url of your EBS application and create a new user.

After this, follow the instruction to configure [Cognito Sync Demo](https://github.com/awslabs/aws-sdk-android-samples/tree/master/CognitoSyncDemo) application to use developer authenticated identities. All these instructions are in the sample's README.

When you run the sample app, you will be able to login using the registered username and password.

**Comment by Jespervj** [comment]
Hi
Thanks for the reply.
I was able to get to the register page through my browser, and i tried to register a user. The register url sais that it registers the user, but i am not able to see this in my identity pool, so my app still cant find the user

**Comment by chetanme** [comment]
The users are never created in the identity pool. Identity pool is the management entity for your user identities once they authenticate and get a Cognito identity.

When you register a user in the sample server application, the users are stored in a a DynamoDB table, named *AWSCognitoDeveloperAuthenticationSample_(your app name)_USERS*, in you account. You can see your registered users there.

**Comment by Jespervj** [comment]
Thank you. Made it work.
I am now able to sign in if i have a user registered via a browser.
Now i only need to implement a registration activity in my app. Is there i way to make my app commmunicate with the registration url?

**Comment by chetanme** [comment]
We don't have any sample code for this but you can explore [WebView Layout](http://developer.android.com/guide/webapps/webview.html) in android to do this.

I must also warn you, the server is a sample application. If you are building this app for production use, I would recommend you to consider your scaling and other requirements and modify this application accordingly.

**Comment by Jespervj** [comment]
Okay. Thank you for the help.
Do you think it would be a better choice registering and storing users in postgresql for production prupose?

**Comment by chetanme** [comment]
It really depends on your requirements. I would recommend discussing this on other open forums with details of your use case.
