### ISSUE TITLE
Secure way to store and use Amazon Access key and Secret Key for Android in Image uploading

### ISSUE THREAD

**Issue by achinverma** [awslabs/aws-sdk-android-samples#38]
hi , I am using aws sdk to upload image on s3 server , it is running fine but i don't want to store Access key and Secret Key  in my code , 
is there any other solution or demo to Authentication the user ?
i have read about IAM Roles to Grant Access in aws ,http://docs.aws.amazon.com/AWSSdkDocsJava/latest/DeveloperGuide/java-dg-roles.html  but i did not able to find any demo , i mean how to use this ?
or is there any way to get Temporary Credentials ?
http://docs.aws.amazon.com/AWSSdkDocsJava/latest/DeveloperGuide/prog-services-sts.html
please anyone guide me?

**Comment by yosuke-matsuda** [comment]
[Amazon Cognito Identity](http://docs.aws.amazon.com/mobile/sdkforandroid/developerguide/cognito-auth.html) is the recommended way to manage the credentials with limited permissions securely. See [Amazon Cognito Developer Guide](https://docs.aws.amazon.com/cognito/devguide/identity/) for more details.

**Comment by fuji8bit** [comment]
You can have the user of your application log in using Login with Amazon or
Social Media Identity Providers, then use the Cognito Identity Service to
get temporary, scoped credentials. You can even get credentials for an
anonymous user with Cognito (no login required).  You would then create and
assign Roles to the Cognito Identity Pool you're using  (roles contain
permissions, called Policies).  This way, you don't need to store
credentials in your application -- they can reside in memory until they
expire.  I suggest using the Cognito Samples and try it out.

**Comment by achinverma** [comment]
Hi @fuji8bit , i have read about Cognito Identity Service to
get temporary, scoped credentials, but for this I need Identity Pool Id, and region , but i am facing one issue with this while creating new Identity Pool Id. Identity Pool Id is not available for my Region . now what should i do? please guide me.

**Comment by wdane** [comment]
Your best option is to create an Identity Pool in the region closest to your users, and then use that pool.  It is okay if the Identity Pool is not located in the same region as the other AWS services you are trying to access with it's credentials.

**Comment by fuji8bit** [comment]
Yes, use cognito-identity endpoint that is closest to your region.  It has
public, non-authenticated endpoints for the cognito API calls you should be
using.  Cognito Sync is a different story, but it sounds like you're not
using that yet.

**Comment by fosterzhang** [comment]
@fuji8bit answered the question. Closing this.
