### ISSUE TITLE
Continuing upload after killing the app

### ISSUE THREAD

**Issue by ckarthikv** [awslabs/aws-sdk-android-samples#42]
TransferObserver currently uses a service implementation, but on killing the app it stops upload immediately.

Is it possible to continue/ restart upload in the background using sticky services or foreground services inspite of the app being killed?

**Comment by fosterzhang** [comment]
TransferUtility continues to transfer when app goes to background. However, if the app is killed by user or system, it's better to stop all transfers. TransferUtility and its service aren't designed to run out side of an application. As a matter of fact, they have many bonds with the application: SQLite database, transfer listeners, and SharedPreferences. If the application is killed, the service will lose some critical information to continue any transfer. Therefore, it's unlikely at the moment.

**Comment by ckarthikv** [comment]
Thanks for the information.
