### ISSUE TITLE
Skd path is different from what the demo shows .

### ISSUE THREAD

**Issue by ishandutta2007** [awslabs/aws-sdk-android-samples#45]
Can't find package paths like this?
com.amazon.identity.auth.device.authorization.api.*;
My aws-android-sdk-core jar has directory structure like this:
com.amazonaws.auth.*;

**Comment by fosterzhang** [comment]
Which sample are you referring to? Generally, the package belongs to Login with Amazon. You can get the library here http://login.amazon.com/android.
