### ISSUE TITLE
S3TransferUtilitySample - Make public an uploaded file from Android

### ISSUE THREAD

**Issue by matamicen** [awslabs/aws-sdk-android-samples#46]
Hi everybody!

Thanks for the excellent sample! it worked great!

Does anybody has an example that let me put the uploaded file in a public state in order to get access from an url? 

Thanks!

**Comment by fosterzhang** [comment]
There are a couple of ways to do it.
- changes the ACL of the object via [AmazonS3.setObjectAcl(String, String, AccessControlList)](http://docs.aws.amazon.com/AWSAndroidSDK/latest/javadoc/com/amazonaws/services/s3/AmazonS3.html#setObjectAcl(java.lang.String,%20java.lang.String,%20com.amazonaws.services.s3.model.AccessControlList)). This requires an additional network request after the object is uploaded. See [Managing Access with ACLs](http://docs.aws.amazon.com/AmazonS3/latest/dev/S3_ACLs_UsingACLs.html) for more information.
- manages the bucket policy. See [Using Bucket Policies and User Policies](http://docs.aws.amazon.com/AmazonS3/latest/dev/using-iam-policies.html) and [Bucket Policy Examples](http://docs.aws.amazon.com/AmazonS3/latest/dev/example-bucket-policies.html).

**Comment by matamicen** [comment]
Thanks fosterzhang! it worked inmediately with:
 manages the bucket policy. See Using Bucket Policies and User Policies and Bucket Policy Examples.

thanks!

**Comment by matamicen** [comment]
This issue is closed. thanks.
