### ISSUE TITLE
android S3 upload issue.

### ISSUE THREAD

**Issue by prakashr87** [awslabs/aws-sdk-android-samples#49]
Hi,
We are using android S3 upload with cognito in our project. While uploading a file, once after it has reached 100% upload, bytes transferred exceeds total bytes and total percentage exceeds 100%, Upload never completed, once we stopped and started again, it uploaded properly. 

This issue occurs even in android aws s3 sample latest project not only in our project. we have given the output and attachment from android aws s3 sample application (latest sample used) for yor refernce.

We have used the following ANDROID SDK'S versions in our project as below,
        minSdkVersion="14"
        targetSdkVersion="23" 		

Tested android OS
======================
Lollypop, Kitkat & Jellybean

We have tested the following AWS Mobile SDK versions for Android in our project but we are getting the same issue.

SDK Tested
=========	
	aws-android-sdk-core-2.2.13
    aws-android-sdk-s3-2.2.13
	aws-android-sdk-core-2.2.14	
	aws-android-sdk-s3-2.2.14 

Output
======
        Uploading file bytesCurrent exceeded from bytesTotal.
		 total: 17914286, current: 16300462
		 total: 17914286, current: 16447918
		 total: 17914286, current: 16562606
		 total: 17914286, current: 16808366
		 total: 17914286, current: 16931246
		 total: 17914286, current: 17283502
		 total: 17914286, current: 17430958
		 total: 17914286, current: 17545646
		 total: 17914286, current: 17914286 - Reached the max size
		 total: 17914286, current: 18028974
		 total: 17914286, current: 18258350
		 total: 17914286, current: 18479534
		 total: 17914286, current: 18725294
		 total: 17914286, current: 18749870
		 total: 17914286, current: 18889134
		 total: 17914286, current: 19118510
		 total: 17914286, current: 19356078
		 total: 17914286, current: 19470766
		 total: 17914286, current: 19732910
		 total: 17914286, current: 20085166
		 total: 17914286, current: 20191662
		 total: 17914286, current: 20543918
		 total: 17914286, current: 20715950
		 total: 17914286, current: 21068206
		 total: 17914286, current: 21420462
		 total: 17914286, current: 21780910
		 total: 17914286, current: 22034862 

I have attached the screenshot of those files below,
![screenshot_2016-04-08-19-10-19](https://cloud.githubusercontent.com/assets/13495522/14638675/116e8336-0656-11e6-9f71-ba43753d1f58.png)
![screenshot_2016-04-08-19-35-00](https://cloud.githubusercontent.com/assets/13495522/14638676/1171bdd0-0656-11e6-9116-2e115dfa79cd.png)
![screenshot_2016-04-12-12-18-50](https://cloud.githubusercontent.com/assets/13495522/14638677/1173966e-0656-11e6-8273-46c3c6a15228.png)
![screenshot_2016-04-12-17-02-24](https://cloud.githubusercontent.com/assets/13495522/14638678/11777248-0656-11e6-8bcb-63c551a47ec5.png)
![screenshot_2016-04-12-17-50-34](https://cloud.githubusercontent.com/assets/13495522/14638679/11799be0-0656-11e6-9592-40c26eee4419.png)
![screenshot_2016-04-16-17-54-22](https://cloud.githubusercontent.com/assets/13495522/14638680/1180a20a-0656-11e6-8de1-3394a39b68de.png)
![screenshot_2016-04-08-19-10-19](https://cloud.githubusercontent.com/assets/13495522/14638721/4dd1919c-0656-11e6-9a8c-f870538c74b8.png)

**Comment by fosterzhang** [comment]
@prakashr87 Thanks for the detailed information. A few questions
- does it happen often?
- in which S3 region?
- will the upload complete eventually?

**Comment by prakashr87** [comment]
@fosterzhang Thanks for the reply, kindly refer below answers.

1. does it happen often?
Failure upto 30% of the uploads (i.e. 3/10 files failure, but it happens randomly). Same file will upload in 2nd or 3rd try.

2. in which S3 region?
US Standard

3. will the upload complete eventually?
It tooks more time (ex: 1 hour) for 10 MB file once, then still progressing, we did pause and resume then it started with 61% and went complete on 100%

**Comment by fosterzhang** [comment]
@prakashr87 what's your network status? I suspect some network issue causes the transfer to retry and the progress listener doesn't update correspondingly. When you pause and resume, the progress is recalculated.

**Comment by jinguoliang** [comment]
I have the same question in some time.

**Comment by fosterzhang** [comment]
@jinguoliang This is a notorious bug to fix. I'll put it in our backlog.

**Comment by jinguoliang** [comment]
Well, I hope make some contribution，what can I do？

**Comment by fosterzhang** [comment]
@jinguoliang This is fixed in v2.2.19 release.

**Comment by syam82** [comment]
Where can i find this v2.2.19?
I am also facing same issue but only in marshmallow  HTC M9.

**Comment by syam82** [comment]
Finally i found the latest version v2.2.19. 
But I tried "S3TransferUtilitySample" It is asking "COGNITO_POOL_ID" for authenticating unfortunately my region not supported for COGNITO. What i need to do?Is there any alternative?

**Comment by fosterzhang** [comment]
@syam82 Cognito isn't available in all regions. However, you don't have to use the same region as your service. For example, you can use Cognito in us-east-1 and S3 in ap-southeast-1. Please open another issue if you have other questions.
