### ISSUE TITLE
How is MainActicity.signInUser verifying the password? (In AmazonCognitoUserPoolsDemo)

### ISSUE THREAD

**Issue by iant2** [awslabs/aws-sdk-android-samples#53]
Sorry if this is the wrong place to put this but im pretty stumped here. 

inside:
AmazonCognitoYourUserPoolsDemo/app/src/main/java/com/amazonaws/youruserpools/MainActivity.java
Lines 249 - 269
In the method signInUser, i cant figure out how or where the users password is verified. I understand the user has been confirmed in the backend, but how does it know if i typed the password correctly?

**Comment by chetanme** [comment]
This method uses our SDK's [authenticate method](https://github.com/aws/aws-sdk-android/blob/master/aws-android-sdk-cognitoidentityprovider/src/main/java/com/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUser.java#L662) in background to call our service.

Our service is based off SRP 6a protocol which requires both the client and server to follow the algorithm to calculate the verifiers for a password and then comparing them on the service side to determine if the password entered at the client end was a valid password or not. This is a very high level explanation of what we do. You can read more about our service [here](http://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools.html) and about SRP 6a [here](http://srp.stanford.edu/design.html).
