### ISSUE TITLE
Sign-in does work in AVD but not on Samsung GT-I9295 

### ISSUE THREAD

**Issue by jonasze** [awslabs/aws-sdk-android-samples#54]
Hi,
thanks for the android samples, they are very helpful! 
But when using the AmazonCognitoYourUserPoolsDemo I ran into a strange problem: Everything works fine on an AVD (Nexus 5X API 23), but when I try to run the demo on my phone (Samsung GT-I9295 (API 21)) I always get the Sign-in failed message. 
This was also true if I hardcoded username/password into the source code.
What is going wrong?

**Comment by behrooziAWS** [comment]
Is the locale of your phone something other than English?  If so, there is a locale related bug with the SDK that will be fixed in the next release.

**Comment by jonasze** [comment]
Thanks for the quick reply!
Yes the local of the phone is Germany. When will be the next release be available?

**Comment by mreddyg** [comment]
We are working towards making the new version available with-in the next few weeks. As a temporary fix, you can change the default locale in your app to Locale.US, before authenticating (Locale.setDefault(Locale.US)).

**Comment by fosterzhang** [comment]
This is fixed in v2.2.17 release. Please update to the latest version.
