### ISSUE TITLE
Error in getting and updating aws IoT shadow 

### ISSUE THREAD

**Issue by Prashant-Kmr** [awslabs/aws-sdk-android-samples#55]
I want to get the status of LED and update the shadow state of LED from android app I referred temperature control example for building android app but getting error like, 
"05-24 14:51:33.854: I/com.amazonaws.demo.temperaturecontrol.TemperatureActivity(31175): New setpoint:0
05-24 14:51:33.854: I/com.amazonaws.demo.temperaturecontrol.TemperatureActivity(31175): {{"desired":{"led":0}}}
05-24 14:51:33.854: I/com.amazonaws.demo.temperaturecontrol.TemperatureActivity(31175): UpdateShadowTask Thing:Led2
05-24 14:51:33.864: D/CognitoCachingCredentialsProvider(31175): Loading credentials from SharedPreferences
05-24 14:51:33.864: D/CognitoCachingCredentialsProvider(31175): No valid credentials found in SharedPreferences
05-24 14:51:34.124: E/com.amazonaws.demo.temperaturecontrol.TemperatureActivity.UpdateShadowTask(31175): updateShadowTask
05-24 14:51:34.124: E/com.amazonaws.demo.temperaturecontrol.TemperatureActivity.UpdateShadowTask(31175): Error in Update Shadow"

What might be the problem? I'm using Marvell MW302 IoT starter kit.

**Comment by johnrotach** [comment]
Hello @Prashant-Kmr,

The first thing to check for this error would be the permissions given to the Cognito identity pool you are using.  In the IAM console you can see your authenticated and unauthenticated roles for the particular Cognito identity pool.  Ensure the policy attached to the applicable role allows permissions to do an UpdateThingShadow to your particular thing, in this case Led2.  An example policy can be found in the [README](https://github.com/awslabs/aws-sdk-android-samples/tree/master/TemperatureControl) of this sample.

You can also modify the onPostExecute method of the UpdateShadowTask class to print the exception.

Try this and let us know the results.

John
AWS IoT

**Comment by Prashant-Kmr** [comment]
Hello John,

Thank you for suggestion. I'll follow it and will update the status.

Regards,
Prashant
