### ISSUE TITLE
Why does the git description say "google"?

### ISSUE THREAD

**Issue by RyPope** [awslabs/aws-sdk-android-samples#56]

**Comment by wdane** [comment]
Can you please explain what/where you mean?  Closing for now until this becomes more clear.

**Comment by RyPope** [comment]
@wdane perhaps "amazon" or "Provides samples for Amazon AWS SDKs" would be more appropriate.

![screen shot 2016-05-25 at 4 39 16 pm](https://cloud.githubusercontent.com/assets/2460153/15623129/724e177e-2425-11e6-89bf-b307e930adf9.png)

**Comment by wdane** [comment]
Thanks for pointing this out, fixed!
