### ISSUE TITLE
Unable to build CognitoSyncDemo

### ISSUE THREAD

**Issue by adedapo** [awslabs/aws-sdk-android-samples#58]
Hello,
Trying to build and run he CognitoSyncDemo but cant build with the error:
 failed to find Build Tools revision 21.1.2
Kindly advice.

Regards,
Emmanuel

**Comment by wdane** [comment]
This means you need to download the specified Android build tools revision. Using the SDK manager within Android Studio or  Eclipse you should be able to browse the latest versions of build tools and SDKs and download the required ones.
