### ISSUE TITLE
S3TransferUtilitySample is not working

### ISSUE THREAD

**Issue by epot** [awslabs/aws-sdk-android-samples#60]
I am trying to use the S3 sample without success: everything is well configured (the same setup works fine on iOS) but I cannot upload anything. It gets stuck at 0.00% (something it manages to send a very small bunch of KB) and stays there forever. Nothing in the logs, no connection or authentication error, I do not really know how to debug that. I am using a Samsung Galaxy S5 with Android 5.0.2, any help would be greatly appreciated.

**Comment by rakesh-3607** [comment]
Hi,

We have implemented this with AWS one time session as well.  (Authenticated
developer identity)

Can you please share code what you are using.

Regards,
Rakesh




On Tue, Jun 7, 2016 at 1:15 PM, epot <notifications@github.com> wrote:

> I am trying to use the S3 sample without success: everything is well
> configured (the same setup works fine on iOS) but I cannot upload anything.
> It gets stuck at 0.00% (something it manages to send a very small bunch of
> KB) and stays there forever. Nothing in the logs, no connection or
> authentication error, I do not really know how to debug that. I am using a
> Samsung Galaxy S5 with Android 5.0.2, any help would be greatly appreciated.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/awslabs/aws-sdk-android-samples/issues/60>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AHmH1LO807A0TCo100ER3JU-vUa0rsvfks5qJSGngaJpZM4IvpeN>
> .
>



-- 
*Regards,*
*Rakesh*

**Comment by epot** [comment]
Hey,

I am not sure I understand your question, sorry. I am using the code sample, without any modification (apart from the changes to use our Cognito identity of course).

Cheers

**Comment by fosterzhang** [comment]
@epot Which region is your S3 in? Does the bucket have special characters like '.' or '-'? What's the size of the object? Does your device connect to a proxy (or Charles)? Is it behind a firewall?

**Comment by epot** [comment]
It is in US-EAST1. The bucket name contains only alphabet characters and a '.'. 

I am trying to upload an image, so a few MB. No proxy or firewall. Thanks !

**Comment by epot** [comment]
It works fine on the emulator, but not on the device, if that can help narrow down the issue.

**Comment by fosterzhang** [comment]
@epot I suggest you try it on a different device. As for the timeout issue, try increasing socket timeout and connection timeout.

**Comment by epot** [comment]
I tried on a different device, same issue. It is probably a firewall issue, but it's hard to point out since it works fine on iOS.
I have a fiber connection, increasing the timeout will definitely not help (I get a timeout because it does not work).

**Comment by fosterzhang** [comment]
@epot I can't reproduce the issue on emulator and device. You also claim that the sample works on emulator. Therefore I assume the SDK is working correctly. My suggestion will be trying the same code on different devices, network, etc.
