### ISSUE TITLE
aws cognito no longer have unauthenticated for identity pool

### ISSUE THREAD

**Issue by dramaticlly** [awslabs/aws-sdk-android-samples#61]
hey, I was following your guide for S3TransferUtility Sample, it seem aws cognito no longer have identityPool for unauthenticated identities. Can anyone update README.md with latest instructions?

**Comment by MarkMerc123** [comment]
Hello,

You can configure your Cognito Federated Identity Pool to accept unauthenticated Identities. 
http://docs.aws.amazon.com/cognito/latest/developerguide/identity-pools.html

With the introduction of our new feature, Cognito User Pools, the Identity Pools to which you are referring is under the "Federated Identities" tab at the top.

-Mark
