### ISSUE TITLE
How can i use "Referer" while uploading a multimedia file

### ISSUE THREAD

**Issue by SkyNite** [awslabs/aws-sdk-android-samples#63]
I need to add custom header while uploading the multimedia files.

I used ObjectMetaData for applying my header, but it not working.  Let me know how can i add my custom header Refer.

**Comment by fosterzhang** [comment]
@SkyNite See [Object Key and Metadata](http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html). Referer isn't a system defined metadata. However you can add it as custom defined metadata which is prefixed with 'x-amz-meta'.

**Comment by SkyNite** [comment]
@fosterzhang : great thanks, will check and update.

**Comment by fosterzhang** [comment]
@SkyNite two issues:
- `ObjectMetadata.setHeader` is internal use only.
- With user metadata, `x-amz-meta` is prepended by the SDK automatically. Simply use "Referer".

See [ObjectMetadata](http://docs.aws.amazon.com/AWSAndroidSDK/latest/javadoc/com/amazonaws/services/s3/model/ObjectMetadata.html) for more information.
