### ISSUE TITLE
AmazonCognitoYourUserPoolsDemo: content_register.xml & activity_register_user.xml refer to AboutApp.java

### ISSUE THREAD

**Issue by jukka-palomaki** [awslabs/aws-sdk-android-samples#64]
Hi,

I think `content_register.xml` and `activity_register_user.xml` should refer to `com.amazonaws.youruserpools.RegisterUser.java `
(not to `com.amazonaws.youruserpools.AboutApp`).

I don't know if that affects the functionality but just wanted to tell so that it will not cause any problems in the future.

BR,

Jukka

**Comment by chetanme** [comment]
Thank you for reporting this. We will fix this with our next release.

**Comment by chetanme** [comment]
This was fixed. Thanks again. Resolving.
