### ISSUE TITLE
Validate token in backend

### ISSUE THREAD

**Issue by neocite** [awslabs/aws-sdk-android-samples#65]
How should I validate the token (CognitoUserSession.getAccessToken ()) in my backend? Is there a method in the type CognitoServerApi.validateUserToken Cognito () API?

**Comment by chetanme** [comment]
No, we do not have any APIs to validate these tokens.

The tokens you get are JWT tokens which can be can be easily decoded for any custom validation. There are several JWT libraries available for different platforms which you can use. You can look at [our documentation](http://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-with-identity-providers.html) for more information about using the tokens that are vended.
