### ISSUE TITLE
Your User Pools sign in does not work with all phone models

### ISSUE THREAD

**Issue by jukka-palomaki** [awslabs/aws-sdk-android-samples#67]
Sign Up works fine with all phones we have tested but Sign In did not work with one model. We did not find any reasonable reason for that. 

07-06 14:14:27.867 20083-20083/com.xxxx.yyyy E/App Error: com.amazonaws.services.cognitoidentityprovider.model.NotAuthorizedException: Incorrect username or password. (Service: AmazonCognitoIdentityProvider; Status Code: 400; Error Code: NotAuthorizedException; Request ID: cdc98891-436a-11e6-a3b0-49b69fd03aa4)

Worked with e.g. 
- Sony M4 Aqua, Android 5.0
- Samsung Galaxy A3, Android 5.0.2

but not with
- Samsung Galaxy S4, Android 5.0.1

We tested with SIM-card+data connection and without (=wifi only). We also tried with Avast virus program and without.

**Comment by fosterzhang** [comment]
@jukka-palomaki Which version of the AWS Android SDK do you use? There was an issue with respect to non English locale in earlier version and has been fixed recently. Please make sure you have the latest version.
