### ISSUE TITLE
Multiple parallel downloads using TransferUtility hanging UI thread

### ISSUE THREAD

**Issue by ckarthikv** [awslabs/aws-sdk-android-samples#68]
We had a use case in which we were trying to download multiple parallel files (around 20 parallel downloads of jpg files) with a transfer listener for each object being downloaded.

The UI thread was hanging badly with just a few parallel downloads.

The normal nomenclature of transferutility.download(bucket, key, file) is being used for each download object. Since the download function returns instantly, all these functions have been written in the main UI thread - Callbacks of the transfer listener have no operations other than printing a log.

Please advise. Thanks.

**Comment by fosterzhang** [comment]
@ckarthikv This is a sample only issue. We'll update the sample to improve UX. The SDK is able to handle large amount of downloads (more than 1k) without blocking the UI.

**Comment by sriram-kakarala** [comment]
@fosterzhang Hi We are using the latest version of Android SDK ie 2.4.4 and are downloading about 20 files. 
1. We see that the max concurrent downloads can be 5 which internal can use max number of HTTP connections which we leave it to the default ie 10. 
2. With this setup the UI thread hangs up completely. If I reduce the number of connections to 3 then it is a little better, but overall the app becomes unresponsive. I could not find a way to reduce overall thread count but I suspect it is the  number of connections causing this.
3. Our block of code is quite simple as shown in Demo, that is use transfer utility to create a download and attach an observer.
4. We use Cognito Authentication and that part works as expected.

**Comment by kvasukib** [comment]
Hi @sriram-kakarala, Sorry for the delayed reply. We released 2.6.16 with enhancements for stability in TransferUtility. Now you have a flag to customize the size of the thread pool for the transfers. We have documented it here: https://docs.aws.amazon.com/aws-mobile/latest/developerguide/how-to-transfer-files-with-transfer-utility.html#native-transfer-utility-options Please let us know if this works for you.

**Comment by sriram-kakarala** [comment]
Hi, Will try and test it once we get back to it. Thanks for adding the capability though!!
