### ISSUE TITLE
YourUserPools does not recover if you give wrong phone number in Sign Up

### ISSUE THREAD

**Issue by jukka-palomaki** [awslabs/aws-sdk-android-samples#69]
Steps to repro:
-Do Sign Up 
-Fill all asked fields, enter incorrect phone number
-Tap Sign up button -> View is changed to Confirm view, SMS confirmation is sent to wrong number
-Return from Confirmation view to fix phone number
-Fix phone number and tap sign up button
Actual result:
Sign up failed, User already exists. 
-> User account is already created with wrong phone number. Confirm code is never received. Account sign-in is not possible since account is not confirmed. Changing phone number of already created account is not possible since sign-in is not possible.
Expected result:
It should be possible to return for fixing wrong information and then return confirm code again.

**Comment by yishafang** [comment]
Hi,
User is not able to change wrong phone number once the user is signed up. To fix wrong phone number or other wrong user attributes provided during signed up, user needs to contact the developer. 
Developer can use adminUpdateUserAttributes API to update the specified wrong user attribute, and then, user can call resendConfirmationCode to get the code to finish confirmation.
Look here for more info http://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AdminUpdateUserAttributes.html

**Comment by jukka-palomaki** [comment]
Ok thanks.

**Comment by litalch** [comment]
Hi,

When will you fix this issue?

Thank you

**Comment by kvasukib** [comment]
This is the current behavior in the AWS Cognito Service. We are taking it as a feature request.

**Comment by muellerfr** [comment]
Hello @jukka-palomaki and @litalch,

We're tracking this request with issue https://github.com/aws/aws-sdk-android/issues/543.
