### ISSUE TITLE
NotAuthorizedException: Incorrect username or password in AmazonCognitoYourUserPoolsDemo

### ISSUE THREAD

**Issue by volic** [awslabs/aws-sdk-android-samples#70]
I can successfully create user with sample. I verify user well by email. I see created user in AWS console.
Unfortunately I cannot login with sample if it uses 2.2.15+ version in gradle. Please, switch library version to the 2.2.20. When I switch the version to 2.2.20 everything works correctly.

**Comment by kvasukib** [comment]
Hi @volic,

The latest version of SDK fixes the issue. Closing the issue.
