### ISSUE TITLE
Questions about AmazonCognitoYourUserPoolsDemo

### ISSUE THREAD

**Issue by jukka-palomaki** [awslabs/aws-sdk-android-samples#71]
Hi,

Are you going to add token handling to AmazonCognitoYourUserPoolsDemo so it can be easily integrated to Mobile Hub based app (using IdentityManager and SignInManager classes)? 

Another related question: Is Mobile Hub app generator going to include Your User Pools in the future? 

Any estimates of schedules? :)

BR,

Jukka

**Comment by wdane** [comment]
Unfortunately the Mobile Hub sample app, and those in this repo and distinct and aren't built to use with each other.

And as to the related question, we typically do not release information about unreleased features. That being said, we do think User Pools would be a great addition to Hub, and I will keep this issue open as a feature request.

**Comment by achud** [comment]
The User Pools feature has now been added to the AWS Mobile Hub sign in provider options. You can configure User Pools by selecting "Email & Password" as an option on the sign-in feature. And, you will get the appropriate demo functionality in the sample app and minimal SDK downloads from the Mobile Hub "Integrate" page.
