### ISSUE TITLE
You can delete required attributes in AmazonCognitoYourUserPoolsDemo

### ISSUE THREAD

**Issue by jukka-palomaki** [awslabs/aws-sdk-android-samples#72]
Hi,

There are no checks for deleting attributes. You can delete also required attributes. I think it would be logical to allow only editing of required fields (so that it is not edited to be empty). Deleting mandatory fields sounds like a bug. 

BR,

Jukka

**Comment by mreddyg** [comment]
Hi Jukka,

This is a known issue, we are working towards fixing it. 

Regards,
Mahesh

**Comment by jukka-palomaki** [comment]
Thanks!

**Comment by kushwahavinay** [comment]
This issue has been fixed.

**Comment by jukka-palomaki** [comment]
Yes I noticed that. Thanks!
