### ISSUE TITLE
Hi team

### ISSUE THREAD

**Issue by ananthramasamy23** [awslabs/aws-sdk-android-samples#73]
Can you anyone share how to make shop online concept (shipping integration )using amazon Api 

Please share any one...

Regards 
Anandharaj.R
Android Developer
SQindia pvt Ltd

**Comment by rohandubal** [comment]
Hi, This is the AWS Android SDK Samples repo, specifically containing samples for accessing AWS services from Android platform and not related to shipping integration. Please post your question on Amazon forums where this can be better answered. Thanks.

**Comment by ananthramasamy23** [comment]
Thanks rohandubal
