### ISSUE TITLE
User pool update attribute issue - Android

### ISSUE THREAD

**Issue by jayappmobi** [awslabs/aws-sdk-android-samples#74]
I am trying to update my attribute using this method below: 

AwsHelper.getPool().getCurrentUser().updateAttributes(userAttributes, updateHandler);

token and attributes are correct but i m getting below error: 

java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference

But my attributes are updated.

can you help me out why "updateUserAttributesResult.getCodeDeliveryDetailsList()" returns me null?

Thanks in advance
Jay.

**Comment by mreddyg** [comment]
Hi Jay,

In which version of the SDK for Android did this exception appear?

Thanks,
Mahesh

**Comment by jayappmobi** [comment]
i  am using following dependencies : 

   compile 'com.amazonaws:aws-android-sdk-cognitoidentityprovider:2.2.20'
    compile 'com.amazonaws:aws-android-sdk-ddb-mapper:2.2.21'
    compile 'com.amazonaws:aws-android-sdk-core:2.2.21'
    compile 'com.amazonaws:aws-android-sdk-cognito:2.2.21'

**Comment by mreddyg** [comment]
Thank you for these details.
Have you seen this exception appear when updating user attributes before this occurrence?

**Comment by jayappmobi** [comment]
I think it appears after attributes updated and response got.

i am getting response in updateUserAttributesResult as below :

UpdateUserAttributesResult updateUserAttributesResult =                  updateAttributesInternal(attributes, session);


updateUserAttributesResult.getCodeDeliveryDetailsList() is null.

and implementtation of updateAttributesInternal is below : 

 private UpdateUserAttributesResult updateAttributesInternal(final CognitoUserAttributes attributes,
                                          final CognitoUserSession session) {
        if (session != null && session.isValid()) {
            UpdateUserAttributesRequest updateUserAttributesRequest = new UpdateUserAttributesRequest();
            updateUserAttributesRequest.setAccessToken(session.getAccessToken().getJWTToken());
            updateUserAttributesRequest.setUserAttributes(attributes.getAttributesList());

            return cognitoIdentityProviderClient.updateUserAttributes(updateUserAttributesRequest);
        } else {
            throw new CognitoNotAuthorizedException("user is not authenticated");
        }
    }

**Comment by jukka-palomaki** [comment]
I get this same error below with com.amazonaws:aws-android-sdk-cognitoidentityprovider:2.3.0 when modifying attribute or adding it. Phone number update works better. But e.g. Family Name and Middle name give this error. Could you please fix this?

```
com.amazonaws.youruserpools.CognitoYourUserPoolsDemo E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.amazonaws.youruserpools.CognitoYourUserPoolsDemo, PID: 6591
java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser$11$1.run(CognitoUser.java:1149)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:145)
at android.app.ActivityThread.main(ActivityThread.java:6145)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
```

**Comment by jukka-palomaki** [comment]
When I went back to 2.2.18 version it started to work again.

**Comment by jayappmobi** [comment]
@jukka-palomaki , are you able to modify all attributes using  2.2.18 version ?

**Comment by jukka-palomaki** [comment]
I did not test them all but I can do it now.

**Comment by jukka-palomaki** [comment]
Yes all I can modify. I tested with my own app but I believe that your demo app has the same thing because it happened at least with part of the attributes also with the demo app (i did not test all attbitutes but enough in my opinion).

I also tested 2.2.20 and 2.2.21 with my own app but they too had this bug.

**Comment by jayappmobi** [comment]
@jukka-palomaki , can you please provide dependencies you are using for aws?

**Comment by jukka-palomaki** [comment]
This currently works with my app. 
    compile('com.amazonaws:aws-android-sdk-cognito:2.2.18')
    compile('com.amazonaws:aws-android-sdk-cognitoidentityprovider:2.2.18')
    compile('com.amazonaws:aws-android-sdk-core:2.3.0')
    compile('com.amazonaws:aws-android-sdk-ddb:2.3.0')
    compile('com.amazonaws:aws-android-sdk-ddb-mapper:2.3.0')
    compile('com.amazonaws:aws-android-sdk-lambda:2.3.0')
    compile('com.amazonaws:aws-android-sdk-mobileanalytics:2.3.0')
    compile('com.amazonaws:aws-android-sdk-s3:2.3.0')
    compile('com.amazonaws:aws-android-sdk-sns:2.3.0')

**Comment by jayappmobi** [comment]
thanks @jukka-palomaki , It helped me. for now i am going to use above. 

@mreddyg , please provide solution for latest version of dependencies to solve described bug

**Comment by mreddyg** [comment]
Thanks @jukka-palomaki @jayappmobi this is a bug in the SDK for Android. The next version of SDK for Android will have this bug fixed. I expect the new version to be available within a couple of weeks.

**Comment by jayappmobi** [comment]
Thanks @mreddyg

**Comment by jukka-palomaki** [comment]
Thank you.

**Comment by aznshodan** [comment]
I also had the same problem as @jukka-palomaki and @jayappmobi. So i changed mine to 
`compile('com.amazonaws:aws-android-sdk-cognito:2.2.18')`
However this seems to fail to import the following:
```
import com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoDevice;
import com.amazonaws.mobileconnectors.cognitoidentityprovider.continuations.ChallengeContinuation;

```
Has anyone figured this out yet?

**Comment by kung-lou** [comment]
I am having this exact issue when trying to update a custom attribute - very frustrating. I have tried 2.3.3 and 2.2.18 as suggested above. Still Not working.

E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.opboomtown.com.boomtownalpha2, PID: 5864
                  java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
                      at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser$11$1.run(CognitoUser.java:1149)
                      at android.os.Handler.handleCallback(Handler.java:739)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:148)
                      at android.app.ActivityThread.main(ActivityThread.java:5417)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by Yogi-p** [comment]
Hi,
I am using the dependencies as below:
compile 'com.amazonaws:aws-android-sdk-core:2.2.22'
    compile 'com.amazonaws:aws-android-sdk-s3:2.2.22'
    compile 'com.amazonaws:aws-android-sdk-ddb:2.2.22'
    compile 'com.amazonaws:aws-android-sdk-cognitoidentityprovider:2.2.22'

Still getting same error as above while updating email attribute of cognito user:

java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser$12$1.run(CognitoUser.java:1333)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95)

Can you please help me to resolve it?

**Comment by jukka-palomaki** [comment]
You have quite old aws libraries. Newest official version is 2.6.10.

**Comment by Yogi-p** [comment]
Thanks jukka-palomaki
I have changed dependancies to 2.6.10. It has resolved my crash but now getting blank attributesVerificationList in OnSuccess method:
Here is my code:

 CognitoConfig.createUserPool(activity);

        CognitoUserAttributes userAttributes = new CognitoUserAttributes();
        // Add the user attributes. Attributes are added as key-value pairs
        userAttributes.addAttribute("email", editEmailText);

        UpdateAttributesHandler handler = new UpdateAttributesHandler() {
            @Override
            public void onSuccess(List<CognitoUserCodeDeliveryDetails> attributesVerificationList) {
                            view.navigateToHome();
                        }, throwable -> {
                            int messageId = R.string.update_email_error_generic;
                            view.hideKeyboard();
                            view.displayError(messageId);
                        });
            }

            @Override
            public void onFailure(Exception exception) {
                exception.printStackTrace();
                Log.e("Request fail", exception.toString());
            }
        };
        CognitoConfig.getUserPool().getCurrentUser().updateAttributesInBackground(userAttributes, handler);
    }

Is that anything i am missing?

**Comment by jukka-palomaki** [comment]
I am using now CognitoUserPool.signUpInBackground(). I don't have a need to update attributes.

**Comment by jukka-palomaki** [comment]
What is the actual error in the log?
