### ISSUE TITLE
How to use user pool with Federated Identities  ?

### ISSUE THREAD

**Issue by Poslwa** [awslabs/aws-sdk-android-samples#77]
Hi;

I'm using AmazonCognitoYourUserPoolsDemo it works perfect. But i want to use user pool with Federated Identities, there is a good tutorial link below, i did step by step configure all requirements but when i sign-in successfully with AmazonCognitoYourUserPoolsDemo nothing change in Identity pool and Identities still empty in . Is there any example with user pool with Federated Identities working together?

http://docs.aws.amazon.com/cognito/latest/developerguide/tutorial-integrating-user-pools-android.html

In this tutorial Step 8:

```
   AuthenticationHandler authenticationHandler = new AuthenticationHandler() {
        @Override
        public void onSuccess(CognitoUserSession cognitoUserSession, CognitoDevice device) {
            Log.e(TAG, "Auth Success");

            // Get id token from CognitoUserSession.
            String idToken = cognitoUserSession.getIdToken().getJWTToken();

            CognitoCachingCredentialsProvider credentialsProvider =
                    new CognitoCachingCredentialsProvider(getApplicationContext(), "eu-west-1:6bda4f27-8258-46c7-87e1-c5c6453f304d", Regions.EU_WEST_1);

            Map<String, String> logins = new HashMap<String, String>();
            logins.put("cognito-idp.eu-west-1.amazonaws.com/eu-west-1_mt8NnZ5Zi", cognitoUserSession.getIdToken().getJWTToken());
            credentialsProvider.setLogins(logins);
  @@@
           // credentialsProvider.refresh();

            AppHelper.setCurrSession(cognitoUserSession);
            AppHelper.newDevice(device);
            closeWaitDialog();
            launchUser();
        }

        @Override
        public void getAuthenticationDetails(AuthenticationContinuation authenticationContinuation, String username) {
            closeWaitDialog();
            Locale.setDefault(Locale.US);
            getUserAuthentication(authenticationContinuation, username);
        }

        @Override
        public void getMFACode(MultiFactorAuthenticationContinuation multiFactorAuthenticationContinuation) {
            closeWaitDialog();
            mfaAuth(multiFactorAuthenticationContinuation);
        }

        @Override
        public void onFailure(Exception e) {
            closeWaitDialog();
            TextView label = (TextView) findViewById(R.id.textViewUserIdMessage);
            label.setText("Sign-in failed");
            inPassword.setBackground(getDrawable(R.drawable.text_border_error));

            label = (TextView) findViewById(R.id.textViewUserIdMessage);
            label.setText("Sign-in failed");
            inUsername.setBackground(getDrawable(R.drawable.text_border_error));

            showDialogMessage("Sign-in failed", AppHelper.formatException(e));
        }

        @Override
        public void authenticationChallenge(ChallengeContinuation continuation) {
            // TODO change the place holder
        }
    };
```

**Comment by Citizen01** [comment]
I passed several days to do that as well and I managed to do it.
Once you authenticated your user against your **User Pool**, then you will get an **id JWT token** (valid 30days by default). So that's what your code does and yes it won't show anything **_yet_** in your **Federated Identity Pool**. 

You have to give your **credentialsProvider** to an AWS service client for it to use. The client will use that credential provider for each request you ask it to make and will exchange the **User Pool id token** for a **Federated Identity access token** in background only if needed (On 1st request and when the **Federated Identity access token** has expired).

Once the exchange has been made, you should see your identity in your **Federated Pool** identities.
I'm still new to this but it seems to work for me:
![federated identities pool](https://i.gyazo.com/55157bdbebd02f1b9b1bc00ddb0792ad.png)

**Comment by MarkMerc123** [comment]
As Citizen01 described, the user will not appear in your federated pool until you actually use the credentials provider. You can do this by using it to call another service, or calling credentialsProvider.getIdentityId();

Hope this solves the issue you were having!

**Comment by ngoyal16** [comment]
Hello @karthiksaligrama i am facing this issue.. 

i setup the logins previously but when i am trying to use credentialsProvider.getIdentityId() it reset it

D/CognitoCachingCredentialsProvider: Loading credentials from SharedPreferences
D/CognitoCachingCredentialsProvider: No valid credentials found in SharedPreferences

could you refer a proper example of using identity pool with user pool
