### ISSUE TITLE
Error:Execution failed for task ':packageDebug'. > Failed to read key iot_keystore_alias from store "AWS/New_certificates_n.virginia_22_aug/iot_keystore.bks": Invalid keystore format

### ISSUE THREAD

**Issue by vnarendra5a1** [awslabs/aws-sdk-android-samples#78]
Created keystore file by following above mentioned steps, but while building the application I am getting the following error.
Kindly suggest me how to resolve the error.

**Comment by johnrotach** [comment]
The first thing to check is listing the keystore contents and ensuring the certificate is present.  If you run

```keytool -list -v -keystore iot_keystore.bks```

is your certificate alias listed?  Did you create the keystore using the BKS provider?

**Comment by karthiksaligrama** [comment]
assuming this issue is resolved. closing
