### ISSUE TITLE
error while uploading to s3

### ISSUE THREAD

**Issue by Kirancloudnix** [awslabs/aws-sdk-android-samples#80]
Error initiating multipart upload: 17 due to The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint. (Service: Amazon S3; Status Code: 301; Error Code: PermanentRedirect; Request ID: 40FC2FD126D8C931)
09-07 23:37:53.394 8971-8971/com.amazonaws.demo.s3transferutility E/UploadActivity: Error during upload: 17
                                                                                    com.amazonaws.services.s3.model.AmazonS3Exception: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint. (Service: Amazon S3; Status Code: 301; Error Code: PermanentRedirect; Request ID: 40FC2FD126D8C931), S3 Extended Request ID: 8oU+qaaQ126cqFpWps3X++bbsKz1oNvhf/0MQ3Cq4G+m6wXuYLP2VB68S+do68HwJEBQYtCW9Lw=

**Comment by i-khan** [comment]
getting same error

**Comment by mlshon** [comment]
Hello,
Could you check what region you're using? Check that you're using a valid endpoint specific to the bucket you're attempting to access.

**Comment by minbi** [comment]
Please re-open if there are still issues
