### ISSUE TITLE
S3TransferUtilitySample - Make public an uploaded file ( Android )

### ISSUE THREAD

**Issue by grovertb** [awslabs/aws-sdk-android-samples#82]
Hello,
I'm having problems when the file is uploaded as I change the permissions to make public
Eh already reviewed the issue [46](https://github.com/awslabs/aws-sdk-android-samples/issues/46) but not achieving the solution, someone who can guide me.

Thanks!

**Comment by kvasukib** [comment]
Hi @grovertb,
What is the version of SDK you are using? Is there an exception thrown when you upload a file? Can you post the exception message and the stack trace?
