### ISSUE TITLE
Failed to download: 1 due to The requested range is not satisfiable

### ISSUE THREAD

**Issue by jonasze** [awslabs/aws-sdk-android-samples#85]
Hi, 
I have problems downloading files from S3 to my android app using a merged Cognito/S3TransferUtility app. I can copy the whole stack trace but the central issue seems to be

 Failed to download: 1 due to The requested range is not satisfiable (Service: Amazon S3; Status Code: 416; Error Code: InvalidRange; Request ID: BBA7FCE8A5FA9C4B)

com.amazonaws.services.s3.model.AmazonS3Exception: The requested range is not satisfiable (Service: Amazon S3; Status Code: 416; Error Code: InvalidRange; Request ID: BBA7FCE8A5FA9C4B), S3 Extended Request ID: iSBDXNaXQnZeodu0rum5l8ZRLXFWaJOswLjm+ZY1jVHHD3iEDhlwEds/TLol96yAT8CaCdF7iEc=

Any ideas?
cheers

**Comment by minbi** [comment]
Hi @jonasze 

Are you providing the range field in your S3 request? If so, you may have requested a range larger then your file size.

If you have further questions, please provide the necessary code and/or steps to reproduce error.

**Comment by JairAviles** [comment]
I came across with the same problem. However, I am not understanding about providing a range field in the S3 request or setting up a new AVd. How do I do that within my application? I searched the internet for more information related, but haven't found a proper documentation yet.

**Comment by jonasze** [comment]
Hi,
I remember solving it by clearing cashes, updating the API or similar. The
error message should actually state: Something in the background fucked up
and we don't know what.
