### ISSUE TITLE
possible to delete item from DynamoDB table without 'primarykey' or 'hashkey' or 'partition key'/

### ISSUE THREAD

**Issue by jayappmobi** [awslabs/aws-sdk-android-samples#86]
I m working on android and need to delete item based on the sort key or any notmal attribute/field of table

is that possible?

As i have reviewed the documents by Amazone, but not able to find solution for it

**Comment by wdane** [comment]
Unfortunately it is not possible to delete without the primary key (hash/partition key). The only option in this case would be to scan or query for all the items, putting the primary key of each item you want to delete in a list. Then you can use BatchWriteItem to delete them in large batches.
