### ISSUE TITLE
S3TransferUtilitySample sometimes is not working (URGENT)

### ISSUE THREAD

**Issue by hvar90** [awslabs/aws-sdk-android-samples#87]
i have a  app for chating and when i test on my celphone all works well but some users of my app they have problems uploading files
i have :
 SocketTimeout=150000;
 ConnectionTimeout=150000;
 basePathToUpLoad="files/image_messages/"

so my question is
this sdk only works for few devices?? what could be the real problem and what is the solution ??? 

thanks

**Comment by mlshon** [comment]
Hello,
The SDK only supports Android 2.3.3 (API Level 10) or higher.

Could you please provide more information? What is the stacktrace of this error?
Do you also have metrics on which device is having the issue?

**Comment by hvar90** [comment]
for the moment i dont have the stacktrace of the error because the problem happen on some users of my app, but i have more information
the problem happen with some images or videos to upload, sometimes it upload well but sometimes the progress bar stop and the upload also is stopped  
and the devices with problems for example 
Atongm H3 ,LG F60, but also with some samsung cellphones

**Comment by mlshon** [comment]
Are you using the latest SDK version? Does it have network connectivity available?
What is the API level of the failing devices?
Without a stacktrace, it's hard to diagnose any possible issues.

**Comment by hvar90** [comment]
Are you using the latest SDK version? **Yes**
Does it have network connectivity available? **Yes** 
What is the API level of the failing devices? API 23 API 17
Without a stacktrace, it's hard to diagnose any possible issues.
my problem is similar to this https://github.com/aws/aws-sdk-android/issues/186

**Comment by mlshon** [comment]
As I mentioned it's hard to diagnose the problem without a stacktrace.
Similar to #186, my thoughts are the same.  I suspect that internet is failing in between.
I'm going to close this issue, and you can reopen when you have more definite information/stacktrace.

**Comment by hvar90** [comment]
i was able find the stacktrace of the problem
i have used my emulator and when i try upload a imagen, it sometimes works and it sometimes doesnt work and this is the information/stacktrace
these are 2 cases when it failed
E/UploadTask: Failed to upload: 3 due to Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed. (Service: Amazon S3; Status Code: 400; Error Code: RequestTimeout; Request ID: 2537BDA6D6D2AD9F)

E/UploadTask: Failed to upload: 1 due to Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed. (Service: Amazon S3; Status Code: 400; Error Code: RequestTimeout; Request ID: 8B007ECB053E175C)

also i have a question i have this configuration 
config.setMaxErrorRetry(3);
but when i get the error, it did not try again to upload the image, so, how can i try many times after that my upload fail ??
