### ISSUE TITLE
Forbidden Exception on accessing AWSIotData. 

### ISSUE THREAD

**Issue by Arudroid** [awslabs/aws-sdk-android-samples#88]
I tried executing the smaple project TemperatureControl. I followed the steps mentioned and the setup is as mentioned. But while getting or updating the thing shadow I get an forbidden exception. Could you please tell me what might be the reason.

Below is exception message:
ShadowResponsecom.amazonaws.AmazonServiceException: Forbidden (Service: AWSIotData; Status Code: 403; Error Code: ForbiddenException; Request ID: 12e3f9c9-1f29-8541-ee51-9653e0bef746)

**Comment by wdane** [comment]
This is likely caused by an IAM (Identity and Access Management service) misconfiguration. Has the client been granted permission?
