### ISSUE TITLE
PubSub - Infinite KeepAlive

### ISSUE THREAD

**Issue by lauleehong** [awslabs/aws-sdk-android-samples#89]
Hi,

I'm building on top of the PubSub example. I'm using the default keep alive:
 `        mqttManager.setKeepAlive(10);`

When I was disconnected for more than an hour (and then later reconnected), the client no longer tries to reconnect. How can I go about having it attempt reconnecting/ping to the MQTT Client infinitesimal every 10sec?

**Comment by chaurah** [comment]
Hi @lauleehong,
The sample you are using only retries up to the default maximum number of retries (set [here](https://github.com/aws/aws-sdk-android/blob/master/aws-android-sdk-iot/src/main/java/com/amazonaws/mobileconnectors/iot/AWSIotMqttManager.java#L80)). After that a manual reconnect is required. If you want to attempt a larger number or infinite retries, you can call the [setMaxAutoReconnectAttepts API](https://github.com/aws/aws-sdk-android/blob/master/aws-android-sdk-iot/src/main/java/com/amazonaws/mobileconnectors/iot/AWSIotMqttManager.java#L280). A value of -1 indicates infinite reconnect.

Please let us know if you have any further questions. Thank you for using AWS IoT.

Rahul

**Comment by minbi** [comment]
Please re-open if there are still issues
