### ISSUE TITLE
Android AWS s3 transfer Failing: D/TransferService: Stop self

### ISSUE THREAD

**Issue by gwicks56** [awslabs/aws-sdk-android-samples#90]
Uploading large video files to S3 Bucket from Android phone, occasionally the uploaded is stopped with the message:

D/TransferService: Stop self

Not sure why it does this only occasionally. Was thinking it was to do with the garbage collector clearing my TransferListener, but it appears that problem was fixed in 2.2.13.

Happens very occasionally, but annoying when it does. Here is my code:

`protected Void doInBackground(String... params) {

			String filePath = params[0];

			if (filePath == null) {
				Log.d("Video", "Could not find the filepath of the selected file");
				//return;
			}

			File file = new File(filePath);
			try{

				final TransferObserver observer = transferUtility.upload(Constants.BUCKET_NAME, newFilePath,
						file);
				observer.setTransferListener(new TransferListener() {
					@Override
					public void onStateChanged(int id, TransferState state) {

						observer.getState();

					}

					@Override
					public void onProgressChanged(int id, long bytesCurrent, long bytesTotal) {
						double percentage = ((double)bytesCurrent/bytesTotal);
						int one = (int)(percentage * 100);

						Log.d("Progress", "Progress in upload is: " + percentage);
						Log.d("Progress", "Progress in upload for longOne is: " + one);
						Log.d("Progess", "The state of the observer is: " + observer.getState());

						int percentageInt = (int)(percentage);
						publishProgress(one);
						//progressBar.setProgress(one);

						if(one == 100)
						{
							progressBar.setVisibility(View.GONE);
						}

					}

					@Override
					public void onError(int id, Exception ex) {

					}

				});
			}catch (AmazonS3Exception s3Exception)
			{
				Log.d("aws","error contacting amazon");
			}

			Log.d("Video", "finshed upload in beginupload");

			return null;
		}`

**Comment by kvasukib** [comment]
Hi @gwicks56,

Thanks for reporting to us. Sorry for the delayed response.
What version of SDK are you using now? Does this issue still occur occasionally?

Thanks

**Comment by kvasukib** [comment]
Closing this issue. Please re-open or open a new one if the issue exists with the latest version of the SDK 2.6.13.
