### ISSUE TITLE
Unable to calculate MD5 hash

### ISSUE THREAD

**Issue by achinverma** [awslabs/aws-sdk-android-samples#91]
Hi, i am uploading image and getting this error

`Unable to calculate MD5 hash: /data/user/0/competent.groove.feetport/files/data/user/0/competent.groove.feetport/app_imageDir/IMG_20161122_073058.jpg: open failed: ENOENT (No such file or directory)`

**Comment by minbi** [comment]
Hi achinverma,

Could you provide some steps to reproduce?
Please include which version of the SDK you are using and a sample image if possible.

Thank you.
