### ISSUE TITLE
Login with Amazon - Did't redirect to app after Login

### ISSUE THREAD

**Issue by krasystem** [awslabs/aws-sdk-android-samples#93]
I have implemented Login with Amazon in android app.
Everything works fine in android Marshmallow and i can get IdentityID.

**But i am facing problem in android KitKat, the app did't redirect after successfully Login.**

I am using the following snippet to authrize

`AuthorizationManager.authorize(
                    new AuthorizeRequest.Builder(requestContext)
                    .addScopes(ProfileScope.profile(), ProfileScope.postalCode())
                    .build());`

**The page load with error** 
> This site can't be reached.

**Note : App works fine with Amazon shopping App, problem occurred in external browser(chrome and default browser)**

**Comment by karthiksaligrama** [comment]
This repo is for AWS SDK's. For Login with Amazon i support you open a discussion @ http://login.amazon.com/support
