### ISSUE TITLE
Exception occurred when generating new private key and certificate.

### ISSUE THREAD

**Issue by andruino** [awslabs/aws-sdk-android-samples#96]
I am new in AWS,  I wanted to test the pubsub in Android, but always appears "Exception occurred when generating new private key and certificate". I have been trying several reported solutions as https://docs.google.com/document/d/1ZC243SuZiXJU_TvhMB293z8XC_SQv2wa6gWCXApxg94/edit with no success 
Any idea? Exists a complete sample to integrate Android's sensor in AWS ioT?

**Comment by chaurah** [comment]
Hi @andruino,
      Can you please provide a reference of where you found the google doc? Did you try the steps mentioned in the Readme that is located [here](https://github.com/awslabs/aws-sdk-android-samples/tree/master/AndroidPubSub)? Which step did you get the error you are mentioning above in?

Please let us know so we can provide you with proper information. Thank you for using AWS IoT.

Rahul

**Comment by andruino** [comment]
Apparently (I am newbie in AWS), I have followed all the steps without error (except  "
Creating a Keystore for Use with AWS IoT", but it is commented in the code). 

I get the application is running in the Android, but not I can connect (the button connect not is active in the app) and in the Logcat appears:

D/CognitoCachingCredentialsProvider(26677): Loading credentials from SharedPreferences

 I/AmazonWebServiceClient(26677): {execute-api, us-east-1} was not found in region metadata, trying to construct an endpoint using the standard pattern for this region: 'execute-api.us-east-1.amazonaws.com'.

 I/com.amazonaws.demo.androidpubsub.PubSubActivity(26677):Keystore /data/data/com.amazonaws.demo.androidpubsub/files/iot_keystore not found.

 I/com.amazonaws.demo.androidpubsub.PubSubActivity(26677): Cert/key was not found in keystore - creating new key and certificate.

 E/com.amazonaws.demo.androidpubsub.PubSubActivity(26677): Exception occurred when generating new private key and certificate.

I tried changing my region to the N.Virginia, I repeated all the operations there, but it gave the same result: -( 
I've copied the CUSTOMER_SPECIFIC_ENDPOINT from  Settings in the IoT Console.
I've copied the  COGNITO_POOL_ID from the final screen of the Cognito process.
I've copied the  AWS_IOT_POLICY_NAME from Security/Policy in the IoT console.
I am using Eclipse and copied into lib the libraries AWS-android-sdk-core-2.3.8. jar and aws-android-sdk-iot-2.3.8. jar
In the cognito identity pool's screen appears a graph showing "1 identities" (?)
Any idea?

**Comment by andruino** [comment]
Thanks for your help!

**Comment by fengsongAWS** [comment]
Hi @andruino ,
It seems you are trying to run the pub/sub sample using Cognito. Could you try using region us-west-2, Oregon, and see if it works?
Thanks,
Fengyi

**Comment by andruino** [comment]
I tried first with Oregon, before N.Virginia, with the same results.
I have also exported the Android aplication in order to include the keystore, with no results...

**Comment by andruino** [comment]
Thanks

**Comment by andruino** [comment]
Now I have tried with the example CreateCertFromCsrActivity.

The exeption appears in the line:
" CreateCertificateFromCsrResult result = iotClient.createCertificateFromCsr(request);" of the file CreateCertFromCsrActivity.java

Expanding the code to get more information from logcat, the error is:
01-05 15:32:30.834: E/com.amazonaws.demo.csrcert.CreateCertFromCsrActivity(5118): An error occurred while creating the CSR and calling create certificate API.com.amazonaws.AmazonClientException: Unable to execute HTTP request: Unable to resolve host "cognito-identity.us-east-1.amazonaws.com": No address associated with hostname

So, it seems a name resoltion problem, but....

But executing nslookup "cognito-identity.us-east-1.amazonaws.com", the results are

Name:  cognito-identity.us-east-1.amazonaws.com
Addresses:  54.174.165.54
          54.84.104.0
          52.54.31.110
          52.0.207.59
          52.20.248.202
          54.173.183.169

And the URL https:://54.174.165.54 in Chrome of the Android phone show the Cognito page
(Also check that in the Manifest of the app appears
 <uses-permission android:name="android.permission.INTERNET" />)

Any ideas???

**Comment by fengsongAWS** [comment]
It seems you got the wrong Cognito Identity. Cognito ID is supposed to be a string like "us-west-2:XXX-XX-XX" which could be found in either sample code of your Identity Pool or settings. Could you double check on that and see if it works?

Thanks,
Fengyi

**Comment by muellerfr** [comment]
This issue has been closed because of inactivity. Please open a new issue in https://github.com/aws/aws-sdk-android/issues if you are still encountering problems.
