### ISSUE TITLE
NotAuthorizedException: Unauthenticated access is not supported for this identity pool. when accessing dynamodb

### ISSUE THREAD

**Issue by jayappmobi** [awslabs/aws-sdk-android-samples#98]
i am using authentication using cognito and done it successfully
saving token with setLogins method of credential provider.

NotAuthorizedException: Unauthenticated access is not supported for this identity pool issue is coming randomly, when trying to make Dynamodb call.

After once this issue occur and i restart app, it is not happening again

i am not able to figure out issue.

sdk i m using  are as below :
   compile 'com.amazonaws:aws-android-sdk-cognitoidentityprovider:2.3.8'
    compile 'com.amazonaws:aws-android-sdk-ddb-mapper:2.3.8'
    compile 'com.amazonaws:aws-android-sdk-core:2.3.8'
    compile 'com.amazonaws:aws-android-sdk-cognito:2.3.8'
    compile 'com.amazonaws:aws-android-sdk-sns:2.3.8'

Thanks in advance

**Comment by jbailey2010** [comment]
Are you just using setLogins? If so, you'll need to call refresh on the credentials provider afterwards to get new credentials. Calling setLogins alone won't do this.

If you're already doing both, can you provide a snippet of your app where this issue is being hit?

**Comment by jayappmobi** [comment]
@jbailey2010, it worked.
But can you tell me if it takes some time to refresh?
Because if i call dynamodb call immediately after refresh, it gives same error as i mentioned in title and if i put some delay,  it works like charm.
If so how can i make faster refresh?

**Comment by jbailey2010** [comment]
Refresh calls Cognito's GetCredentialsForIdentity API, which might take some time. All you can really do to minimize this is maximize how long the credentials can be used, but that doesn't apply to the initial sign in which is what you're running into. Not much you can do there, other than just have your Dynamo logic kick in after refresh has completed. It's worth noting that the refresh call isn't asynchronous in the android SDK, which you may have already seen.

**Comment by jayappmobi** [comment]
ok got it
Thanks @jbailey2010
