### ISSUE TITLE
getting 403 AccessDeniedException 

### ISSUE THREAD

**Issue by vigneswarandavarapu** [awslabs/aws-sdk-android-samples#99]
Unable to get available voices. User: arn:aws:sts::235205248229:assumed-role/Cognito_pollydemoUnauth_Role/CognitoIdentityCredentials is not authorized to perform: polly:DescribeVoices (Service: AmazonPolly; Status Code: 403; Error Code: AccessDeniedException; Request ID: 59976f52-d8ac-11e6-8784-231fce1f9314)

**Comment by mlshon** [comment]
You can follow the Polly sample's README file to see how to attach a policy to that role
